/* eslint-disable @nx/enforce-module-boundaries -- the generated course lives in prisma/seed-data, outside any nx project; these tests exist to pin it */
import { DEFAULT_QUIZ_QUESTION_COUNT, MODULE_PASSING_SCORE } from '@kambriq/common/constants/kbs';
import { LESSON_CONTENT_TYPES } from '@kambriq/common/constants/kbs/lesson-content';
import {
  KCA1_CONTENT_TYPE,
  KCA1_PARCOURS,
  KCA1_QUESTIONS,
} from '../../../../../prisma/seed-data/kca1';

/**
 * Step 2: the generated KCA1 course, asserted as data rather than as a run.
 *
 * The loader is proved on a fixture in `kca1-loader.spec.ts`. This file pins
 * what the loader actually produced from the real source and committed, because
 * that generated module is what a candidate will be taught from - and it can be
 * regenerated by anybody at any time from a document only Visquis edits.
 */

const LESSONS = KCA1_PARCOURS.flatMap((parcours) => parcours.lessons);
const SLOTS = LESSONS.flatMap((lesson) => lesson.slots);

describe('KCA1 generated course - structure', () => {
  it('is the four parcours, in the order the document states them', () => {
    expect(KCA1_PARCOURS.map((p) => p.code)).toEqual(['P0', 'P1', 'P2', 'P5']);
    expect(KCA1_PARCOURS.map((p) => p.order)).toEqual([1, 2, 3, 4]);
  });

  it('carries 33 lessons, 8/8/9/8', () => {
    expect(KCA1_PARCOURS.map((p) => p.lessons.length)).toEqual([8, 8, 9, 8]);
    expect(LESSONS).toHaveLength(33);
  });

  it('gives every parcours its title, subtitle and objectives', () => {
    for (const parcours of KCA1_PARCOURS) {
      expect(parcours.title.length).toBeGreaterThan(0);
      expect(parcours.subtitle.length).toBeGreaterThan(0);
      expect(parcours.objectives.length).toBeGreaterThan(0);
    }
  });

  it('gives every lesson a body, a duration and a goal', () => {
    for (const lesson of LESSONS) {
      expect(lesson.contentHtml.length).toBeGreaterThan(0);
      expect(lesson.durationMinutes).toBeGreaterThan(0);
      expect(lesson.goal.length).toBeGreaterThan(0);
    }
  });

  it('keys every lesson on its content position, uniquely', () => {
    const keys = LESSONS.map((l) => l.key);

    expect(new Set(keys).size).toBe(keys.length);
    expect(keys[0]).toBe('P0/M1');
  });

  /** A4: the value written must be one the read path accepts. */
  it('writes a content type the read path accepts', () => {
    expect(LESSON_CONTENT_TYPES).toContain(KCA1_CONTENT_TYPE);
  });

  /** Decision 4: per-module duration only, no global total anywhere. */
  it('keeps the range durations readable rather than rounding them away', () => {
    const ranges = LESSONS.filter((l) => l.durationText.includes('-'));

    expect(ranges.map((l) => `${l.key} ${l.durationText}`)).toEqual([
      'P0/M1 25-30 min',
      'P0/M2 30-35 min',
    ]);
    expect(ranges.map((l) => l.durationMinutes)).toEqual([25, 30]);
  });
});

describe('KCA1 generated course - media slots (A3)', () => {
  it('has one slot per marker the document left, eighteen in all', () => {
    expect(SLOTS).toHaveLength(18);
    expect(SLOTS.filter((s) => s.kind === 'VIDEO')).toHaveLength(5);
    expect(SLOTS.filter((s) => s.kind === 'IMAGE')).toHaveLength(7);
    expect(SLOTS.filter((s) => s.kind === 'DOCUMENT')).toHaveLength(6);
  });

  it('spreads them over thirteen lessons', () => {
    expect(LESSONS.filter((l) => l.slots.length > 0)).toHaveLength(13);
  });

  /** Empty until the file exists. The slot is the row; the url arrives later. */
  it('leaves every url null', () => {
    for (const slot of SLOTS) {
      expect(slot.url).toBeNull();
    }
  });

  it('numbers the slots within a lesson from one, without gaps', () => {
    for (const lesson of LESSONS) {
      const positions = lesson.slots.map((s) => s.position);
      expect(positions).toEqual(positions.map((_, i) => i + 1));
    }
  });

  /**
   * A slot that says only its kind sends Visquis back to the document, which is
   * what making them addressable was meant to avoid.
   */
  it('names what each slot is for', () => {
    for (const slot of SLOTS) {
      expect(slot.label.length).toBeGreaterThan(0);
      expect(slot.label).not.toContain('[EMPLACEMENT');
    }
  });

  it('keeps the markers visible in the lesson body as well', () => {
    const visible = LESSONS.filter((l) => l.contentHtml.includes('[EMPLACEMENT'));

    expect(visible).toHaveLength(13);
  });
});

describe('KCA1 generated course - questions', () => {
  it('carries eighty questions, twenty per parcours', () => {
    expect(KCA1_QUESTIONS).toHaveLength(80);
    for (const code of ['P0', 'P1', 'P2', 'P5']) {
      expect(KCA1_QUESTIONS.filter((q) => q.parcours === code)).toHaveLength(20);
    }
  });

  it('gives every question four answers and exactly one correct', () => {
    for (const question of KCA1_QUESTIONS) {
      expect(question.answers).toHaveLength(4);
      expect(question.answers.filter((a) => a.isCorrect)).toHaveLength(1);
    }
    expect(KCA1_QUESTIONS.flatMap((q) => q.answers)).toHaveLength(320);
  });

  it('keeps four distinct answer texts per question', () => {
    for (const question of KCA1_QUESTIONS) {
      expect(new Set(question.answers.map((a) => a.text)).size).toBe(4);
    }
  });
});

/**
 * A2 - the exploit is the SCORE, not the distribution.
 *
 * The source key is degenerate: A 0, B 63, C 16, D 1 over the eighty. A
 * candidate who answers B to everything passes three of the four module quizzes
 * as written. Visquis decided the CSV files stay exactly as he wrote them and
 * the loader redistributes the correct answer across positions when it
 * generates the seed data.
 *
 * So this asserts the consequence rather than the shape. A quiz draws
 * `DEFAULT_QUIZ_QUESTION_COUNT` questions from that parcours' twenty, and the
 * draw is not ordered - so the honest measure is the WORST case: the ten that
 * would suit such a candidate best. If a parcours holds k questions whose
 * correct answer sits at one position, that candidate can score
 * `min(k, 10) / 10`. Asserting an even distribution instead would be asserting
 * a proxy and calling it the thing.
 */
describe('KCA1 generated course - the same-position candidate fails (A2)', () => {
  const byParcours = (code: string) => KCA1_QUESTIONS.filter((q) => q.parcours === code);

  const positionCounts = (code: string): number[] => {
    const counts = [0, 0, 0, 0];
    for (const question of byParcours(code)) {
      counts[question.answers.findIndex((a) => a.isCorrect)] += 1;
    }
    return counts;
  };

  /** What such a candidate scores on the ten questions that suit them best. */
  const bestCaseScore = (count: number): number =>
    Math.round((Math.min(count, DEFAULT_QUIZ_QUESTION_COUNT) / DEFAULT_QUIZ_QUESTION_COUNT) * 100);

  it.each(['P0', 'P1', 'P2', 'P5'])(
    'leaves a same-position candidate below the module threshold on %s',
    (code) => {
      for (const count of positionCounts(code)) {
        expect(bestCaseScore(count)).toBeLessThan(MODULE_PASSING_SCORE);
      }
    },
  );

  it('holds no position above 30 per cent of any parcours', () => {
    for (const code of ['P0', 'P1', 'P2', 'P5']) {
      const counts = positionCounts(code);
      const total = counts.reduce((a, b) => a + b, 0);
      for (const count of counts) {
        expect(count / total).toBeLessThanOrEqual(0.3);
      }
    }
  });

  it('uses every position somewhere in every parcours', () => {
    for (const code of ['P0', 'P1', 'P2', 'P5']) {
      for (const count of positionCounts(code)) {
        expect(count).toBeGreaterThan(0);
      }
    }
  });
});
