
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
export const prismaVersion: PrismaVersion = {
  client: "7.3.0",
  engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  KbsCourse: 'KbsCourse',
  KbsModule: 'KbsModule',
  KbsLesson: 'KbsLesson',
  KbsLessonCompletion: 'KbsLessonCompletion',
  KbsQuestion: 'KbsQuestion',
  KbsAnswer: 'KbsAnswer',
  KbsExamQuestion: 'KbsExamQuestion',
  KbsExamQuestionAnswer: 'KbsExamQuestionAnswer',
  KbsCandidate: 'KbsCandidate',
  KbsCandidateProgress: 'KbsCandidateProgress',
  KbsExam: 'KbsExam',
  KbsExamAnswer: 'KbsExamAnswer',
  KbsExamAnswerSelection: 'KbsExamAnswerSelection',
  KbsSettings: 'KbsSettings',
  KbsCertificate: 'KbsCertificate'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "kbsCourse" | "kbsModule" | "kbsLesson" | "kbsLessonCompletion" | "kbsQuestion" | "kbsAnswer" | "kbsExamQuestion" | "kbsExamQuestionAnswer" | "kbsCandidate" | "kbsCandidateProgress" | "kbsExam" | "kbsExamAnswer" | "kbsExamAnswerSelection" | "kbsSettings" | "kbsCertificate"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    KbsCourse: {
      payload: Prisma.$KbsCoursePayload<ExtArgs>
      fields: Prisma.KbsCourseFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsCourseFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCoursePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsCourseFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCoursePayload>
        }
        findFirst: {
          args: Prisma.KbsCourseFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCoursePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsCourseFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCoursePayload>
        }
        findMany: {
          args: Prisma.KbsCourseFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCoursePayload>[]
        }
        create: {
          args: Prisma.KbsCourseCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCoursePayload>
        }
        createMany: {
          args: Prisma.KbsCourseCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsCourseCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCoursePayload>[]
        }
        delete: {
          args: Prisma.KbsCourseDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCoursePayload>
        }
        update: {
          args: Prisma.KbsCourseUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCoursePayload>
        }
        deleteMany: {
          args: Prisma.KbsCourseDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsCourseUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsCourseUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCoursePayload>[]
        }
        upsert: {
          args: Prisma.KbsCourseUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCoursePayload>
        }
        aggregate: {
          args: Prisma.KbsCourseAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsCourse>
        }
        groupBy: {
          args: Prisma.KbsCourseGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsCourseGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsCourseCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsCourseCountAggregateOutputType> | number
        }
      }
    }
    KbsModule: {
      payload: Prisma.$KbsModulePayload<ExtArgs>
      fields: Prisma.KbsModuleFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsModuleFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsModulePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsModuleFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsModulePayload>
        }
        findFirst: {
          args: Prisma.KbsModuleFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsModulePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsModuleFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsModulePayload>
        }
        findMany: {
          args: Prisma.KbsModuleFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsModulePayload>[]
        }
        create: {
          args: Prisma.KbsModuleCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsModulePayload>
        }
        createMany: {
          args: Prisma.KbsModuleCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsModuleCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsModulePayload>[]
        }
        delete: {
          args: Prisma.KbsModuleDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsModulePayload>
        }
        update: {
          args: Prisma.KbsModuleUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsModulePayload>
        }
        deleteMany: {
          args: Prisma.KbsModuleDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsModuleUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsModuleUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsModulePayload>[]
        }
        upsert: {
          args: Prisma.KbsModuleUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsModulePayload>
        }
        aggregate: {
          args: Prisma.KbsModuleAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsModule>
        }
        groupBy: {
          args: Prisma.KbsModuleGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsModuleGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsModuleCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsModuleCountAggregateOutputType> | number
        }
      }
    }
    KbsLesson: {
      payload: Prisma.$KbsLessonPayload<ExtArgs>
      fields: Prisma.KbsLessonFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsLessonFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsLessonFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonPayload>
        }
        findFirst: {
          args: Prisma.KbsLessonFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsLessonFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonPayload>
        }
        findMany: {
          args: Prisma.KbsLessonFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonPayload>[]
        }
        create: {
          args: Prisma.KbsLessonCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonPayload>
        }
        createMany: {
          args: Prisma.KbsLessonCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsLessonCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonPayload>[]
        }
        delete: {
          args: Prisma.KbsLessonDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonPayload>
        }
        update: {
          args: Prisma.KbsLessonUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonPayload>
        }
        deleteMany: {
          args: Prisma.KbsLessonDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsLessonUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsLessonUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonPayload>[]
        }
        upsert: {
          args: Prisma.KbsLessonUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonPayload>
        }
        aggregate: {
          args: Prisma.KbsLessonAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsLesson>
        }
        groupBy: {
          args: Prisma.KbsLessonGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsLessonGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsLessonCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsLessonCountAggregateOutputType> | number
        }
      }
    }
    KbsLessonCompletion: {
      payload: Prisma.$KbsLessonCompletionPayload<ExtArgs>
      fields: Prisma.KbsLessonCompletionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsLessonCompletionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonCompletionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsLessonCompletionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonCompletionPayload>
        }
        findFirst: {
          args: Prisma.KbsLessonCompletionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonCompletionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsLessonCompletionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonCompletionPayload>
        }
        findMany: {
          args: Prisma.KbsLessonCompletionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonCompletionPayload>[]
        }
        create: {
          args: Prisma.KbsLessonCompletionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonCompletionPayload>
        }
        createMany: {
          args: Prisma.KbsLessonCompletionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsLessonCompletionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonCompletionPayload>[]
        }
        delete: {
          args: Prisma.KbsLessonCompletionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonCompletionPayload>
        }
        update: {
          args: Prisma.KbsLessonCompletionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonCompletionPayload>
        }
        deleteMany: {
          args: Prisma.KbsLessonCompletionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsLessonCompletionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsLessonCompletionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonCompletionPayload>[]
        }
        upsert: {
          args: Prisma.KbsLessonCompletionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsLessonCompletionPayload>
        }
        aggregate: {
          args: Prisma.KbsLessonCompletionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsLessonCompletion>
        }
        groupBy: {
          args: Prisma.KbsLessonCompletionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsLessonCompletionGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsLessonCompletionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsLessonCompletionCountAggregateOutputType> | number
        }
      }
    }
    KbsQuestion: {
      payload: Prisma.$KbsQuestionPayload<ExtArgs>
      fields: Prisma.KbsQuestionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsQuestionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsQuestionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsQuestionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsQuestionPayload>
        }
        findFirst: {
          args: Prisma.KbsQuestionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsQuestionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsQuestionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsQuestionPayload>
        }
        findMany: {
          args: Prisma.KbsQuestionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsQuestionPayload>[]
        }
        create: {
          args: Prisma.KbsQuestionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsQuestionPayload>
        }
        createMany: {
          args: Prisma.KbsQuestionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsQuestionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsQuestionPayload>[]
        }
        delete: {
          args: Prisma.KbsQuestionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsQuestionPayload>
        }
        update: {
          args: Prisma.KbsQuestionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsQuestionPayload>
        }
        deleteMany: {
          args: Prisma.KbsQuestionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsQuestionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsQuestionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsQuestionPayload>[]
        }
        upsert: {
          args: Prisma.KbsQuestionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsQuestionPayload>
        }
        aggregate: {
          args: Prisma.KbsQuestionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsQuestion>
        }
        groupBy: {
          args: Prisma.KbsQuestionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsQuestionGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsQuestionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsQuestionCountAggregateOutputType> | number
        }
      }
    }
    KbsAnswer: {
      payload: Prisma.$KbsAnswerPayload<ExtArgs>
      fields: Prisma.KbsAnswerFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsAnswerFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsAnswerPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsAnswerFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsAnswerPayload>
        }
        findFirst: {
          args: Prisma.KbsAnswerFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsAnswerPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsAnswerFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsAnswerPayload>
        }
        findMany: {
          args: Prisma.KbsAnswerFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsAnswerPayload>[]
        }
        create: {
          args: Prisma.KbsAnswerCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsAnswerPayload>
        }
        createMany: {
          args: Prisma.KbsAnswerCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsAnswerCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsAnswerPayload>[]
        }
        delete: {
          args: Prisma.KbsAnswerDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsAnswerPayload>
        }
        update: {
          args: Prisma.KbsAnswerUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsAnswerPayload>
        }
        deleteMany: {
          args: Prisma.KbsAnswerDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsAnswerUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsAnswerUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsAnswerPayload>[]
        }
        upsert: {
          args: Prisma.KbsAnswerUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsAnswerPayload>
        }
        aggregate: {
          args: Prisma.KbsAnswerAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsAnswer>
        }
        groupBy: {
          args: Prisma.KbsAnswerGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsAnswerGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsAnswerCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsAnswerCountAggregateOutputType> | number
        }
      }
    }
    KbsExamQuestion: {
      payload: Prisma.$KbsExamQuestionPayload<ExtArgs>
      fields: Prisma.KbsExamQuestionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsExamQuestionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsExamQuestionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionPayload>
        }
        findFirst: {
          args: Prisma.KbsExamQuestionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsExamQuestionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionPayload>
        }
        findMany: {
          args: Prisma.KbsExamQuestionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionPayload>[]
        }
        create: {
          args: Prisma.KbsExamQuestionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionPayload>
        }
        createMany: {
          args: Prisma.KbsExamQuestionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsExamQuestionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionPayload>[]
        }
        delete: {
          args: Prisma.KbsExamQuestionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionPayload>
        }
        update: {
          args: Prisma.KbsExamQuestionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionPayload>
        }
        deleteMany: {
          args: Prisma.KbsExamQuestionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsExamQuestionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsExamQuestionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionPayload>[]
        }
        upsert: {
          args: Prisma.KbsExamQuestionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionPayload>
        }
        aggregate: {
          args: Prisma.KbsExamQuestionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsExamQuestion>
        }
        groupBy: {
          args: Prisma.KbsExamQuestionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsExamQuestionGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsExamQuestionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsExamQuestionCountAggregateOutputType> | number
        }
      }
    }
    KbsExamQuestionAnswer: {
      payload: Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>
      fields: Prisma.KbsExamQuestionAnswerFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsExamQuestionAnswerFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionAnswerPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsExamQuestionAnswerFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionAnswerPayload>
        }
        findFirst: {
          args: Prisma.KbsExamQuestionAnswerFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionAnswerPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsExamQuestionAnswerFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionAnswerPayload>
        }
        findMany: {
          args: Prisma.KbsExamQuestionAnswerFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionAnswerPayload>[]
        }
        create: {
          args: Prisma.KbsExamQuestionAnswerCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionAnswerPayload>
        }
        createMany: {
          args: Prisma.KbsExamQuestionAnswerCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsExamQuestionAnswerCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionAnswerPayload>[]
        }
        delete: {
          args: Prisma.KbsExamQuestionAnswerDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionAnswerPayload>
        }
        update: {
          args: Prisma.KbsExamQuestionAnswerUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionAnswerPayload>
        }
        deleteMany: {
          args: Prisma.KbsExamQuestionAnswerDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsExamQuestionAnswerUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsExamQuestionAnswerUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionAnswerPayload>[]
        }
        upsert: {
          args: Prisma.KbsExamQuestionAnswerUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamQuestionAnswerPayload>
        }
        aggregate: {
          args: Prisma.KbsExamQuestionAnswerAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsExamQuestionAnswer>
        }
        groupBy: {
          args: Prisma.KbsExamQuestionAnswerGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsExamQuestionAnswerGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsExamQuestionAnswerCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsExamQuestionAnswerCountAggregateOutputType> | number
        }
      }
    }
    KbsCandidate: {
      payload: Prisma.$KbsCandidatePayload<ExtArgs>
      fields: Prisma.KbsCandidateFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsCandidateFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidatePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsCandidateFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidatePayload>
        }
        findFirst: {
          args: Prisma.KbsCandidateFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidatePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsCandidateFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidatePayload>
        }
        findMany: {
          args: Prisma.KbsCandidateFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidatePayload>[]
        }
        create: {
          args: Prisma.KbsCandidateCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidatePayload>
        }
        createMany: {
          args: Prisma.KbsCandidateCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsCandidateCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidatePayload>[]
        }
        delete: {
          args: Prisma.KbsCandidateDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidatePayload>
        }
        update: {
          args: Prisma.KbsCandidateUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidatePayload>
        }
        deleteMany: {
          args: Prisma.KbsCandidateDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsCandidateUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsCandidateUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidatePayload>[]
        }
        upsert: {
          args: Prisma.KbsCandidateUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidatePayload>
        }
        aggregate: {
          args: Prisma.KbsCandidateAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsCandidate>
        }
        groupBy: {
          args: Prisma.KbsCandidateGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsCandidateGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsCandidateCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsCandidateCountAggregateOutputType> | number
        }
      }
    }
    KbsCandidateProgress: {
      payload: Prisma.$KbsCandidateProgressPayload<ExtArgs>
      fields: Prisma.KbsCandidateProgressFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsCandidateProgressFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidateProgressPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsCandidateProgressFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidateProgressPayload>
        }
        findFirst: {
          args: Prisma.KbsCandidateProgressFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidateProgressPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsCandidateProgressFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidateProgressPayload>
        }
        findMany: {
          args: Prisma.KbsCandidateProgressFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidateProgressPayload>[]
        }
        create: {
          args: Prisma.KbsCandidateProgressCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidateProgressPayload>
        }
        createMany: {
          args: Prisma.KbsCandidateProgressCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsCandidateProgressCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidateProgressPayload>[]
        }
        delete: {
          args: Prisma.KbsCandidateProgressDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidateProgressPayload>
        }
        update: {
          args: Prisma.KbsCandidateProgressUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidateProgressPayload>
        }
        deleteMany: {
          args: Prisma.KbsCandidateProgressDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsCandidateProgressUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsCandidateProgressUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidateProgressPayload>[]
        }
        upsert: {
          args: Prisma.KbsCandidateProgressUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCandidateProgressPayload>
        }
        aggregate: {
          args: Prisma.KbsCandidateProgressAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsCandidateProgress>
        }
        groupBy: {
          args: Prisma.KbsCandidateProgressGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsCandidateProgressGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsCandidateProgressCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsCandidateProgressCountAggregateOutputType> | number
        }
      }
    }
    KbsExam: {
      payload: Prisma.$KbsExamPayload<ExtArgs>
      fields: Prisma.KbsExamFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsExamFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsExamFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamPayload>
        }
        findFirst: {
          args: Prisma.KbsExamFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsExamFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamPayload>
        }
        findMany: {
          args: Prisma.KbsExamFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamPayload>[]
        }
        create: {
          args: Prisma.KbsExamCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamPayload>
        }
        createMany: {
          args: Prisma.KbsExamCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsExamCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamPayload>[]
        }
        delete: {
          args: Prisma.KbsExamDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamPayload>
        }
        update: {
          args: Prisma.KbsExamUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamPayload>
        }
        deleteMany: {
          args: Prisma.KbsExamDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsExamUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsExamUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamPayload>[]
        }
        upsert: {
          args: Prisma.KbsExamUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamPayload>
        }
        aggregate: {
          args: Prisma.KbsExamAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsExam>
        }
        groupBy: {
          args: Prisma.KbsExamGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsExamGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsExamCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsExamCountAggregateOutputType> | number
        }
      }
    }
    KbsExamAnswer: {
      payload: Prisma.$KbsExamAnswerPayload<ExtArgs>
      fields: Prisma.KbsExamAnswerFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsExamAnswerFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsExamAnswerFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerPayload>
        }
        findFirst: {
          args: Prisma.KbsExamAnswerFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsExamAnswerFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerPayload>
        }
        findMany: {
          args: Prisma.KbsExamAnswerFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerPayload>[]
        }
        create: {
          args: Prisma.KbsExamAnswerCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerPayload>
        }
        createMany: {
          args: Prisma.KbsExamAnswerCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsExamAnswerCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerPayload>[]
        }
        delete: {
          args: Prisma.KbsExamAnswerDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerPayload>
        }
        update: {
          args: Prisma.KbsExamAnswerUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerPayload>
        }
        deleteMany: {
          args: Prisma.KbsExamAnswerDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsExamAnswerUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsExamAnswerUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerPayload>[]
        }
        upsert: {
          args: Prisma.KbsExamAnswerUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerPayload>
        }
        aggregate: {
          args: Prisma.KbsExamAnswerAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsExamAnswer>
        }
        groupBy: {
          args: Prisma.KbsExamAnswerGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsExamAnswerGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsExamAnswerCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsExamAnswerCountAggregateOutputType> | number
        }
      }
    }
    KbsExamAnswerSelection: {
      payload: Prisma.$KbsExamAnswerSelectionPayload<ExtArgs>
      fields: Prisma.KbsExamAnswerSelectionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsExamAnswerSelectionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerSelectionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsExamAnswerSelectionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerSelectionPayload>
        }
        findFirst: {
          args: Prisma.KbsExamAnswerSelectionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerSelectionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsExamAnswerSelectionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerSelectionPayload>
        }
        findMany: {
          args: Prisma.KbsExamAnswerSelectionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerSelectionPayload>[]
        }
        create: {
          args: Prisma.KbsExamAnswerSelectionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerSelectionPayload>
        }
        createMany: {
          args: Prisma.KbsExamAnswerSelectionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsExamAnswerSelectionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerSelectionPayload>[]
        }
        delete: {
          args: Prisma.KbsExamAnswerSelectionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerSelectionPayload>
        }
        update: {
          args: Prisma.KbsExamAnswerSelectionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerSelectionPayload>
        }
        deleteMany: {
          args: Prisma.KbsExamAnswerSelectionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsExamAnswerSelectionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsExamAnswerSelectionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerSelectionPayload>[]
        }
        upsert: {
          args: Prisma.KbsExamAnswerSelectionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsExamAnswerSelectionPayload>
        }
        aggregate: {
          args: Prisma.KbsExamAnswerSelectionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsExamAnswerSelection>
        }
        groupBy: {
          args: Prisma.KbsExamAnswerSelectionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsExamAnswerSelectionGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsExamAnswerSelectionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsExamAnswerSelectionCountAggregateOutputType> | number
        }
      }
    }
    KbsSettings: {
      payload: Prisma.$KbsSettingsPayload<ExtArgs>
      fields: Prisma.KbsSettingsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsSettingsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsSettingsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsSettingsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsSettingsPayload>
        }
        findFirst: {
          args: Prisma.KbsSettingsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsSettingsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsSettingsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsSettingsPayload>
        }
        findMany: {
          args: Prisma.KbsSettingsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsSettingsPayload>[]
        }
        create: {
          args: Prisma.KbsSettingsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsSettingsPayload>
        }
        createMany: {
          args: Prisma.KbsSettingsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsSettingsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsSettingsPayload>[]
        }
        delete: {
          args: Prisma.KbsSettingsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsSettingsPayload>
        }
        update: {
          args: Prisma.KbsSettingsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsSettingsPayload>
        }
        deleteMany: {
          args: Prisma.KbsSettingsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsSettingsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsSettingsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsSettingsPayload>[]
        }
        upsert: {
          args: Prisma.KbsSettingsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsSettingsPayload>
        }
        aggregate: {
          args: Prisma.KbsSettingsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsSettings>
        }
        groupBy: {
          args: Prisma.KbsSettingsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsSettingsGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsSettingsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsSettingsCountAggregateOutputType> | number
        }
      }
    }
    KbsCertificate: {
      payload: Prisma.$KbsCertificatePayload<ExtArgs>
      fields: Prisma.KbsCertificateFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KbsCertificateFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCertificatePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KbsCertificateFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCertificatePayload>
        }
        findFirst: {
          args: Prisma.KbsCertificateFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCertificatePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KbsCertificateFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCertificatePayload>
        }
        findMany: {
          args: Prisma.KbsCertificateFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCertificatePayload>[]
        }
        create: {
          args: Prisma.KbsCertificateCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCertificatePayload>
        }
        createMany: {
          args: Prisma.KbsCertificateCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KbsCertificateCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCertificatePayload>[]
        }
        delete: {
          args: Prisma.KbsCertificateDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCertificatePayload>
        }
        update: {
          args: Prisma.KbsCertificateUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCertificatePayload>
        }
        deleteMany: {
          args: Prisma.KbsCertificateDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KbsCertificateUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KbsCertificateUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCertificatePayload>[]
        }
        upsert: {
          args: Prisma.KbsCertificateUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KbsCertificatePayload>
        }
        aggregate: {
          args: Prisma.KbsCertificateAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKbsCertificate>
        }
        groupBy: {
          args: Prisma.KbsCertificateGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsCertificateGroupByOutputType>[]
        }
        count: {
          args: Prisma.KbsCertificateCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KbsCertificateCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const KbsCourseScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  slug: 'slug',
  language: 'language',
  isPublished: 'isPublished',
  duration: 'duration',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KbsCourseScalarFieldEnum = (typeof KbsCourseScalarFieldEnum)[keyof typeof KbsCourseScalarFieldEnum]


export const KbsModuleScalarFieldEnum = {
  id: 'id',
  courseId: 'courseId',
  title: 'title',
  description: 'description',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KbsModuleScalarFieldEnum = (typeof KbsModuleScalarFieldEnum)[keyof typeof KbsModuleScalarFieldEnum]


export const KbsLessonScalarFieldEnum = {
  id: 'id',
  moduleId: 'moduleId',
  title: 'title',
  contentType: 'contentType',
  contentUrl: 'contentUrl',
  duration: 'duration',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KbsLessonScalarFieldEnum = (typeof KbsLessonScalarFieldEnum)[keyof typeof KbsLessonScalarFieldEnum]


export const KbsLessonCompletionScalarFieldEnum = {
  id: 'id',
  candidateId: 'candidateId',
  lessonId: 'lessonId',
  completedAt: 'completedAt'
} as const

export type KbsLessonCompletionScalarFieldEnum = (typeof KbsLessonCompletionScalarFieldEnum)[keyof typeof KbsLessonCompletionScalarFieldEnum]


export const KbsQuestionScalarFieldEnum = {
  id: 'id',
  moduleId: 'moduleId',
  text: 'text',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KbsQuestionScalarFieldEnum = (typeof KbsQuestionScalarFieldEnum)[keyof typeof KbsQuestionScalarFieldEnum]


export const KbsAnswerScalarFieldEnum = {
  id: 'id',
  questionId: 'questionId',
  text: 'text',
  isCorrect: 'isCorrect',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KbsAnswerScalarFieldEnum = (typeof KbsAnswerScalarFieldEnum)[keyof typeof KbsAnswerScalarFieldEnum]


export const KbsExamQuestionScalarFieldEnum = {
  id: 'id',
  moduleId: 'moduleId',
  text: 'text',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KbsExamQuestionScalarFieldEnum = (typeof KbsExamQuestionScalarFieldEnum)[keyof typeof KbsExamQuestionScalarFieldEnum]


export const KbsExamQuestionAnswerScalarFieldEnum = {
  id: 'id',
  questionId: 'questionId',
  text: 'text',
  isCorrect: 'isCorrect',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KbsExamQuestionAnswerScalarFieldEnum = (typeof KbsExamQuestionAnswerScalarFieldEnum)[keyof typeof KbsExamQuestionAnswerScalarFieldEnum]


export const KbsCandidateScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  sponsorCode: 'sponsorCode',
  status: 'status',
  maxAttempts: 'maxAttempts',
  retakeCooldownDays: 'retakeCooldownDays',
  currentCycle: 'currentCycle',
  enrolledAt: 'enrolledAt',
  certifiedAt: 'certifiedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KbsCandidateScalarFieldEnum = (typeof KbsCandidateScalarFieldEnum)[keyof typeof KbsCandidateScalarFieldEnum]


export const KbsCandidateProgressScalarFieldEnum = {
  id: 'id',
  candidateId: 'candidateId',
  moduleId: 'moduleId',
  score: 'score',
  passed: 'passed',
  attempts: 'attempts',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KbsCandidateProgressScalarFieldEnum = (typeof KbsCandidateProgressScalarFieldEnum)[keyof typeof KbsCandidateProgressScalarFieldEnum]


export const KbsExamScalarFieldEnum = {
  id: 'id',
  candidateId: 'candidateId',
  attemptNumber: 'attemptNumber',
  score: 'score',
  passingScore: 'passingScore',
  status: 'status',
  cycle: 'cycle',
  durationMinutes: 'durationMinutes',
  totalQuestions: 'totalQuestions',
  scheduledAt: 'scheduledAt',
  startedAt: 'startedAt',
  submittedAt: 'submittedAt',
  cancelledAt: 'cancelledAt',
  cancelReason: 'cancelReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KbsExamScalarFieldEnum = (typeof KbsExamScalarFieldEnum)[keyof typeof KbsExamScalarFieldEnum]


export const KbsExamAnswerScalarFieldEnum = {
  id: 'id',
  examId: 'examId',
  questionId: 'questionId',
  flagged: 'flagged',
  questionCorrect: 'questionCorrect',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  answeredAt: 'answeredAt'
} as const

export type KbsExamAnswerScalarFieldEnum = (typeof KbsExamAnswerScalarFieldEnum)[keyof typeof KbsExamAnswerScalarFieldEnum]


export const KbsExamAnswerSelectionScalarFieldEnum = {
  id: 'id',
  examAnswerId: 'examAnswerId',
  answerId: 'answerId',
  wasCorrect: 'wasCorrect'
} as const

export type KbsExamAnswerSelectionScalarFieldEnum = (typeof KbsExamAnswerSelectionScalarFieldEnum)[keyof typeof KbsExamAnswerSelectionScalarFieldEnum]


export const KbsSettingsScalarFieldEnum = {
  id: 'id',
  examQuestionCount: 'examQuestionCount',
  quizQuestionCount: 'quizQuestionCount',
  quizMaxAttempts: 'quizMaxAttempts',
  updatedAt: 'updatedAt'
} as const

export type KbsSettingsScalarFieldEnum = (typeof KbsSettingsScalarFieldEnum)[keyof typeof KbsSettingsScalarFieldEnum]


export const KbsCertificateScalarFieldEnum = {
  id: 'id',
  candidateId: 'candidateId',
  kcaNumber: 'kcaNumber',
  issueDate: 'issueDate',
  validUntil: 'validUntil',
  pdfUrl: 'pdfUrl',
  issuedBy: 'issuedBy',
  revokedAt: 'revokedAt',
  revokedBy: 'revokedBy',
  revokeReason: 'revokeReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type KbsCertificateScalarFieldEnum = (typeof KbsCertificateScalarFieldEnum)[keyof typeof KbsCertificateScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  kbsCourse?: Prisma.KbsCourseOmit
  kbsModule?: Prisma.KbsModuleOmit
  kbsLesson?: Prisma.KbsLessonOmit
  kbsLessonCompletion?: Prisma.KbsLessonCompletionOmit
  kbsQuestion?: Prisma.KbsQuestionOmit
  kbsAnswer?: Prisma.KbsAnswerOmit
  kbsExamQuestion?: Prisma.KbsExamQuestionOmit
  kbsExamQuestionAnswer?: Prisma.KbsExamQuestionAnswerOmit
  kbsCandidate?: Prisma.KbsCandidateOmit
  kbsCandidateProgress?: Prisma.KbsCandidateProgressOmit
  kbsExam?: Prisma.KbsExamOmit
  kbsExamAnswer?: Prisma.KbsExamAnswerOmit
  kbsExamAnswerSelection?: Prisma.KbsExamAnswerSelectionOmit
  kbsSettings?: Prisma.KbsSettingsOmit
  kbsCertificate?: Prisma.KbsCertificateOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

