import { readdirSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';

/**
 * G19 - nothing multiplies a price by the surface.
 *
 * `Land.price` was a total to the API and a price per m2 to the web, and six
 * web places multiplied it by `sizeM2`: a 3 400 000 parcel of 480 m2 showed a
 * balance of 1 631 830 000. The total is now `totalPrice`, and the price per m2
 * is `pricePerM2`, generated by the database. Neither needs arithmetic with the
 * surface, so any such product is the defect coming back.
 */
const ROOT = join(__dirname, '..', '..', '..', '..', '..');
const DIRS = ['apps/web/src', 'apps/api/src', 'libs/common/src', 'prisma'];

const walk = (dir: string): string[] =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    if (['node_modules', '__test__'].includes(e.name) || e.name.endsWith('-client')) return [];
    return e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)];
  });

const SOURCES = DIRS.flatMap((d) => walk(join(ROOT, d))).filter(
  (f) => /\.tsx?$/.test(f) && !/\.(spec|dbspec)\.tsx?$/.test(f),
);

const PRICE_TIMES_SURFACE =
  /(price|prix)\w*[^;,\n*]{0,15}\*[^;,\n*]{0,15}sizeM2|sizeM2[^;,\n*]{0,15}\*[^;,\n*]{0,15}(price|prix)/i;

describe('G19 - a price is never multiplied by the surface', () => {
  it('reads the sources', () => {
    expect(SOURCES.length).toBeGreaterThan(300);
  });

  it('finds the shape it bans', () => {
    expect(PRICE_TIMES_SURFACE.test('formatXAF(land.price * land.sizeM2)')).toBe(true);
    expect(PRICE_TIMES_SURFACE.test('(land?.price ?? 0) * (land?.sizeM2 ?? 0)')).toBe(true);
  });

  it('no source does it', () => {
    const found = SOURCES.flatMap((f) =>
      readFileSync(f, 'utf8')
        .split('\n')
        .map((line, i) => [line, i] as const)
        .filter(([line]) => PRICE_TIMES_SURFACE.test(line))
        .map(([line, i]) => `${relative(ROOT, f)}:${i + 1} ${line.trim()}`),
    );
    expect(found).toEqual([]);
  });
});
