
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import type * as Prisma from "./internal/prismaNamespace"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type EnumLandLabelCodesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandLabelCodes | Prisma.EnumLandLabelCodesFieldRefInput<$PrismaModel>
  in?: $Enums.LandLabelCodes[] | Prisma.ListEnumLandLabelCodesFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandLabelCodes[] | Prisma.ListEnumLandLabelCodesFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandLabelCodesFilter<$PrismaModel> | $Enums.LandLabelCodes
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type EnumLandLabelCodesWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandLabelCodes | Prisma.EnumLandLabelCodesFieldRefInput<$PrismaModel>
  in?: $Enums.LandLabelCodes[] | Prisma.ListEnumLandLabelCodesFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandLabelCodes[] | Prisma.ListEnumLandLabelCodesFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandLabelCodesWithAggregatesFilter<$PrismaModel> | $Enums.LandLabelCodes
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLandLabelCodesFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLandLabelCodesFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type FloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type FloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type EnumLandStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.LandStatus | Prisma.EnumLandStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LandStatus[] | Prisma.ListEnumLandStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandStatus[] | Prisma.ListEnumLandStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandStatusFilter<$PrismaModel> | $Enums.LandStatus
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type EnumLandOwnerTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.LandOwnerType | Prisma.EnumLandOwnerTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LandOwnerType[] | Prisma.ListEnumLandOwnerTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandOwnerType[] | Prisma.ListEnumLandOwnerTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandOwnerTypeFilter<$PrismaModel> | $Enums.LandOwnerType
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type FloatNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _min?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _max?: Prisma.NestedFloatNullableFilter<$PrismaModel>
}

export type FloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>
  _min?: Prisma.NestedFloatFilter<$PrismaModel>
  _max?: Prisma.NestedFloatFilter<$PrismaModel>
}

export type EnumLandStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandStatus | Prisma.EnumLandStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LandStatus[] | Prisma.ListEnumLandStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandStatus[] | Prisma.ListEnumLandStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandStatusWithAggregatesFilter<$PrismaModel> | $Enums.LandStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLandStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLandStatusFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type EnumLandOwnerTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandOwnerType | Prisma.EnumLandOwnerTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LandOwnerType[] | Prisma.ListEnumLandOwnerTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandOwnerType[] | Prisma.ListEnumLandOwnerTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandOwnerTypeWithAggregatesFilter<$PrismaModel> | $Enums.LandOwnerType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLandOwnerTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLandOwnerTypeFilter<$PrismaModel>
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type EnumLandMediaTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.LandMediaType | Prisma.EnumLandMediaTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LandMediaType[] | Prisma.ListEnumLandMediaTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandMediaType[] | Prisma.ListEnumLandMediaTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandMediaTypeFilter<$PrismaModel> | $Enums.LandMediaType
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type EnumLandMediaTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandMediaType | Prisma.EnumLandMediaTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LandMediaType[] | Prisma.ListEnumLandMediaTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandMediaType[] | Prisma.ListEnumLandMediaTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandMediaTypeWithAggregatesFilter<$PrismaModel> | $Enums.LandMediaType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLandMediaTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLandMediaTypeFilter<$PrismaModel>
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type EnumLandDocumentTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.LandDocumentType | Prisma.EnumLandDocumentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LandDocumentType[] | Prisma.ListEnumLandDocumentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandDocumentType[] | Prisma.ListEnumLandDocumentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandDocumentTypeFilter<$PrismaModel> | $Enums.LandDocumentType
}

export type EnumLandDocumentTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandDocumentType | Prisma.EnumLandDocumentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LandDocumentType[] | Prisma.ListEnumLandDocumentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandDocumentType[] | Prisma.ListEnumLandDocumentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandDocumentTypeWithAggregatesFilter<$PrismaModel> | $Enums.LandDocumentType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLandDocumentTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLandDocumentTypeFilter<$PrismaModel>
}

export type EnumLandReservationStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.LandReservationStatus | Prisma.EnumLandReservationStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LandReservationStatus[] | Prisma.ListEnumLandReservationStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandReservationStatus[] | Prisma.ListEnumLandReservationStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandReservationStatusFilter<$PrismaModel> | $Enums.LandReservationStatus
}

export type EnumLandReservationStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandReservationStatus | Prisma.EnumLandReservationStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LandReservationStatus[] | Prisma.ListEnumLandReservationStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandReservationStatus[] | Prisma.ListEnumLandReservationStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandReservationStatusWithAggregatesFilter<$PrismaModel> | $Enums.LandReservationStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLandReservationStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLandReservationStatusFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedEnumLandLabelCodesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandLabelCodes | Prisma.EnumLandLabelCodesFieldRefInput<$PrismaModel>
  in?: $Enums.LandLabelCodes[] | Prisma.ListEnumLandLabelCodesFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandLabelCodes[] | Prisma.ListEnumLandLabelCodesFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandLabelCodesFilter<$PrismaModel> | $Enums.LandLabelCodes
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedEnumLandLabelCodesWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandLabelCodes | Prisma.EnumLandLabelCodesFieldRefInput<$PrismaModel>
  in?: $Enums.LandLabelCodes[] | Prisma.ListEnumLandLabelCodesFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandLabelCodes[] | Prisma.ListEnumLandLabelCodesFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandLabelCodesWithAggregatesFilter<$PrismaModel> | $Enums.LandLabelCodes
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLandLabelCodesFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLandLabelCodesFilter<$PrismaModel>
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedEnumLandStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.LandStatus | Prisma.EnumLandStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LandStatus[] | Prisma.ListEnumLandStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandStatus[] | Prisma.ListEnumLandStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandStatusFilter<$PrismaModel> | $Enums.LandStatus
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedEnumLandOwnerTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.LandOwnerType | Prisma.EnumLandOwnerTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LandOwnerType[] | Prisma.ListEnumLandOwnerTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandOwnerType[] | Prisma.ListEnumLandOwnerTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandOwnerTypeFilter<$PrismaModel> | $Enums.LandOwnerType
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedFloatNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _min?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _max?: Prisma.NestedFloatNullableFilter<$PrismaModel>
}

export type NestedFloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>
  _min?: Prisma.NestedFloatFilter<$PrismaModel>
  _max?: Prisma.NestedFloatFilter<$PrismaModel>
}

export type NestedEnumLandStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandStatus | Prisma.EnumLandStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LandStatus[] | Prisma.ListEnumLandStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandStatus[] | Prisma.ListEnumLandStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandStatusWithAggregatesFilter<$PrismaModel> | $Enums.LandStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLandStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLandStatusFilter<$PrismaModel>
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedEnumLandOwnerTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandOwnerType | Prisma.EnumLandOwnerTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LandOwnerType[] | Prisma.ListEnumLandOwnerTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandOwnerType[] | Prisma.ListEnumLandOwnerTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandOwnerTypeWithAggregatesFilter<$PrismaModel> | $Enums.LandOwnerType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLandOwnerTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLandOwnerTypeFilter<$PrismaModel>
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type NestedEnumLandMediaTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.LandMediaType | Prisma.EnumLandMediaTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LandMediaType[] | Prisma.ListEnumLandMediaTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandMediaType[] | Prisma.ListEnumLandMediaTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandMediaTypeFilter<$PrismaModel> | $Enums.LandMediaType
}

export type NestedEnumLandMediaTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandMediaType | Prisma.EnumLandMediaTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LandMediaType[] | Prisma.ListEnumLandMediaTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandMediaType[] | Prisma.ListEnumLandMediaTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandMediaTypeWithAggregatesFilter<$PrismaModel> | $Enums.LandMediaType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLandMediaTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLandMediaTypeFilter<$PrismaModel>
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedEnumLandDocumentTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.LandDocumentType | Prisma.EnumLandDocumentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LandDocumentType[] | Prisma.ListEnumLandDocumentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandDocumentType[] | Prisma.ListEnumLandDocumentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandDocumentTypeFilter<$PrismaModel> | $Enums.LandDocumentType
}

export type NestedEnumLandDocumentTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandDocumentType | Prisma.EnumLandDocumentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LandDocumentType[] | Prisma.ListEnumLandDocumentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandDocumentType[] | Prisma.ListEnumLandDocumentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandDocumentTypeWithAggregatesFilter<$PrismaModel> | $Enums.LandDocumentType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLandDocumentTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLandDocumentTypeFilter<$PrismaModel>
}

export type NestedEnumLandReservationStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.LandReservationStatus | Prisma.EnumLandReservationStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LandReservationStatus[] | Prisma.ListEnumLandReservationStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandReservationStatus[] | Prisma.ListEnumLandReservationStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandReservationStatusFilter<$PrismaModel> | $Enums.LandReservationStatus
}

export type NestedEnumLandReservationStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LandReservationStatus | Prisma.EnumLandReservationStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LandReservationStatus[] | Prisma.ListEnumLandReservationStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.LandReservationStatus[] | Prisma.ListEnumLandReservationStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLandReservationStatusWithAggregatesFilter<$PrismaModel> | $Enums.LandReservationStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLandReservationStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLandReservationStatusFilter<$PrismaModel>
}


