
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `KbsExamQuestionAnswer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model KbsExamQuestionAnswer
 * 
 */
export type KbsExamQuestionAnswerModel = runtime.Types.Result.DefaultSelection<Prisma.$KbsExamQuestionAnswerPayload>

export type AggregateKbsExamQuestionAnswer = {
  _count: KbsExamQuestionAnswerCountAggregateOutputType | null
  _min: KbsExamQuestionAnswerMinAggregateOutputType | null
  _max: KbsExamQuestionAnswerMaxAggregateOutputType | null
}

export type KbsExamQuestionAnswerMinAggregateOutputType = {
  id: string | null
  questionId: string | null
  text: string | null
  isCorrect: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type KbsExamQuestionAnswerMaxAggregateOutputType = {
  id: string | null
  questionId: string | null
  text: string | null
  isCorrect: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type KbsExamQuestionAnswerCountAggregateOutputType = {
  id: number
  questionId: number
  text: number
  isCorrect: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type KbsExamQuestionAnswerMinAggregateInputType = {
  id?: true
  questionId?: true
  text?: true
  isCorrect?: true
  createdAt?: true
  updatedAt?: true
}

export type KbsExamQuestionAnswerMaxAggregateInputType = {
  id?: true
  questionId?: true
  text?: true
  isCorrect?: true
  createdAt?: true
  updatedAt?: true
}

export type KbsExamQuestionAnswerCountAggregateInputType = {
  id?: true
  questionId?: true
  text?: true
  isCorrect?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type KbsExamQuestionAnswerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KbsExamQuestionAnswer to aggregate.
   */
  where?: Prisma.KbsExamQuestionAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsExamQuestionAnswers to fetch.
   */
  orderBy?: Prisma.KbsExamQuestionAnswerOrderByWithRelationInput | Prisma.KbsExamQuestionAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KbsExamQuestionAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsExamQuestionAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsExamQuestionAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KbsExamQuestionAnswers
  **/
  _count?: true | KbsExamQuestionAnswerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KbsExamQuestionAnswerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KbsExamQuestionAnswerMaxAggregateInputType
}

export type GetKbsExamQuestionAnswerAggregateType<T extends KbsExamQuestionAnswerAggregateArgs> = {
      [P in keyof T & keyof AggregateKbsExamQuestionAnswer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKbsExamQuestionAnswer[P]>
    : Prisma.GetScalarType<T[P], AggregateKbsExamQuestionAnswer[P]>
}




export type KbsExamQuestionAnswerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KbsExamQuestionAnswerWhereInput
  orderBy?: Prisma.KbsExamQuestionAnswerOrderByWithAggregationInput | Prisma.KbsExamQuestionAnswerOrderByWithAggregationInput[]
  by: Prisma.KbsExamQuestionAnswerScalarFieldEnum[] | Prisma.KbsExamQuestionAnswerScalarFieldEnum
  having?: Prisma.KbsExamQuestionAnswerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KbsExamQuestionAnswerCountAggregateInputType | true
  _min?: KbsExamQuestionAnswerMinAggregateInputType
  _max?: KbsExamQuestionAnswerMaxAggregateInputType
}

export type KbsExamQuestionAnswerGroupByOutputType = {
  id: string
  questionId: string
  text: string
  isCorrect: boolean
  createdAt: Date
  updatedAt: Date
  _count: KbsExamQuestionAnswerCountAggregateOutputType | null
  _min: KbsExamQuestionAnswerMinAggregateOutputType | null
  _max: KbsExamQuestionAnswerMaxAggregateOutputType | null
}

type GetKbsExamQuestionAnswerGroupByPayload<T extends KbsExamQuestionAnswerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KbsExamQuestionAnswerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KbsExamQuestionAnswerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KbsExamQuestionAnswerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KbsExamQuestionAnswerGroupByOutputType[P]>
      }
    >
  >



export type KbsExamQuestionAnswerWhereInput = {
  AND?: Prisma.KbsExamQuestionAnswerWhereInput | Prisma.KbsExamQuestionAnswerWhereInput[]
  OR?: Prisma.KbsExamQuestionAnswerWhereInput[]
  NOT?: Prisma.KbsExamQuestionAnswerWhereInput | Prisma.KbsExamQuestionAnswerWhereInput[]
  id?: Prisma.StringFilter<"KbsExamQuestionAnswer"> | string
  questionId?: Prisma.StringFilter<"KbsExamQuestionAnswer"> | string
  text?: Prisma.StringFilter<"KbsExamQuestionAnswer"> | string
  isCorrect?: Prisma.BoolFilter<"KbsExamQuestionAnswer"> | boolean
  createdAt?: Prisma.DateTimeFilter<"KbsExamQuestionAnswer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KbsExamQuestionAnswer"> | Date | string
  question?: Prisma.XOR<Prisma.KbsExamQuestionScalarRelationFilter, Prisma.KbsExamQuestionWhereInput>
  selections?: Prisma.KbsExamAnswerSelectionListRelationFilter
}

export type KbsExamQuestionAnswerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  question?: Prisma.KbsExamQuestionOrderByWithRelationInput
  selections?: Prisma.KbsExamAnswerSelectionOrderByRelationAggregateInput
}

export type KbsExamQuestionAnswerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.KbsExamQuestionAnswerWhereInput | Prisma.KbsExamQuestionAnswerWhereInput[]
  OR?: Prisma.KbsExamQuestionAnswerWhereInput[]
  NOT?: Prisma.KbsExamQuestionAnswerWhereInput | Prisma.KbsExamQuestionAnswerWhereInput[]
  questionId?: Prisma.StringFilter<"KbsExamQuestionAnswer"> | string
  text?: Prisma.StringFilter<"KbsExamQuestionAnswer"> | string
  isCorrect?: Prisma.BoolFilter<"KbsExamQuestionAnswer"> | boolean
  createdAt?: Prisma.DateTimeFilter<"KbsExamQuestionAnswer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KbsExamQuestionAnswer"> | Date | string
  question?: Prisma.XOR<Prisma.KbsExamQuestionScalarRelationFilter, Prisma.KbsExamQuestionWhereInput>
  selections?: Prisma.KbsExamAnswerSelectionListRelationFilter
}, "id">

export type KbsExamQuestionAnswerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.KbsExamQuestionAnswerCountOrderByAggregateInput
  _max?: Prisma.KbsExamQuestionAnswerMaxOrderByAggregateInput
  _min?: Prisma.KbsExamQuestionAnswerMinOrderByAggregateInput
}

export type KbsExamQuestionAnswerScalarWhereWithAggregatesInput = {
  AND?: Prisma.KbsExamQuestionAnswerScalarWhereWithAggregatesInput | Prisma.KbsExamQuestionAnswerScalarWhereWithAggregatesInput[]
  OR?: Prisma.KbsExamQuestionAnswerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KbsExamQuestionAnswerScalarWhereWithAggregatesInput | Prisma.KbsExamQuestionAnswerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"KbsExamQuestionAnswer"> | string
  questionId?: Prisma.StringWithAggregatesFilter<"KbsExamQuestionAnswer"> | string
  text?: Prisma.StringWithAggregatesFilter<"KbsExamQuestionAnswer"> | string
  isCorrect?: Prisma.BoolWithAggregatesFilter<"KbsExamQuestionAnswer"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"KbsExamQuestionAnswer"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"KbsExamQuestionAnswer"> | Date | string
}

export type KbsExamQuestionAnswerCreateInput = {
  id?: string
  text: string
  isCorrect: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  question: Prisma.KbsExamQuestionCreateNestedOneWithoutAnswersInput
  selections?: Prisma.KbsExamAnswerSelectionCreateNestedManyWithoutAnswerInput
}

export type KbsExamQuestionAnswerUncheckedCreateInput = {
  id?: string
  questionId: string
  text: string
  isCorrect: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  selections?: Prisma.KbsExamAnswerSelectionUncheckedCreateNestedManyWithoutAnswerInput
}

export type KbsExamQuestionAnswerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  question?: Prisma.KbsExamQuestionUpdateOneRequiredWithoutAnswersNestedInput
  selections?: Prisma.KbsExamAnswerSelectionUpdateManyWithoutAnswerNestedInput
}

export type KbsExamQuestionAnswerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  selections?: Prisma.KbsExamAnswerSelectionUncheckedUpdateManyWithoutAnswerNestedInput
}

export type KbsExamQuestionAnswerCreateManyInput = {
  id?: string
  questionId: string
  text: string
  isCorrect: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KbsExamQuestionAnswerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsExamQuestionAnswerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsExamQuestionAnswerListRelationFilter = {
  every?: Prisma.KbsExamQuestionAnswerWhereInput
  some?: Prisma.KbsExamQuestionAnswerWhereInput
  none?: Prisma.KbsExamQuestionAnswerWhereInput
}

export type KbsExamQuestionAnswerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type KbsExamQuestionAnswerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KbsExamQuestionAnswerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KbsExamQuestionAnswerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KbsExamQuestionAnswerScalarRelationFilter = {
  is?: Prisma.KbsExamQuestionAnswerWhereInput
  isNot?: Prisma.KbsExamQuestionAnswerWhereInput
}

export type KbsExamQuestionAnswerCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionAnswerCreateWithoutQuestionInput, Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutQuestionInput> | Prisma.KbsExamQuestionAnswerCreateWithoutQuestionInput[] | Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.KbsExamQuestionAnswerCreateOrConnectWithoutQuestionInput | Prisma.KbsExamQuestionAnswerCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.KbsExamQuestionAnswerCreateManyQuestionInputEnvelope
  connect?: Prisma.KbsExamQuestionAnswerWhereUniqueInput | Prisma.KbsExamQuestionAnswerWhereUniqueInput[]
}

export type KbsExamQuestionAnswerUncheckedCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionAnswerCreateWithoutQuestionInput, Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutQuestionInput> | Prisma.KbsExamQuestionAnswerCreateWithoutQuestionInput[] | Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.KbsExamQuestionAnswerCreateOrConnectWithoutQuestionInput | Prisma.KbsExamQuestionAnswerCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.KbsExamQuestionAnswerCreateManyQuestionInputEnvelope
  connect?: Prisma.KbsExamQuestionAnswerWhereUniqueInput | Prisma.KbsExamQuestionAnswerWhereUniqueInput[]
}

export type KbsExamQuestionAnswerUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionAnswerCreateWithoutQuestionInput, Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutQuestionInput> | Prisma.KbsExamQuestionAnswerCreateWithoutQuestionInput[] | Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.KbsExamQuestionAnswerCreateOrConnectWithoutQuestionInput | Prisma.KbsExamQuestionAnswerCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.KbsExamQuestionAnswerUpsertWithWhereUniqueWithoutQuestionInput | Prisma.KbsExamQuestionAnswerUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.KbsExamQuestionAnswerCreateManyQuestionInputEnvelope
  set?: Prisma.KbsExamQuestionAnswerWhereUniqueInput | Prisma.KbsExamQuestionAnswerWhereUniqueInput[]
  disconnect?: Prisma.KbsExamQuestionAnswerWhereUniqueInput | Prisma.KbsExamQuestionAnswerWhereUniqueInput[]
  delete?: Prisma.KbsExamQuestionAnswerWhereUniqueInput | Prisma.KbsExamQuestionAnswerWhereUniqueInput[]
  connect?: Prisma.KbsExamQuestionAnswerWhereUniqueInput | Prisma.KbsExamQuestionAnswerWhereUniqueInput[]
  update?: Prisma.KbsExamQuestionAnswerUpdateWithWhereUniqueWithoutQuestionInput | Prisma.KbsExamQuestionAnswerUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.KbsExamQuestionAnswerUpdateManyWithWhereWithoutQuestionInput | Prisma.KbsExamQuestionAnswerUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.KbsExamQuestionAnswerScalarWhereInput | Prisma.KbsExamQuestionAnswerScalarWhereInput[]
}

export type KbsExamQuestionAnswerUncheckedUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionAnswerCreateWithoutQuestionInput, Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutQuestionInput> | Prisma.KbsExamQuestionAnswerCreateWithoutQuestionInput[] | Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.KbsExamQuestionAnswerCreateOrConnectWithoutQuestionInput | Prisma.KbsExamQuestionAnswerCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.KbsExamQuestionAnswerUpsertWithWhereUniqueWithoutQuestionInput | Prisma.KbsExamQuestionAnswerUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.KbsExamQuestionAnswerCreateManyQuestionInputEnvelope
  set?: Prisma.KbsExamQuestionAnswerWhereUniqueInput | Prisma.KbsExamQuestionAnswerWhereUniqueInput[]
  disconnect?: Prisma.KbsExamQuestionAnswerWhereUniqueInput | Prisma.KbsExamQuestionAnswerWhereUniqueInput[]
  delete?: Prisma.KbsExamQuestionAnswerWhereUniqueInput | Prisma.KbsExamQuestionAnswerWhereUniqueInput[]
  connect?: Prisma.KbsExamQuestionAnswerWhereUniqueInput | Prisma.KbsExamQuestionAnswerWhereUniqueInput[]
  update?: Prisma.KbsExamQuestionAnswerUpdateWithWhereUniqueWithoutQuestionInput | Prisma.KbsExamQuestionAnswerUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.KbsExamQuestionAnswerUpdateManyWithWhereWithoutQuestionInput | Prisma.KbsExamQuestionAnswerUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.KbsExamQuestionAnswerScalarWhereInput | Prisma.KbsExamQuestionAnswerScalarWhereInput[]
}

export type KbsExamQuestionAnswerCreateNestedOneWithoutSelectionsInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionAnswerCreateWithoutSelectionsInput, Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutSelectionsInput>
  connectOrCreate?: Prisma.KbsExamQuestionAnswerCreateOrConnectWithoutSelectionsInput
  connect?: Prisma.KbsExamQuestionAnswerWhereUniqueInput
}

export type KbsExamQuestionAnswerUpdateOneRequiredWithoutSelectionsNestedInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionAnswerCreateWithoutSelectionsInput, Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutSelectionsInput>
  connectOrCreate?: Prisma.KbsExamQuestionAnswerCreateOrConnectWithoutSelectionsInput
  upsert?: Prisma.KbsExamQuestionAnswerUpsertWithoutSelectionsInput
  connect?: Prisma.KbsExamQuestionAnswerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.KbsExamQuestionAnswerUpdateToOneWithWhereWithoutSelectionsInput, Prisma.KbsExamQuestionAnswerUpdateWithoutSelectionsInput>, Prisma.KbsExamQuestionAnswerUncheckedUpdateWithoutSelectionsInput>
}

export type KbsExamQuestionAnswerCreateWithoutQuestionInput = {
  id?: string
  text: string
  isCorrect: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  selections?: Prisma.KbsExamAnswerSelectionCreateNestedManyWithoutAnswerInput
}

export type KbsExamQuestionAnswerUncheckedCreateWithoutQuestionInput = {
  id?: string
  text: string
  isCorrect: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  selections?: Prisma.KbsExamAnswerSelectionUncheckedCreateNestedManyWithoutAnswerInput
}

export type KbsExamQuestionAnswerCreateOrConnectWithoutQuestionInput = {
  where: Prisma.KbsExamQuestionAnswerWhereUniqueInput
  create: Prisma.XOR<Prisma.KbsExamQuestionAnswerCreateWithoutQuestionInput, Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutQuestionInput>
}

export type KbsExamQuestionAnswerCreateManyQuestionInputEnvelope = {
  data: Prisma.KbsExamQuestionAnswerCreateManyQuestionInput | Prisma.KbsExamQuestionAnswerCreateManyQuestionInput[]
  skipDuplicates?: boolean
}

export type KbsExamQuestionAnswerUpsertWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.KbsExamQuestionAnswerWhereUniqueInput
  update: Prisma.XOR<Prisma.KbsExamQuestionAnswerUpdateWithoutQuestionInput, Prisma.KbsExamQuestionAnswerUncheckedUpdateWithoutQuestionInput>
  create: Prisma.XOR<Prisma.KbsExamQuestionAnswerCreateWithoutQuestionInput, Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutQuestionInput>
}

export type KbsExamQuestionAnswerUpdateWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.KbsExamQuestionAnswerWhereUniqueInput
  data: Prisma.XOR<Prisma.KbsExamQuestionAnswerUpdateWithoutQuestionInput, Prisma.KbsExamQuestionAnswerUncheckedUpdateWithoutQuestionInput>
}

export type KbsExamQuestionAnswerUpdateManyWithWhereWithoutQuestionInput = {
  where: Prisma.KbsExamQuestionAnswerScalarWhereInput
  data: Prisma.XOR<Prisma.KbsExamQuestionAnswerUpdateManyMutationInput, Prisma.KbsExamQuestionAnswerUncheckedUpdateManyWithoutQuestionInput>
}

export type KbsExamQuestionAnswerScalarWhereInput = {
  AND?: Prisma.KbsExamQuestionAnswerScalarWhereInput | Prisma.KbsExamQuestionAnswerScalarWhereInput[]
  OR?: Prisma.KbsExamQuestionAnswerScalarWhereInput[]
  NOT?: Prisma.KbsExamQuestionAnswerScalarWhereInput | Prisma.KbsExamQuestionAnswerScalarWhereInput[]
  id?: Prisma.StringFilter<"KbsExamQuestionAnswer"> | string
  questionId?: Prisma.StringFilter<"KbsExamQuestionAnswer"> | string
  text?: Prisma.StringFilter<"KbsExamQuestionAnswer"> | string
  isCorrect?: Prisma.BoolFilter<"KbsExamQuestionAnswer"> | boolean
  createdAt?: Prisma.DateTimeFilter<"KbsExamQuestionAnswer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KbsExamQuestionAnswer"> | Date | string
}

export type KbsExamQuestionAnswerCreateWithoutSelectionsInput = {
  id?: string
  text: string
  isCorrect: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  question: Prisma.KbsExamQuestionCreateNestedOneWithoutAnswersInput
}

export type KbsExamQuestionAnswerUncheckedCreateWithoutSelectionsInput = {
  id?: string
  questionId: string
  text: string
  isCorrect: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KbsExamQuestionAnswerCreateOrConnectWithoutSelectionsInput = {
  where: Prisma.KbsExamQuestionAnswerWhereUniqueInput
  create: Prisma.XOR<Prisma.KbsExamQuestionAnswerCreateWithoutSelectionsInput, Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutSelectionsInput>
}

export type KbsExamQuestionAnswerUpsertWithoutSelectionsInput = {
  update: Prisma.XOR<Prisma.KbsExamQuestionAnswerUpdateWithoutSelectionsInput, Prisma.KbsExamQuestionAnswerUncheckedUpdateWithoutSelectionsInput>
  create: Prisma.XOR<Prisma.KbsExamQuestionAnswerCreateWithoutSelectionsInput, Prisma.KbsExamQuestionAnswerUncheckedCreateWithoutSelectionsInput>
  where?: Prisma.KbsExamQuestionAnswerWhereInput
}

export type KbsExamQuestionAnswerUpdateToOneWithWhereWithoutSelectionsInput = {
  where?: Prisma.KbsExamQuestionAnswerWhereInput
  data: Prisma.XOR<Prisma.KbsExamQuestionAnswerUpdateWithoutSelectionsInput, Prisma.KbsExamQuestionAnswerUncheckedUpdateWithoutSelectionsInput>
}

export type KbsExamQuestionAnswerUpdateWithoutSelectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  question?: Prisma.KbsExamQuestionUpdateOneRequiredWithoutAnswersNestedInput
}

export type KbsExamQuestionAnswerUncheckedUpdateWithoutSelectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsExamQuestionAnswerCreateManyQuestionInput = {
  id?: string
  text: string
  isCorrect: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KbsExamQuestionAnswerUpdateWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  selections?: Prisma.KbsExamAnswerSelectionUpdateManyWithoutAnswerNestedInput
}

export type KbsExamQuestionAnswerUncheckedUpdateWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  selections?: Prisma.KbsExamAnswerSelectionUncheckedUpdateManyWithoutAnswerNestedInput
}

export type KbsExamQuestionAnswerUncheckedUpdateManyWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  isCorrect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type KbsExamQuestionAnswerCountOutputType
 */

export type KbsExamQuestionAnswerCountOutputType = {
  selections: number
}

export type KbsExamQuestionAnswerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  selections?: boolean | KbsExamQuestionAnswerCountOutputTypeCountSelectionsArgs
}

/**
 * KbsExamQuestionAnswerCountOutputType without action
 */
export type KbsExamQuestionAnswerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswerCountOutputType
   */
  select?: Prisma.KbsExamQuestionAnswerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * KbsExamQuestionAnswerCountOutputType without action
 */
export type KbsExamQuestionAnswerCountOutputTypeCountSelectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KbsExamAnswerSelectionWhereInput
}


export type KbsExamQuestionAnswerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionId?: boolean
  text?: boolean
  isCorrect?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  question?: boolean | Prisma.KbsExamQuestionDefaultArgs<ExtArgs>
  selections?: boolean | Prisma.KbsExamQuestionAnswer$selectionsArgs<ExtArgs>
  _count?: boolean | Prisma.KbsExamQuestionAnswerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kbsExamQuestionAnswer"]>

export type KbsExamQuestionAnswerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionId?: boolean
  text?: boolean
  isCorrect?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  question?: boolean | Prisma.KbsExamQuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kbsExamQuestionAnswer"]>

export type KbsExamQuestionAnswerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionId?: boolean
  text?: boolean
  isCorrect?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  question?: boolean | Prisma.KbsExamQuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kbsExamQuestionAnswer"]>

export type KbsExamQuestionAnswerSelectScalar = {
  id?: boolean
  questionId?: boolean
  text?: boolean
  isCorrect?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type KbsExamQuestionAnswerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "questionId" | "text" | "isCorrect" | "createdAt" | "updatedAt", ExtArgs["result"]["kbsExamQuestionAnswer"]>
export type KbsExamQuestionAnswerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  question?: boolean | Prisma.KbsExamQuestionDefaultArgs<ExtArgs>
  selections?: boolean | Prisma.KbsExamQuestionAnswer$selectionsArgs<ExtArgs>
  _count?: boolean | Prisma.KbsExamQuestionAnswerCountOutputTypeDefaultArgs<ExtArgs>
}
export type KbsExamQuestionAnswerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  question?: boolean | Prisma.KbsExamQuestionDefaultArgs<ExtArgs>
}
export type KbsExamQuestionAnswerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  question?: boolean | Prisma.KbsExamQuestionDefaultArgs<ExtArgs>
}

export type $KbsExamQuestionAnswerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KbsExamQuestionAnswer"
  objects: {
    question: Prisma.$KbsExamQuestionPayload<ExtArgs>
    selections: Prisma.$KbsExamAnswerSelectionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    questionId: string
    text: string
    isCorrect: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["kbsExamQuestionAnswer"]>
  composites: {}
}

export type KbsExamQuestionAnswerGetPayload<S extends boolean | null | undefined | KbsExamQuestionAnswerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload, S>

export type KbsExamQuestionAnswerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KbsExamQuestionAnswerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KbsExamQuestionAnswerCountAggregateInputType | true
  }

export interface KbsExamQuestionAnswerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KbsExamQuestionAnswer'], meta: { name: 'KbsExamQuestionAnswer' } }
  /**
   * Find zero or one KbsExamQuestionAnswer that matches the filter.
   * @param {KbsExamQuestionAnswerFindUniqueArgs} args - Arguments to find a KbsExamQuestionAnswer
   * @example
   * // Get one KbsExamQuestionAnswer
   * const kbsExamQuestionAnswer = await prisma.kbsExamQuestionAnswer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KbsExamQuestionAnswerFindUniqueArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionAnswerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KbsExamQuestionAnswer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KbsExamQuestionAnswerFindUniqueOrThrowArgs} args - Arguments to find a KbsExamQuestionAnswer
   * @example
   * // Get one KbsExamQuestionAnswer
   * const kbsExamQuestionAnswer = await prisma.kbsExamQuestionAnswer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KbsExamQuestionAnswerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionAnswerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KbsExamQuestionAnswer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionAnswerFindFirstArgs} args - Arguments to find a KbsExamQuestionAnswer
   * @example
   * // Get one KbsExamQuestionAnswer
   * const kbsExamQuestionAnswer = await prisma.kbsExamQuestionAnswer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KbsExamQuestionAnswerFindFirstArgs>(args?: Prisma.SelectSubset<T, KbsExamQuestionAnswerFindFirstArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KbsExamQuestionAnswer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionAnswerFindFirstOrThrowArgs} args - Arguments to find a KbsExamQuestionAnswer
   * @example
   * // Get one KbsExamQuestionAnswer
   * const kbsExamQuestionAnswer = await prisma.kbsExamQuestionAnswer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KbsExamQuestionAnswerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KbsExamQuestionAnswerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KbsExamQuestionAnswers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionAnswerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KbsExamQuestionAnswers
   * const kbsExamQuestionAnswers = await prisma.kbsExamQuestionAnswer.findMany()
   * 
   * // Get first 10 KbsExamQuestionAnswers
   * const kbsExamQuestionAnswers = await prisma.kbsExamQuestionAnswer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kbsExamQuestionAnswerWithIdOnly = await prisma.kbsExamQuestionAnswer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KbsExamQuestionAnswerFindManyArgs>(args?: Prisma.SelectSubset<T, KbsExamQuestionAnswerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a KbsExamQuestionAnswer.
   * @param {KbsExamQuestionAnswerCreateArgs} args - Arguments to create a KbsExamQuestionAnswer.
   * @example
   * // Create one KbsExamQuestionAnswer
   * const KbsExamQuestionAnswer = await prisma.kbsExamQuestionAnswer.create({
   *   data: {
   *     // ... data to create a KbsExamQuestionAnswer
   *   }
   * })
   * 
   */
  create<T extends KbsExamQuestionAnswerCreateArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionAnswerCreateArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many KbsExamQuestionAnswers.
   * @param {KbsExamQuestionAnswerCreateManyArgs} args - Arguments to create many KbsExamQuestionAnswers.
   * @example
   * // Create many KbsExamQuestionAnswers
   * const kbsExamQuestionAnswer = await prisma.kbsExamQuestionAnswer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KbsExamQuestionAnswerCreateManyArgs>(args?: Prisma.SelectSubset<T, KbsExamQuestionAnswerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many KbsExamQuestionAnswers and returns the data saved in the database.
   * @param {KbsExamQuestionAnswerCreateManyAndReturnArgs} args - Arguments to create many KbsExamQuestionAnswers.
   * @example
   * // Create many KbsExamQuestionAnswers
   * const kbsExamQuestionAnswer = await prisma.kbsExamQuestionAnswer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many KbsExamQuestionAnswers and only return the `id`
   * const kbsExamQuestionAnswerWithIdOnly = await prisma.kbsExamQuestionAnswer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KbsExamQuestionAnswerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KbsExamQuestionAnswerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a KbsExamQuestionAnswer.
   * @param {KbsExamQuestionAnswerDeleteArgs} args - Arguments to delete one KbsExamQuestionAnswer.
   * @example
   * // Delete one KbsExamQuestionAnswer
   * const KbsExamQuestionAnswer = await prisma.kbsExamQuestionAnswer.delete({
   *   where: {
   *     // ... filter to delete one KbsExamQuestionAnswer
   *   }
   * })
   * 
   */
  delete<T extends KbsExamQuestionAnswerDeleteArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionAnswerDeleteArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KbsExamQuestionAnswer.
   * @param {KbsExamQuestionAnswerUpdateArgs} args - Arguments to update one KbsExamQuestionAnswer.
   * @example
   * // Update one KbsExamQuestionAnswer
   * const kbsExamQuestionAnswer = await prisma.kbsExamQuestionAnswer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KbsExamQuestionAnswerUpdateArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionAnswerUpdateArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KbsExamQuestionAnswers.
   * @param {KbsExamQuestionAnswerDeleteManyArgs} args - Arguments to filter KbsExamQuestionAnswers to delete.
   * @example
   * // Delete a few KbsExamQuestionAnswers
   * const { count } = await prisma.kbsExamQuestionAnswer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KbsExamQuestionAnswerDeleteManyArgs>(args?: Prisma.SelectSubset<T, KbsExamQuestionAnswerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KbsExamQuestionAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionAnswerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KbsExamQuestionAnswers
   * const kbsExamQuestionAnswer = await prisma.kbsExamQuestionAnswer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KbsExamQuestionAnswerUpdateManyArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionAnswerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KbsExamQuestionAnswers and returns the data updated in the database.
   * @param {KbsExamQuestionAnswerUpdateManyAndReturnArgs} args - Arguments to update many KbsExamQuestionAnswers.
   * @example
   * // Update many KbsExamQuestionAnswers
   * const kbsExamQuestionAnswer = await prisma.kbsExamQuestionAnswer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more KbsExamQuestionAnswers and only return the `id`
   * const kbsExamQuestionAnswerWithIdOnly = await prisma.kbsExamQuestionAnswer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KbsExamQuestionAnswerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionAnswerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one KbsExamQuestionAnswer.
   * @param {KbsExamQuestionAnswerUpsertArgs} args - Arguments to update or create a KbsExamQuestionAnswer.
   * @example
   * // Update or create a KbsExamQuestionAnswer
   * const kbsExamQuestionAnswer = await prisma.kbsExamQuestionAnswer.upsert({
   *   create: {
   *     // ... data to create a KbsExamQuestionAnswer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the KbsExamQuestionAnswer we want to update
   *   }
   * })
   */
  upsert<T extends KbsExamQuestionAnswerUpsertArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionAnswerUpsertArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionAnswerClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of KbsExamQuestionAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionAnswerCountArgs} args - Arguments to filter KbsExamQuestionAnswers to count.
   * @example
   * // Count the number of KbsExamQuestionAnswers
   * const count = await prisma.kbsExamQuestionAnswer.count({
   *   where: {
   *     // ... the filter for the KbsExamQuestionAnswers we want to count
   *   }
   * })
  **/
  count<T extends KbsExamQuestionAnswerCountArgs>(
    args?: Prisma.Subset<T, KbsExamQuestionAnswerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KbsExamQuestionAnswerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KbsExamQuestionAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionAnswerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KbsExamQuestionAnswerAggregateArgs>(args: Prisma.Subset<T, KbsExamQuestionAnswerAggregateArgs>): Prisma.PrismaPromise<GetKbsExamQuestionAnswerAggregateType<T>>

  /**
   * Group by KbsExamQuestionAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionAnswerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KbsExamQuestionAnswerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KbsExamQuestionAnswerGroupByArgs['orderBy'] }
      : { orderBy?: KbsExamQuestionAnswerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KbsExamQuestionAnswerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKbsExamQuestionAnswerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KbsExamQuestionAnswer model
 */
readonly fields: KbsExamQuestionAnswerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KbsExamQuestionAnswer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KbsExamQuestionAnswerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  question<T extends Prisma.KbsExamQuestionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KbsExamQuestionDefaultArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  selections<T extends Prisma.KbsExamQuestionAnswer$selectionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KbsExamQuestionAnswer$selectionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsExamAnswerSelectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KbsExamQuestionAnswer model
 */
export interface KbsExamQuestionAnswerFieldRefs {
  readonly id: Prisma.FieldRef<"KbsExamQuestionAnswer", 'String'>
  readonly questionId: Prisma.FieldRef<"KbsExamQuestionAnswer", 'String'>
  readonly text: Prisma.FieldRef<"KbsExamQuestionAnswer", 'String'>
  readonly isCorrect: Prisma.FieldRef<"KbsExamQuestionAnswer", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"KbsExamQuestionAnswer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"KbsExamQuestionAnswer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * KbsExamQuestionAnswer findUnique
 */
export type KbsExamQuestionAnswerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerInclude<ExtArgs> | null
  /**
   * Filter, which KbsExamQuestionAnswer to fetch.
   */
  where: Prisma.KbsExamQuestionAnswerWhereUniqueInput
}

/**
 * KbsExamQuestionAnswer findUniqueOrThrow
 */
export type KbsExamQuestionAnswerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerInclude<ExtArgs> | null
  /**
   * Filter, which KbsExamQuestionAnswer to fetch.
   */
  where: Prisma.KbsExamQuestionAnswerWhereUniqueInput
}

/**
 * KbsExamQuestionAnswer findFirst
 */
export type KbsExamQuestionAnswerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerInclude<ExtArgs> | null
  /**
   * Filter, which KbsExamQuestionAnswer to fetch.
   */
  where?: Prisma.KbsExamQuestionAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsExamQuestionAnswers to fetch.
   */
  orderBy?: Prisma.KbsExamQuestionAnswerOrderByWithRelationInput | Prisma.KbsExamQuestionAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KbsExamQuestionAnswers.
   */
  cursor?: Prisma.KbsExamQuestionAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsExamQuestionAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsExamQuestionAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KbsExamQuestionAnswers.
   */
  distinct?: Prisma.KbsExamQuestionAnswerScalarFieldEnum | Prisma.KbsExamQuestionAnswerScalarFieldEnum[]
}

/**
 * KbsExamQuestionAnswer findFirstOrThrow
 */
export type KbsExamQuestionAnswerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerInclude<ExtArgs> | null
  /**
   * Filter, which KbsExamQuestionAnswer to fetch.
   */
  where?: Prisma.KbsExamQuestionAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsExamQuestionAnswers to fetch.
   */
  orderBy?: Prisma.KbsExamQuestionAnswerOrderByWithRelationInput | Prisma.KbsExamQuestionAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KbsExamQuestionAnswers.
   */
  cursor?: Prisma.KbsExamQuestionAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsExamQuestionAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsExamQuestionAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KbsExamQuestionAnswers.
   */
  distinct?: Prisma.KbsExamQuestionAnswerScalarFieldEnum | Prisma.KbsExamQuestionAnswerScalarFieldEnum[]
}

/**
 * KbsExamQuestionAnswer findMany
 */
export type KbsExamQuestionAnswerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerInclude<ExtArgs> | null
  /**
   * Filter, which KbsExamQuestionAnswers to fetch.
   */
  where?: Prisma.KbsExamQuestionAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsExamQuestionAnswers to fetch.
   */
  orderBy?: Prisma.KbsExamQuestionAnswerOrderByWithRelationInput | Prisma.KbsExamQuestionAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KbsExamQuestionAnswers.
   */
  cursor?: Prisma.KbsExamQuestionAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsExamQuestionAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsExamQuestionAnswers.
   */
  skip?: number
  distinct?: Prisma.KbsExamQuestionAnswerScalarFieldEnum | Prisma.KbsExamQuestionAnswerScalarFieldEnum[]
}

/**
 * KbsExamQuestionAnswer create
 */
export type KbsExamQuestionAnswerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerInclude<ExtArgs> | null
  /**
   * The data needed to create a KbsExamQuestionAnswer.
   */
  data: Prisma.XOR<Prisma.KbsExamQuestionAnswerCreateInput, Prisma.KbsExamQuestionAnswerUncheckedCreateInput>
}

/**
 * KbsExamQuestionAnswer createMany
 */
export type KbsExamQuestionAnswerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many KbsExamQuestionAnswers.
   */
  data: Prisma.KbsExamQuestionAnswerCreateManyInput | Prisma.KbsExamQuestionAnswerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KbsExamQuestionAnswer createManyAndReturn
 */
export type KbsExamQuestionAnswerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * The data used to create many KbsExamQuestionAnswers.
   */
  data: Prisma.KbsExamQuestionAnswerCreateManyInput | Prisma.KbsExamQuestionAnswerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * KbsExamQuestionAnswer update
 */
export type KbsExamQuestionAnswerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerInclude<ExtArgs> | null
  /**
   * The data needed to update a KbsExamQuestionAnswer.
   */
  data: Prisma.XOR<Prisma.KbsExamQuestionAnswerUpdateInput, Prisma.KbsExamQuestionAnswerUncheckedUpdateInput>
  /**
   * Choose, which KbsExamQuestionAnswer to update.
   */
  where: Prisma.KbsExamQuestionAnswerWhereUniqueInput
}

/**
 * KbsExamQuestionAnswer updateMany
 */
export type KbsExamQuestionAnswerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KbsExamQuestionAnswers.
   */
  data: Prisma.XOR<Prisma.KbsExamQuestionAnswerUpdateManyMutationInput, Prisma.KbsExamQuestionAnswerUncheckedUpdateManyInput>
  /**
   * Filter which KbsExamQuestionAnswers to update
   */
  where?: Prisma.KbsExamQuestionAnswerWhereInput
  /**
   * Limit how many KbsExamQuestionAnswers to update.
   */
  limit?: number
}

/**
 * KbsExamQuestionAnswer updateManyAndReturn
 */
export type KbsExamQuestionAnswerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * The data used to update KbsExamQuestionAnswers.
   */
  data: Prisma.XOR<Prisma.KbsExamQuestionAnswerUpdateManyMutationInput, Prisma.KbsExamQuestionAnswerUncheckedUpdateManyInput>
  /**
   * Filter which KbsExamQuestionAnswers to update
   */
  where?: Prisma.KbsExamQuestionAnswerWhereInput
  /**
   * Limit how many KbsExamQuestionAnswers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * KbsExamQuestionAnswer upsert
 */
export type KbsExamQuestionAnswerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerInclude<ExtArgs> | null
  /**
   * The filter to search for the KbsExamQuestionAnswer to update in case it exists.
   */
  where: Prisma.KbsExamQuestionAnswerWhereUniqueInput
  /**
   * In case the KbsExamQuestionAnswer found by the `where` argument doesn't exist, create a new KbsExamQuestionAnswer with this data.
   */
  create: Prisma.XOR<Prisma.KbsExamQuestionAnswerCreateInput, Prisma.KbsExamQuestionAnswerUncheckedCreateInput>
  /**
   * In case the KbsExamQuestionAnswer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KbsExamQuestionAnswerUpdateInput, Prisma.KbsExamQuestionAnswerUncheckedUpdateInput>
}

/**
 * KbsExamQuestionAnswer delete
 */
export type KbsExamQuestionAnswerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerInclude<ExtArgs> | null
  /**
   * Filter which KbsExamQuestionAnswer to delete.
   */
  where: Prisma.KbsExamQuestionAnswerWhereUniqueInput
}

/**
 * KbsExamQuestionAnswer deleteMany
 */
export type KbsExamQuestionAnswerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KbsExamQuestionAnswers to delete
   */
  where?: Prisma.KbsExamQuestionAnswerWhereInput
  /**
   * Limit how many KbsExamQuestionAnswers to delete.
   */
  limit?: number
}

/**
 * KbsExamQuestionAnswer.selections
 */
export type KbsExamQuestionAnswer$selectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamAnswerSelection
   */
  select?: Prisma.KbsExamAnswerSelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamAnswerSelection
   */
  omit?: Prisma.KbsExamAnswerSelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamAnswerSelectionInclude<ExtArgs> | null
  where?: Prisma.KbsExamAnswerSelectionWhereInput
  orderBy?: Prisma.KbsExamAnswerSelectionOrderByWithRelationInput | Prisma.KbsExamAnswerSelectionOrderByWithRelationInput[]
  cursor?: Prisma.KbsExamAnswerSelectionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.KbsExamAnswerSelectionScalarFieldEnum | Prisma.KbsExamAnswerSelectionScalarFieldEnum[]
}

/**
 * KbsExamQuestionAnswer without action
 */
export type KbsExamQuestionAnswerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerInclude<ExtArgs> | null
}
