
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `KbsExamQuestion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model KbsExamQuestion
 * 
 */
export type KbsExamQuestionModel = runtime.Types.Result.DefaultSelection<Prisma.$KbsExamQuestionPayload>

export type AggregateKbsExamQuestion = {
  _count: KbsExamQuestionCountAggregateOutputType | null
  _min: KbsExamQuestionMinAggregateOutputType | null
  _max: KbsExamQuestionMaxAggregateOutputType | null
}

export type KbsExamQuestionMinAggregateOutputType = {
  id: string | null
  moduleId: string | null
  text: string | null
  type: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type KbsExamQuestionMaxAggregateOutputType = {
  id: string | null
  moduleId: string | null
  text: string | null
  type: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type KbsExamQuestionCountAggregateOutputType = {
  id: number
  moduleId: number
  text: number
  type: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type KbsExamQuestionMinAggregateInputType = {
  id?: true
  moduleId?: true
  text?: true
  type?: true
  createdAt?: true
  updatedAt?: true
}

export type KbsExamQuestionMaxAggregateInputType = {
  id?: true
  moduleId?: true
  text?: true
  type?: true
  createdAt?: true
  updatedAt?: true
}

export type KbsExamQuestionCountAggregateInputType = {
  id?: true
  moduleId?: true
  text?: true
  type?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type KbsExamQuestionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KbsExamQuestion to aggregate.
   */
  where?: Prisma.KbsExamQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsExamQuestions to fetch.
   */
  orderBy?: Prisma.KbsExamQuestionOrderByWithRelationInput | Prisma.KbsExamQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KbsExamQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsExamQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsExamQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KbsExamQuestions
  **/
  _count?: true | KbsExamQuestionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KbsExamQuestionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KbsExamQuestionMaxAggregateInputType
}

export type GetKbsExamQuestionAggregateType<T extends KbsExamQuestionAggregateArgs> = {
      [P in keyof T & keyof AggregateKbsExamQuestion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKbsExamQuestion[P]>
    : Prisma.GetScalarType<T[P], AggregateKbsExamQuestion[P]>
}




export type KbsExamQuestionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KbsExamQuestionWhereInput
  orderBy?: Prisma.KbsExamQuestionOrderByWithAggregationInput | Prisma.KbsExamQuestionOrderByWithAggregationInput[]
  by: Prisma.KbsExamQuestionScalarFieldEnum[] | Prisma.KbsExamQuestionScalarFieldEnum
  having?: Prisma.KbsExamQuestionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KbsExamQuestionCountAggregateInputType | true
  _min?: KbsExamQuestionMinAggregateInputType
  _max?: KbsExamQuestionMaxAggregateInputType
}

export type KbsExamQuestionGroupByOutputType = {
  id: string
  moduleId: string
  text: string
  type: string
  createdAt: Date
  updatedAt: Date
  _count: KbsExamQuestionCountAggregateOutputType | null
  _min: KbsExamQuestionMinAggregateOutputType | null
  _max: KbsExamQuestionMaxAggregateOutputType | null
}

type GetKbsExamQuestionGroupByPayload<T extends KbsExamQuestionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KbsExamQuestionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KbsExamQuestionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KbsExamQuestionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KbsExamQuestionGroupByOutputType[P]>
      }
    >
  >



export type KbsExamQuestionWhereInput = {
  AND?: Prisma.KbsExamQuestionWhereInput | Prisma.KbsExamQuestionWhereInput[]
  OR?: Prisma.KbsExamQuestionWhereInput[]
  NOT?: Prisma.KbsExamQuestionWhereInput | Prisma.KbsExamQuestionWhereInput[]
  id?: Prisma.StringFilter<"KbsExamQuestion"> | string
  moduleId?: Prisma.StringFilter<"KbsExamQuestion"> | string
  text?: Prisma.StringFilter<"KbsExamQuestion"> | string
  type?: Prisma.StringFilter<"KbsExamQuestion"> | string
  createdAt?: Prisma.DateTimeFilter<"KbsExamQuestion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KbsExamQuestion"> | Date | string
  module?: Prisma.XOR<Prisma.KbsModuleScalarRelationFilter, Prisma.KbsModuleWhereInput>
  answers?: Prisma.KbsExamQuestionAnswerListRelationFilter
  examAnswers?: Prisma.KbsExamAnswerListRelationFilter
}

export type KbsExamQuestionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  module?: Prisma.KbsModuleOrderByWithRelationInput
  answers?: Prisma.KbsExamQuestionAnswerOrderByRelationAggregateInput
  examAnswers?: Prisma.KbsExamAnswerOrderByRelationAggregateInput
}

export type KbsExamQuestionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.KbsExamQuestionWhereInput | Prisma.KbsExamQuestionWhereInput[]
  OR?: Prisma.KbsExamQuestionWhereInput[]
  NOT?: Prisma.KbsExamQuestionWhereInput | Prisma.KbsExamQuestionWhereInput[]
  moduleId?: Prisma.StringFilter<"KbsExamQuestion"> | string
  text?: Prisma.StringFilter<"KbsExamQuestion"> | string
  type?: Prisma.StringFilter<"KbsExamQuestion"> | string
  createdAt?: Prisma.DateTimeFilter<"KbsExamQuestion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KbsExamQuestion"> | Date | string
  module?: Prisma.XOR<Prisma.KbsModuleScalarRelationFilter, Prisma.KbsModuleWhereInput>
  answers?: Prisma.KbsExamQuestionAnswerListRelationFilter
  examAnswers?: Prisma.KbsExamAnswerListRelationFilter
}, "id">

export type KbsExamQuestionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.KbsExamQuestionCountOrderByAggregateInput
  _max?: Prisma.KbsExamQuestionMaxOrderByAggregateInput
  _min?: Prisma.KbsExamQuestionMinOrderByAggregateInput
}

export type KbsExamQuestionScalarWhereWithAggregatesInput = {
  AND?: Prisma.KbsExamQuestionScalarWhereWithAggregatesInput | Prisma.KbsExamQuestionScalarWhereWithAggregatesInput[]
  OR?: Prisma.KbsExamQuestionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KbsExamQuestionScalarWhereWithAggregatesInput | Prisma.KbsExamQuestionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"KbsExamQuestion"> | string
  moduleId?: Prisma.StringWithAggregatesFilter<"KbsExamQuestion"> | string
  text?: Prisma.StringWithAggregatesFilter<"KbsExamQuestion"> | string
  type?: Prisma.StringWithAggregatesFilter<"KbsExamQuestion"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"KbsExamQuestion"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"KbsExamQuestion"> | Date | string
}

export type KbsExamQuestionCreateInput = {
  id?: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  module: Prisma.KbsModuleCreateNestedOneWithoutExamQuestionsInput
  answers?: Prisma.KbsExamQuestionAnswerCreateNestedManyWithoutQuestionInput
  examAnswers?: Prisma.KbsExamAnswerCreateNestedManyWithoutQuestionInput
}

export type KbsExamQuestionUncheckedCreateInput = {
  id?: string
  moduleId: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  answers?: Prisma.KbsExamQuestionAnswerUncheckedCreateNestedManyWithoutQuestionInput
  examAnswers?: Prisma.KbsExamAnswerUncheckedCreateNestedManyWithoutQuestionInput
}

export type KbsExamQuestionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  module?: Prisma.KbsModuleUpdateOneRequiredWithoutExamQuestionsNestedInput
  answers?: Prisma.KbsExamQuestionAnswerUpdateManyWithoutQuestionNestedInput
  examAnswers?: Prisma.KbsExamAnswerUpdateManyWithoutQuestionNestedInput
}

export type KbsExamQuestionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  moduleId?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.KbsExamQuestionAnswerUncheckedUpdateManyWithoutQuestionNestedInput
  examAnswers?: Prisma.KbsExamAnswerUncheckedUpdateManyWithoutQuestionNestedInput
}

export type KbsExamQuestionCreateManyInput = {
  id?: string
  moduleId: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KbsExamQuestionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsExamQuestionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  moduleId?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsExamQuestionListRelationFilter = {
  every?: Prisma.KbsExamQuestionWhereInput
  some?: Prisma.KbsExamQuestionWhereInput
  none?: Prisma.KbsExamQuestionWhereInput
}

export type KbsExamQuestionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type KbsExamQuestionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KbsExamQuestionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KbsExamQuestionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KbsExamQuestionScalarRelationFilter = {
  is?: Prisma.KbsExamQuestionWhereInput
  isNot?: Prisma.KbsExamQuestionWhereInput
}

export type KbsExamQuestionCreateNestedManyWithoutModuleInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutModuleInput, Prisma.KbsExamQuestionUncheckedCreateWithoutModuleInput> | Prisma.KbsExamQuestionCreateWithoutModuleInput[] | Prisma.KbsExamQuestionUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.KbsExamQuestionCreateOrConnectWithoutModuleInput | Prisma.KbsExamQuestionCreateOrConnectWithoutModuleInput[]
  createMany?: Prisma.KbsExamQuestionCreateManyModuleInputEnvelope
  connect?: Prisma.KbsExamQuestionWhereUniqueInput | Prisma.KbsExamQuestionWhereUniqueInput[]
}

export type KbsExamQuestionUncheckedCreateNestedManyWithoutModuleInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutModuleInput, Prisma.KbsExamQuestionUncheckedCreateWithoutModuleInput> | Prisma.KbsExamQuestionCreateWithoutModuleInput[] | Prisma.KbsExamQuestionUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.KbsExamQuestionCreateOrConnectWithoutModuleInput | Prisma.KbsExamQuestionCreateOrConnectWithoutModuleInput[]
  createMany?: Prisma.KbsExamQuestionCreateManyModuleInputEnvelope
  connect?: Prisma.KbsExamQuestionWhereUniqueInput | Prisma.KbsExamQuestionWhereUniqueInput[]
}

export type KbsExamQuestionUpdateManyWithoutModuleNestedInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutModuleInput, Prisma.KbsExamQuestionUncheckedCreateWithoutModuleInput> | Prisma.KbsExamQuestionCreateWithoutModuleInput[] | Prisma.KbsExamQuestionUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.KbsExamQuestionCreateOrConnectWithoutModuleInput | Prisma.KbsExamQuestionCreateOrConnectWithoutModuleInput[]
  upsert?: Prisma.KbsExamQuestionUpsertWithWhereUniqueWithoutModuleInput | Prisma.KbsExamQuestionUpsertWithWhereUniqueWithoutModuleInput[]
  createMany?: Prisma.KbsExamQuestionCreateManyModuleInputEnvelope
  set?: Prisma.KbsExamQuestionWhereUniqueInput | Prisma.KbsExamQuestionWhereUniqueInput[]
  disconnect?: Prisma.KbsExamQuestionWhereUniqueInput | Prisma.KbsExamQuestionWhereUniqueInput[]
  delete?: Prisma.KbsExamQuestionWhereUniqueInput | Prisma.KbsExamQuestionWhereUniqueInput[]
  connect?: Prisma.KbsExamQuestionWhereUniqueInput | Prisma.KbsExamQuestionWhereUniqueInput[]
  update?: Prisma.KbsExamQuestionUpdateWithWhereUniqueWithoutModuleInput | Prisma.KbsExamQuestionUpdateWithWhereUniqueWithoutModuleInput[]
  updateMany?: Prisma.KbsExamQuestionUpdateManyWithWhereWithoutModuleInput | Prisma.KbsExamQuestionUpdateManyWithWhereWithoutModuleInput[]
  deleteMany?: Prisma.KbsExamQuestionScalarWhereInput | Prisma.KbsExamQuestionScalarWhereInput[]
}

export type KbsExamQuestionUncheckedUpdateManyWithoutModuleNestedInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutModuleInput, Prisma.KbsExamQuestionUncheckedCreateWithoutModuleInput> | Prisma.KbsExamQuestionCreateWithoutModuleInput[] | Prisma.KbsExamQuestionUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.KbsExamQuestionCreateOrConnectWithoutModuleInput | Prisma.KbsExamQuestionCreateOrConnectWithoutModuleInput[]
  upsert?: Prisma.KbsExamQuestionUpsertWithWhereUniqueWithoutModuleInput | Prisma.KbsExamQuestionUpsertWithWhereUniqueWithoutModuleInput[]
  createMany?: Prisma.KbsExamQuestionCreateManyModuleInputEnvelope
  set?: Prisma.KbsExamQuestionWhereUniqueInput | Prisma.KbsExamQuestionWhereUniqueInput[]
  disconnect?: Prisma.KbsExamQuestionWhereUniqueInput | Prisma.KbsExamQuestionWhereUniqueInput[]
  delete?: Prisma.KbsExamQuestionWhereUniqueInput | Prisma.KbsExamQuestionWhereUniqueInput[]
  connect?: Prisma.KbsExamQuestionWhereUniqueInput | Prisma.KbsExamQuestionWhereUniqueInput[]
  update?: Prisma.KbsExamQuestionUpdateWithWhereUniqueWithoutModuleInput | Prisma.KbsExamQuestionUpdateWithWhereUniqueWithoutModuleInput[]
  updateMany?: Prisma.KbsExamQuestionUpdateManyWithWhereWithoutModuleInput | Prisma.KbsExamQuestionUpdateManyWithWhereWithoutModuleInput[]
  deleteMany?: Prisma.KbsExamQuestionScalarWhereInput | Prisma.KbsExamQuestionScalarWhereInput[]
}

export type KbsExamQuestionCreateNestedOneWithoutAnswersInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutAnswersInput, Prisma.KbsExamQuestionUncheckedCreateWithoutAnswersInput>
  connectOrCreate?: Prisma.KbsExamQuestionCreateOrConnectWithoutAnswersInput
  connect?: Prisma.KbsExamQuestionWhereUniqueInput
}

export type KbsExamQuestionUpdateOneRequiredWithoutAnswersNestedInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutAnswersInput, Prisma.KbsExamQuestionUncheckedCreateWithoutAnswersInput>
  connectOrCreate?: Prisma.KbsExamQuestionCreateOrConnectWithoutAnswersInput
  upsert?: Prisma.KbsExamQuestionUpsertWithoutAnswersInput
  connect?: Prisma.KbsExamQuestionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.KbsExamQuestionUpdateToOneWithWhereWithoutAnswersInput, Prisma.KbsExamQuestionUpdateWithoutAnswersInput>, Prisma.KbsExamQuestionUncheckedUpdateWithoutAnswersInput>
}

export type KbsExamQuestionCreateNestedOneWithoutExamAnswersInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutExamAnswersInput, Prisma.KbsExamQuestionUncheckedCreateWithoutExamAnswersInput>
  connectOrCreate?: Prisma.KbsExamQuestionCreateOrConnectWithoutExamAnswersInput
  connect?: Prisma.KbsExamQuestionWhereUniqueInput
}

export type KbsExamQuestionUpdateOneRequiredWithoutExamAnswersNestedInput = {
  create?: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutExamAnswersInput, Prisma.KbsExamQuestionUncheckedCreateWithoutExamAnswersInput>
  connectOrCreate?: Prisma.KbsExamQuestionCreateOrConnectWithoutExamAnswersInput
  upsert?: Prisma.KbsExamQuestionUpsertWithoutExamAnswersInput
  connect?: Prisma.KbsExamQuestionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.KbsExamQuestionUpdateToOneWithWhereWithoutExamAnswersInput, Prisma.KbsExamQuestionUpdateWithoutExamAnswersInput>, Prisma.KbsExamQuestionUncheckedUpdateWithoutExamAnswersInput>
}

export type KbsExamQuestionCreateWithoutModuleInput = {
  id?: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  answers?: Prisma.KbsExamQuestionAnswerCreateNestedManyWithoutQuestionInput
  examAnswers?: Prisma.KbsExamAnswerCreateNestedManyWithoutQuestionInput
}

export type KbsExamQuestionUncheckedCreateWithoutModuleInput = {
  id?: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  answers?: Prisma.KbsExamQuestionAnswerUncheckedCreateNestedManyWithoutQuestionInput
  examAnswers?: Prisma.KbsExamAnswerUncheckedCreateNestedManyWithoutQuestionInput
}

export type KbsExamQuestionCreateOrConnectWithoutModuleInput = {
  where: Prisma.KbsExamQuestionWhereUniqueInput
  create: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutModuleInput, Prisma.KbsExamQuestionUncheckedCreateWithoutModuleInput>
}

export type KbsExamQuestionCreateManyModuleInputEnvelope = {
  data: Prisma.KbsExamQuestionCreateManyModuleInput | Prisma.KbsExamQuestionCreateManyModuleInput[]
  skipDuplicates?: boolean
}

export type KbsExamQuestionUpsertWithWhereUniqueWithoutModuleInput = {
  where: Prisma.KbsExamQuestionWhereUniqueInput
  update: Prisma.XOR<Prisma.KbsExamQuestionUpdateWithoutModuleInput, Prisma.KbsExamQuestionUncheckedUpdateWithoutModuleInput>
  create: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutModuleInput, Prisma.KbsExamQuestionUncheckedCreateWithoutModuleInput>
}

export type KbsExamQuestionUpdateWithWhereUniqueWithoutModuleInput = {
  where: Prisma.KbsExamQuestionWhereUniqueInput
  data: Prisma.XOR<Prisma.KbsExamQuestionUpdateWithoutModuleInput, Prisma.KbsExamQuestionUncheckedUpdateWithoutModuleInput>
}

export type KbsExamQuestionUpdateManyWithWhereWithoutModuleInput = {
  where: Prisma.KbsExamQuestionScalarWhereInput
  data: Prisma.XOR<Prisma.KbsExamQuestionUpdateManyMutationInput, Prisma.KbsExamQuestionUncheckedUpdateManyWithoutModuleInput>
}

export type KbsExamQuestionScalarWhereInput = {
  AND?: Prisma.KbsExamQuestionScalarWhereInput | Prisma.KbsExamQuestionScalarWhereInput[]
  OR?: Prisma.KbsExamQuestionScalarWhereInput[]
  NOT?: Prisma.KbsExamQuestionScalarWhereInput | Prisma.KbsExamQuestionScalarWhereInput[]
  id?: Prisma.StringFilter<"KbsExamQuestion"> | string
  moduleId?: Prisma.StringFilter<"KbsExamQuestion"> | string
  text?: Prisma.StringFilter<"KbsExamQuestion"> | string
  type?: Prisma.StringFilter<"KbsExamQuestion"> | string
  createdAt?: Prisma.DateTimeFilter<"KbsExamQuestion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KbsExamQuestion"> | Date | string
}

export type KbsExamQuestionCreateWithoutAnswersInput = {
  id?: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  module: Prisma.KbsModuleCreateNestedOneWithoutExamQuestionsInput
  examAnswers?: Prisma.KbsExamAnswerCreateNestedManyWithoutQuestionInput
}

export type KbsExamQuestionUncheckedCreateWithoutAnswersInput = {
  id?: string
  moduleId: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  examAnswers?: Prisma.KbsExamAnswerUncheckedCreateNestedManyWithoutQuestionInput
}

export type KbsExamQuestionCreateOrConnectWithoutAnswersInput = {
  where: Prisma.KbsExamQuestionWhereUniqueInput
  create: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutAnswersInput, Prisma.KbsExamQuestionUncheckedCreateWithoutAnswersInput>
}

export type KbsExamQuestionUpsertWithoutAnswersInput = {
  update: Prisma.XOR<Prisma.KbsExamQuestionUpdateWithoutAnswersInput, Prisma.KbsExamQuestionUncheckedUpdateWithoutAnswersInput>
  create: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutAnswersInput, Prisma.KbsExamQuestionUncheckedCreateWithoutAnswersInput>
  where?: Prisma.KbsExamQuestionWhereInput
}

export type KbsExamQuestionUpdateToOneWithWhereWithoutAnswersInput = {
  where?: Prisma.KbsExamQuestionWhereInput
  data: Prisma.XOR<Prisma.KbsExamQuestionUpdateWithoutAnswersInput, Prisma.KbsExamQuestionUncheckedUpdateWithoutAnswersInput>
}

export type KbsExamQuestionUpdateWithoutAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  module?: Prisma.KbsModuleUpdateOneRequiredWithoutExamQuestionsNestedInput
  examAnswers?: Prisma.KbsExamAnswerUpdateManyWithoutQuestionNestedInput
}

export type KbsExamQuestionUncheckedUpdateWithoutAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  moduleId?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  examAnswers?: Prisma.KbsExamAnswerUncheckedUpdateManyWithoutQuestionNestedInput
}

export type KbsExamQuestionCreateWithoutExamAnswersInput = {
  id?: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  module: Prisma.KbsModuleCreateNestedOneWithoutExamQuestionsInput
  answers?: Prisma.KbsExamQuestionAnswerCreateNestedManyWithoutQuestionInput
}

export type KbsExamQuestionUncheckedCreateWithoutExamAnswersInput = {
  id?: string
  moduleId: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  answers?: Prisma.KbsExamQuestionAnswerUncheckedCreateNestedManyWithoutQuestionInput
}

export type KbsExamQuestionCreateOrConnectWithoutExamAnswersInput = {
  where: Prisma.KbsExamQuestionWhereUniqueInput
  create: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutExamAnswersInput, Prisma.KbsExamQuestionUncheckedCreateWithoutExamAnswersInput>
}

export type KbsExamQuestionUpsertWithoutExamAnswersInput = {
  update: Prisma.XOR<Prisma.KbsExamQuestionUpdateWithoutExamAnswersInput, Prisma.KbsExamQuestionUncheckedUpdateWithoutExamAnswersInput>
  create: Prisma.XOR<Prisma.KbsExamQuestionCreateWithoutExamAnswersInput, Prisma.KbsExamQuestionUncheckedCreateWithoutExamAnswersInput>
  where?: Prisma.KbsExamQuestionWhereInput
}

export type KbsExamQuestionUpdateToOneWithWhereWithoutExamAnswersInput = {
  where?: Prisma.KbsExamQuestionWhereInput
  data: Prisma.XOR<Prisma.KbsExamQuestionUpdateWithoutExamAnswersInput, Prisma.KbsExamQuestionUncheckedUpdateWithoutExamAnswersInput>
}

export type KbsExamQuestionUpdateWithoutExamAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  module?: Prisma.KbsModuleUpdateOneRequiredWithoutExamQuestionsNestedInput
  answers?: Prisma.KbsExamQuestionAnswerUpdateManyWithoutQuestionNestedInput
}

export type KbsExamQuestionUncheckedUpdateWithoutExamAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  moduleId?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.KbsExamQuestionAnswerUncheckedUpdateManyWithoutQuestionNestedInput
}

export type KbsExamQuestionCreateManyModuleInput = {
  id?: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KbsExamQuestionUpdateWithoutModuleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.KbsExamQuestionAnswerUpdateManyWithoutQuestionNestedInput
  examAnswers?: Prisma.KbsExamAnswerUpdateManyWithoutQuestionNestedInput
}

export type KbsExamQuestionUncheckedUpdateWithoutModuleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.KbsExamQuestionAnswerUncheckedUpdateManyWithoutQuestionNestedInput
  examAnswers?: Prisma.KbsExamAnswerUncheckedUpdateManyWithoutQuestionNestedInput
}

export type KbsExamQuestionUncheckedUpdateManyWithoutModuleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type KbsExamQuestionCountOutputType
 */

export type KbsExamQuestionCountOutputType = {
  answers: number
  examAnswers: number
}

export type KbsExamQuestionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  answers?: boolean | KbsExamQuestionCountOutputTypeCountAnswersArgs
  examAnswers?: boolean | KbsExamQuestionCountOutputTypeCountExamAnswersArgs
}

/**
 * KbsExamQuestionCountOutputType without action
 */
export type KbsExamQuestionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionCountOutputType
   */
  select?: Prisma.KbsExamQuestionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * KbsExamQuestionCountOutputType without action
 */
export type KbsExamQuestionCountOutputTypeCountAnswersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KbsExamQuestionAnswerWhereInput
}

/**
 * KbsExamQuestionCountOutputType without action
 */
export type KbsExamQuestionCountOutputTypeCountExamAnswersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KbsExamAnswerWhereInput
}


export type KbsExamQuestionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  moduleId?: boolean
  text?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  module?: boolean | Prisma.KbsModuleDefaultArgs<ExtArgs>
  answers?: boolean | Prisma.KbsExamQuestion$answersArgs<ExtArgs>
  examAnswers?: boolean | Prisma.KbsExamQuestion$examAnswersArgs<ExtArgs>
  _count?: boolean | Prisma.KbsExamQuestionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kbsExamQuestion"]>

export type KbsExamQuestionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  moduleId?: boolean
  text?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  module?: boolean | Prisma.KbsModuleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kbsExamQuestion"]>

export type KbsExamQuestionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  moduleId?: boolean
  text?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  module?: boolean | Prisma.KbsModuleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kbsExamQuestion"]>

export type KbsExamQuestionSelectScalar = {
  id?: boolean
  moduleId?: boolean
  text?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type KbsExamQuestionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "moduleId" | "text" | "type" | "createdAt" | "updatedAt", ExtArgs["result"]["kbsExamQuestion"]>
export type KbsExamQuestionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  module?: boolean | Prisma.KbsModuleDefaultArgs<ExtArgs>
  answers?: boolean | Prisma.KbsExamQuestion$answersArgs<ExtArgs>
  examAnswers?: boolean | Prisma.KbsExamQuestion$examAnswersArgs<ExtArgs>
  _count?: boolean | Prisma.KbsExamQuestionCountOutputTypeDefaultArgs<ExtArgs>
}
export type KbsExamQuestionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  module?: boolean | Prisma.KbsModuleDefaultArgs<ExtArgs>
}
export type KbsExamQuestionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  module?: boolean | Prisma.KbsModuleDefaultArgs<ExtArgs>
}

export type $KbsExamQuestionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KbsExamQuestion"
  objects: {
    module: Prisma.$KbsModulePayload<ExtArgs>
    answers: Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>[]
    examAnswers: Prisma.$KbsExamAnswerPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    moduleId: string
    text: string
    type: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["kbsExamQuestion"]>
  composites: {}
}

export type KbsExamQuestionGetPayload<S extends boolean | null | undefined | KbsExamQuestionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload, S>

export type KbsExamQuestionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KbsExamQuestionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KbsExamQuestionCountAggregateInputType | true
  }

export interface KbsExamQuestionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KbsExamQuestion'], meta: { name: 'KbsExamQuestion' } }
  /**
   * Find zero or one KbsExamQuestion that matches the filter.
   * @param {KbsExamQuestionFindUniqueArgs} args - Arguments to find a KbsExamQuestion
   * @example
   * // Get one KbsExamQuestion
   * const kbsExamQuestion = await prisma.kbsExamQuestion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KbsExamQuestionFindUniqueArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KbsExamQuestion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KbsExamQuestionFindUniqueOrThrowArgs} args - Arguments to find a KbsExamQuestion
   * @example
   * // Get one KbsExamQuestion
   * const kbsExamQuestion = await prisma.kbsExamQuestion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KbsExamQuestionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KbsExamQuestion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionFindFirstArgs} args - Arguments to find a KbsExamQuestion
   * @example
   * // Get one KbsExamQuestion
   * const kbsExamQuestion = await prisma.kbsExamQuestion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KbsExamQuestionFindFirstArgs>(args?: Prisma.SelectSubset<T, KbsExamQuestionFindFirstArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KbsExamQuestion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionFindFirstOrThrowArgs} args - Arguments to find a KbsExamQuestion
   * @example
   * // Get one KbsExamQuestion
   * const kbsExamQuestion = await prisma.kbsExamQuestion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KbsExamQuestionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KbsExamQuestionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KbsExamQuestions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KbsExamQuestions
   * const kbsExamQuestions = await prisma.kbsExamQuestion.findMany()
   * 
   * // Get first 10 KbsExamQuestions
   * const kbsExamQuestions = await prisma.kbsExamQuestion.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kbsExamQuestionWithIdOnly = await prisma.kbsExamQuestion.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KbsExamQuestionFindManyArgs>(args?: Prisma.SelectSubset<T, KbsExamQuestionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a KbsExamQuestion.
   * @param {KbsExamQuestionCreateArgs} args - Arguments to create a KbsExamQuestion.
   * @example
   * // Create one KbsExamQuestion
   * const KbsExamQuestion = await prisma.kbsExamQuestion.create({
   *   data: {
   *     // ... data to create a KbsExamQuestion
   *   }
   * })
   * 
   */
  create<T extends KbsExamQuestionCreateArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionCreateArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many KbsExamQuestions.
   * @param {KbsExamQuestionCreateManyArgs} args - Arguments to create many KbsExamQuestions.
   * @example
   * // Create many KbsExamQuestions
   * const kbsExamQuestion = await prisma.kbsExamQuestion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KbsExamQuestionCreateManyArgs>(args?: Prisma.SelectSubset<T, KbsExamQuestionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many KbsExamQuestions and returns the data saved in the database.
   * @param {KbsExamQuestionCreateManyAndReturnArgs} args - Arguments to create many KbsExamQuestions.
   * @example
   * // Create many KbsExamQuestions
   * const kbsExamQuestion = await prisma.kbsExamQuestion.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many KbsExamQuestions and only return the `id`
   * const kbsExamQuestionWithIdOnly = await prisma.kbsExamQuestion.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KbsExamQuestionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KbsExamQuestionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a KbsExamQuestion.
   * @param {KbsExamQuestionDeleteArgs} args - Arguments to delete one KbsExamQuestion.
   * @example
   * // Delete one KbsExamQuestion
   * const KbsExamQuestion = await prisma.kbsExamQuestion.delete({
   *   where: {
   *     // ... filter to delete one KbsExamQuestion
   *   }
   * })
   * 
   */
  delete<T extends KbsExamQuestionDeleteArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionDeleteArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KbsExamQuestion.
   * @param {KbsExamQuestionUpdateArgs} args - Arguments to update one KbsExamQuestion.
   * @example
   * // Update one KbsExamQuestion
   * const kbsExamQuestion = await prisma.kbsExamQuestion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KbsExamQuestionUpdateArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionUpdateArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KbsExamQuestions.
   * @param {KbsExamQuestionDeleteManyArgs} args - Arguments to filter KbsExamQuestions to delete.
   * @example
   * // Delete a few KbsExamQuestions
   * const { count } = await prisma.kbsExamQuestion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KbsExamQuestionDeleteManyArgs>(args?: Prisma.SelectSubset<T, KbsExamQuestionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KbsExamQuestions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KbsExamQuestions
   * const kbsExamQuestion = await prisma.kbsExamQuestion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KbsExamQuestionUpdateManyArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KbsExamQuestions and returns the data updated in the database.
   * @param {KbsExamQuestionUpdateManyAndReturnArgs} args - Arguments to update many KbsExamQuestions.
   * @example
   * // Update many KbsExamQuestions
   * const kbsExamQuestion = await prisma.kbsExamQuestion.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more KbsExamQuestions and only return the `id`
   * const kbsExamQuestionWithIdOnly = await prisma.kbsExamQuestion.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KbsExamQuestionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one KbsExamQuestion.
   * @param {KbsExamQuestionUpsertArgs} args - Arguments to update or create a KbsExamQuestion.
   * @example
   * // Update or create a KbsExamQuestion
   * const kbsExamQuestion = await prisma.kbsExamQuestion.upsert({
   *   create: {
   *     // ... data to create a KbsExamQuestion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the KbsExamQuestion we want to update
   *   }
   * })
   */
  upsert<T extends KbsExamQuestionUpsertArgs>(args: Prisma.SelectSubset<T, KbsExamQuestionUpsertArgs<ExtArgs>>): Prisma.Prisma__KbsExamQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of KbsExamQuestions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionCountArgs} args - Arguments to filter KbsExamQuestions to count.
   * @example
   * // Count the number of KbsExamQuestions
   * const count = await prisma.kbsExamQuestion.count({
   *   where: {
   *     // ... the filter for the KbsExamQuestions we want to count
   *   }
   * })
  **/
  count<T extends KbsExamQuestionCountArgs>(
    args?: Prisma.Subset<T, KbsExamQuestionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KbsExamQuestionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KbsExamQuestion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KbsExamQuestionAggregateArgs>(args: Prisma.Subset<T, KbsExamQuestionAggregateArgs>): Prisma.PrismaPromise<GetKbsExamQuestionAggregateType<T>>

  /**
   * Group by KbsExamQuestion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsExamQuestionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KbsExamQuestionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KbsExamQuestionGroupByArgs['orderBy'] }
      : { orderBy?: KbsExamQuestionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KbsExamQuestionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKbsExamQuestionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KbsExamQuestion model
 */
readonly fields: KbsExamQuestionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KbsExamQuestion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KbsExamQuestionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  module<T extends Prisma.KbsModuleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KbsModuleDefaultArgs<ExtArgs>>): Prisma.Prisma__KbsModuleClient<runtime.Types.Result.GetResult<Prisma.$KbsModulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  answers<T extends Prisma.KbsExamQuestion$answersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KbsExamQuestion$answersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsExamQuestionAnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  examAnswers<T extends Prisma.KbsExamQuestion$examAnswersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KbsExamQuestion$examAnswersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsExamAnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KbsExamQuestion model
 */
export interface KbsExamQuestionFieldRefs {
  readonly id: Prisma.FieldRef<"KbsExamQuestion", 'String'>
  readonly moduleId: Prisma.FieldRef<"KbsExamQuestion", 'String'>
  readonly text: Prisma.FieldRef<"KbsExamQuestion", 'String'>
  readonly type: Prisma.FieldRef<"KbsExamQuestion", 'String'>
  readonly createdAt: Prisma.FieldRef<"KbsExamQuestion", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"KbsExamQuestion", 'DateTime'>
}
    

// Custom InputTypes
/**
 * KbsExamQuestion findUnique
 */
export type KbsExamQuestionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestion
   */
  select?: Prisma.KbsExamQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestion
   */
  omit?: Prisma.KbsExamQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionInclude<ExtArgs> | null
  /**
   * Filter, which KbsExamQuestion to fetch.
   */
  where: Prisma.KbsExamQuestionWhereUniqueInput
}

/**
 * KbsExamQuestion findUniqueOrThrow
 */
export type KbsExamQuestionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestion
   */
  select?: Prisma.KbsExamQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestion
   */
  omit?: Prisma.KbsExamQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionInclude<ExtArgs> | null
  /**
   * Filter, which KbsExamQuestion to fetch.
   */
  where: Prisma.KbsExamQuestionWhereUniqueInput
}

/**
 * KbsExamQuestion findFirst
 */
export type KbsExamQuestionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestion
   */
  select?: Prisma.KbsExamQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestion
   */
  omit?: Prisma.KbsExamQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionInclude<ExtArgs> | null
  /**
   * Filter, which KbsExamQuestion to fetch.
   */
  where?: Prisma.KbsExamQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsExamQuestions to fetch.
   */
  orderBy?: Prisma.KbsExamQuestionOrderByWithRelationInput | Prisma.KbsExamQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KbsExamQuestions.
   */
  cursor?: Prisma.KbsExamQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsExamQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsExamQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KbsExamQuestions.
   */
  distinct?: Prisma.KbsExamQuestionScalarFieldEnum | Prisma.KbsExamQuestionScalarFieldEnum[]
}

/**
 * KbsExamQuestion findFirstOrThrow
 */
export type KbsExamQuestionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestion
   */
  select?: Prisma.KbsExamQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestion
   */
  omit?: Prisma.KbsExamQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionInclude<ExtArgs> | null
  /**
   * Filter, which KbsExamQuestion to fetch.
   */
  where?: Prisma.KbsExamQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsExamQuestions to fetch.
   */
  orderBy?: Prisma.KbsExamQuestionOrderByWithRelationInput | Prisma.KbsExamQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KbsExamQuestions.
   */
  cursor?: Prisma.KbsExamQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsExamQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsExamQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KbsExamQuestions.
   */
  distinct?: Prisma.KbsExamQuestionScalarFieldEnum | Prisma.KbsExamQuestionScalarFieldEnum[]
}

/**
 * KbsExamQuestion findMany
 */
export type KbsExamQuestionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestion
   */
  select?: Prisma.KbsExamQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestion
   */
  omit?: Prisma.KbsExamQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionInclude<ExtArgs> | null
  /**
   * Filter, which KbsExamQuestions to fetch.
   */
  where?: Prisma.KbsExamQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsExamQuestions to fetch.
   */
  orderBy?: Prisma.KbsExamQuestionOrderByWithRelationInput | Prisma.KbsExamQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KbsExamQuestions.
   */
  cursor?: Prisma.KbsExamQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsExamQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsExamQuestions.
   */
  skip?: number
  distinct?: Prisma.KbsExamQuestionScalarFieldEnum | Prisma.KbsExamQuestionScalarFieldEnum[]
}

/**
 * KbsExamQuestion create
 */
export type KbsExamQuestionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestion
   */
  select?: Prisma.KbsExamQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestion
   */
  omit?: Prisma.KbsExamQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionInclude<ExtArgs> | null
  /**
   * The data needed to create a KbsExamQuestion.
   */
  data: Prisma.XOR<Prisma.KbsExamQuestionCreateInput, Prisma.KbsExamQuestionUncheckedCreateInput>
}

/**
 * KbsExamQuestion createMany
 */
export type KbsExamQuestionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many KbsExamQuestions.
   */
  data: Prisma.KbsExamQuestionCreateManyInput | Prisma.KbsExamQuestionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KbsExamQuestion createManyAndReturn
 */
export type KbsExamQuestionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestion
   */
  select?: Prisma.KbsExamQuestionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestion
   */
  omit?: Prisma.KbsExamQuestionOmit<ExtArgs> | null
  /**
   * The data used to create many KbsExamQuestions.
   */
  data: Prisma.KbsExamQuestionCreateManyInput | Prisma.KbsExamQuestionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * KbsExamQuestion update
 */
export type KbsExamQuestionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestion
   */
  select?: Prisma.KbsExamQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestion
   */
  omit?: Prisma.KbsExamQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionInclude<ExtArgs> | null
  /**
   * The data needed to update a KbsExamQuestion.
   */
  data: Prisma.XOR<Prisma.KbsExamQuestionUpdateInput, Prisma.KbsExamQuestionUncheckedUpdateInput>
  /**
   * Choose, which KbsExamQuestion to update.
   */
  where: Prisma.KbsExamQuestionWhereUniqueInput
}

/**
 * KbsExamQuestion updateMany
 */
export type KbsExamQuestionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KbsExamQuestions.
   */
  data: Prisma.XOR<Prisma.KbsExamQuestionUpdateManyMutationInput, Prisma.KbsExamQuestionUncheckedUpdateManyInput>
  /**
   * Filter which KbsExamQuestions to update
   */
  where?: Prisma.KbsExamQuestionWhereInput
  /**
   * Limit how many KbsExamQuestions to update.
   */
  limit?: number
}

/**
 * KbsExamQuestion updateManyAndReturn
 */
export type KbsExamQuestionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestion
   */
  select?: Prisma.KbsExamQuestionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestion
   */
  omit?: Prisma.KbsExamQuestionOmit<ExtArgs> | null
  /**
   * The data used to update KbsExamQuestions.
   */
  data: Prisma.XOR<Prisma.KbsExamQuestionUpdateManyMutationInput, Prisma.KbsExamQuestionUncheckedUpdateManyInput>
  /**
   * Filter which KbsExamQuestions to update
   */
  where?: Prisma.KbsExamQuestionWhereInput
  /**
   * Limit how many KbsExamQuestions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * KbsExamQuestion upsert
 */
export type KbsExamQuestionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestion
   */
  select?: Prisma.KbsExamQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestion
   */
  omit?: Prisma.KbsExamQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionInclude<ExtArgs> | null
  /**
   * The filter to search for the KbsExamQuestion to update in case it exists.
   */
  where: Prisma.KbsExamQuestionWhereUniqueInput
  /**
   * In case the KbsExamQuestion found by the `where` argument doesn't exist, create a new KbsExamQuestion with this data.
   */
  create: Prisma.XOR<Prisma.KbsExamQuestionCreateInput, Prisma.KbsExamQuestionUncheckedCreateInput>
  /**
   * In case the KbsExamQuestion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KbsExamQuestionUpdateInput, Prisma.KbsExamQuestionUncheckedUpdateInput>
}

/**
 * KbsExamQuestion delete
 */
export type KbsExamQuestionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestion
   */
  select?: Prisma.KbsExamQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestion
   */
  omit?: Prisma.KbsExamQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionInclude<ExtArgs> | null
  /**
   * Filter which KbsExamQuestion to delete.
   */
  where: Prisma.KbsExamQuestionWhereUniqueInput
}

/**
 * KbsExamQuestion deleteMany
 */
export type KbsExamQuestionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KbsExamQuestions to delete
   */
  where?: Prisma.KbsExamQuestionWhereInput
  /**
   * Limit how many KbsExamQuestions to delete.
   */
  limit?: number
}

/**
 * KbsExamQuestion.answers
 */
export type KbsExamQuestion$answersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestionAnswer
   */
  select?: Prisma.KbsExamQuestionAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestionAnswer
   */
  omit?: Prisma.KbsExamQuestionAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionAnswerInclude<ExtArgs> | null
  where?: Prisma.KbsExamQuestionAnswerWhereInput
  orderBy?: Prisma.KbsExamQuestionAnswerOrderByWithRelationInput | Prisma.KbsExamQuestionAnswerOrderByWithRelationInput[]
  cursor?: Prisma.KbsExamQuestionAnswerWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.KbsExamQuestionAnswerScalarFieldEnum | Prisma.KbsExamQuestionAnswerScalarFieldEnum[]
}

/**
 * KbsExamQuestion.examAnswers
 */
export type KbsExamQuestion$examAnswersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamAnswer
   */
  select?: Prisma.KbsExamAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamAnswer
   */
  omit?: Prisma.KbsExamAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamAnswerInclude<ExtArgs> | null
  where?: Prisma.KbsExamAnswerWhereInput
  orderBy?: Prisma.KbsExamAnswerOrderByWithRelationInput | Prisma.KbsExamAnswerOrderByWithRelationInput[]
  cursor?: Prisma.KbsExamAnswerWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.KbsExamAnswerScalarFieldEnum | Prisma.KbsExamAnswerScalarFieldEnum[]
}

/**
 * KbsExamQuestion without action
 */
export type KbsExamQuestionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsExamQuestion
   */
  select?: Prisma.KbsExamQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsExamQuestion
   */
  omit?: Prisma.KbsExamQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsExamQuestionInclude<ExtArgs> | null
}
