
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `KbsLessonCompletion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model KbsLessonCompletion
 * 
 */
export type KbsLessonCompletionModel = runtime.Types.Result.DefaultSelection<Prisma.$KbsLessonCompletionPayload>

export type AggregateKbsLessonCompletion = {
  _count: KbsLessonCompletionCountAggregateOutputType | null
  _min: KbsLessonCompletionMinAggregateOutputType | null
  _max: KbsLessonCompletionMaxAggregateOutputType | null
}

export type KbsLessonCompletionMinAggregateOutputType = {
  id: string | null
  candidateId: string | null
  lessonId: string | null
  completedAt: Date | null
}

export type KbsLessonCompletionMaxAggregateOutputType = {
  id: string | null
  candidateId: string | null
  lessonId: string | null
  completedAt: Date | null
}

export type KbsLessonCompletionCountAggregateOutputType = {
  id: number
  candidateId: number
  lessonId: number
  completedAt: number
  _all: number
}


export type KbsLessonCompletionMinAggregateInputType = {
  id?: true
  candidateId?: true
  lessonId?: true
  completedAt?: true
}

export type KbsLessonCompletionMaxAggregateInputType = {
  id?: true
  candidateId?: true
  lessonId?: true
  completedAt?: true
}

export type KbsLessonCompletionCountAggregateInputType = {
  id?: true
  candidateId?: true
  lessonId?: true
  completedAt?: true
  _all?: true
}

export type KbsLessonCompletionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KbsLessonCompletion to aggregate.
   */
  where?: Prisma.KbsLessonCompletionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsLessonCompletions to fetch.
   */
  orderBy?: Prisma.KbsLessonCompletionOrderByWithRelationInput | Prisma.KbsLessonCompletionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KbsLessonCompletionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsLessonCompletions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsLessonCompletions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KbsLessonCompletions
  **/
  _count?: true | KbsLessonCompletionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KbsLessonCompletionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KbsLessonCompletionMaxAggregateInputType
}

export type GetKbsLessonCompletionAggregateType<T extends KbsLessonCompletionAggregateArgs> = {
      [P in keyof T & keyof AggregateKbsLessonCompletion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKbsLessonCompletion[P]>
    : Prisma.GetScalarType<T[P], AggregateKbsLessonCompletion[P]>
}




export type KbsLessonCompletionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KbsLessonCompletionWhereInput
  orderBy?: Prisma.KbsLessonCompletionOrderByWithAggregationInput | Prisma.KbsLessonCompletionOrderByWithAggregationInput[]
  by: Prisma.KbsLessonCompletionScalarFieldEnum[] | Prisma.KbsLessonCompletionScalarFieldEnum
  having?: Prisma.KbsLessonCompletionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KbsLessonCompletionCountAggregateInputType | true
  _min?: KbsLessonCompletionMinAggregateInputType
  _max?: KbsLessonCompletionMaxAggregateInputType
}

export type KbsLessonCompletionGroupByOutputType = {
  id: string
  candidateId: string
  lessonId: string
  completedAt: Date
  _count: KbsLessonCompletionCountAggregateOutputType | null
  _min: KbsLessonCompletionMinAggregateOutputType | null
  _max: KbsLessonCompletionMaxAggregateOutputType | null
}

type GetKbsLessonCompletionGroupByPayload<T extends KbsLessonCompletionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KbsLessonCompletionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KbsLessonCompletionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KbsLessonCompletionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KbsLessonCompletionGroupByOutputType[P]>
      }
    >
  >



export type KbsLessonCompletionWhereInput = {
  AND?: Prisma.KbsLessonCompletionWhereInput | Prisma.KbsLessonCompletionWhereInput[]
  OR?: Prisma.KbsLessonCompletionWhereInput[]
  NOT?: Prisma.KbsLessonCompletionWhereInput | Prisma.KbsLessonCompletionWhereInput[]
  id?: Prisma.StringFilter<"KbsLessonCompletion"> | string
  candidateId?: Prisma.StringFilter<"KbsLessonCompletion"> | string
  lessonId?: Prisma.StringFilter<"KbsLessonCompletion"> | string
  completedAt?: Prisma.DateTimeFilter<"KbsLessonCompletion"> | Date | string
  candidate?: Prisma.XOR<Prisma.KbsCandidateScalarRelationFilter, Prisma.KbsCandidateWhereInput>
  lesson?: Prisma.XOR<Prisma.KbsLessonScalarRelationFilter, Prisma.KbsLessonWhereInput>
}

export type KbsLessonCompletionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  candidateId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  candidate?: Prisma.KbsCandidateOrderByWithRelationInput
  lesson?: Prisma.KbsLessonOrderByWithRelationInput
}

export type KbsLessonCompletionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  candidateId_lessonId?: Prisma.KbsLessonCompletionCandidateIdLessonIdCompoundUniqueInput
  AND?: Prisma.KbsLessonCompletionWhereInput | Prisma.KbsLessonCompletionWhereInput[]
  OR?: Prisma.KbsLessonCompletionWhereInput[]
  NOT?: Prisma.KbsLessonCompletionWhereInput | Prisma.KbsLessonCompletionWhereInput[]
  candidateId?: Prisma.StringFilter<"KbsLessonCompletion"> | string
  lessonId?: Prisma.StringFilter<"KbsLessonCompletion"> | string
  completedAt?: Prisma.DateTimeFilter<"KbsLessonCompletion"> | Date | string
  candidate?: Prisma.XOR<Prisma.KbsCandidateScalarRelationFilter, Prisma.KbsCandidateWhereInput>
  lesson?: Prisma.XOR<Prisma.KbsLessonScalarRelationFilter, Prisma.KbsLessonWhereInput>
}, "id" | "candidateId_lessonId">

export type KbsLessonCompletionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  candidateId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  _count?: Prisma.KbsLessonCompletionCountOrderByAggregateInput
  _max?: Prisma.KbsLessonCompletionMaxOrderByAggregateInput
  _min?: Prisma.KbsLessonCompletionMinOrderByAggregateInput
}

export type KbsLessonCompletionScalarWhereWithAggregatesInput = {
  AND?: Prisma.KbsLessonCompletionScalarWhereWithAggregatesInput | Prisma.KbsLessonCompletionScalarWhereWithAggregatesInput[]
  OR?: Prisma.KbsLessonCompletionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KbsLessonCompletionScalarWhereWithAggregatesInput | Prisma.KbsLessonCompletionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"KbsLessonCompletion"> | string
  candidateId?: Prisma.StringWithAggregatesFilter<"KbsLessonCompletion"> | string
  lessonId?: Prisma.StringWithAggregatesFilter<"KbsLessonCompletion"> | string
  completedAt?: Prisma.DateTimeWithAggregatesFilter<"KbsLessonCompletion"> | Date | string
}

export type KbsLessonCompletionCreateInput = {
  id?: string
  completedAt?: Date | string
  candidate: Prisma.KbsCandidateCreateNestedOneWithoutLessonCompletionsInput
  lesson: Prisma.KbsLessonCreateNestedOneWithoutLessonCompletionsInput
}

export type KbsLessonCompletionUncheckedCreateInput = {
  id?: string
  candidateId: string
  lessonId: string
  completedAt?: Date | string
}

export type KbsLessonCompletionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  candidate?: Prisma.KbsCandidateUpdateOneRequiredWithoutLessonCompletionsNestedInput
  lesson?: Prisma.KbsLessonUpdateOneRequiredWithoutLessonCompletionsNestedInput
}

export type KbsLessonCompletionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  candidateId?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsLessonCompletionCreateManyInput = {
  id?: string
  candidateId: string
  lessonId: string
  completedAt?: Date | string
}

export type KbsLessonCompletionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsLessonCompletionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  candidateId?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsLessonCompletionListRelationFilter = {
  every?: Prisma.KbsLessonCompletionWhereInput
  some?: Prisma.KbsLessonCompletionWhereInput
  none?: Prisma.KbsLessonCompletionWhereInput
}

export type KbsLessonCompletionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type KbsLessonCompletionCandidateIdLessonIdCompoundUniqueInput = {
  candidateId: string
  lessonId: string
}

export type KbsLessonCompletionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidateId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type KbsLessonCompletionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidateId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type KbsLessonCompletionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidateId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type KbsLessonCompletionCreateNestedManyWithoutLessonInput = {
  create?: Prisma.XOR<Prisma.KbsLessonCompletionCreateWithoutLessonInput, Prisma.KbsLessonCompletionUncheckedCreateWithoutLessonInput> | Prisma.KbsLessonCompletionCreateWithoutLessonInput[] | Prisma.KbsLessonCompletionUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.KbsLessonCompletionCreateOrConnectWithoutLessonInput | Prisma.KbsLessonCompletionCreateOrConnectWithoutLessonInput[]
  createMany?: Prisma.KbsLessonCompletionCreateManyLessonInputEnvelope
  connect?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
}

export type KbsLessonCompletionUncheckedCreateNestedManyWithoutLessonInput = {
  create?: Prisma.XOR<Prisma.KbsLessonCompletionCreateWithoutLessonInput, Prisma.KbsLessonCompletionUncheckedCreateWithoutLessonInput> | Prisma.KbsLessonCompletionCreateWithoutLessonInput[] | Prisma.KbsLessonCompletionUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.KbsLessonCompletionCreateOrConnectWithoutLessonInput | Prisma.KbsLessonCompletionCreateOrConnectWithoutLessonInput[]
  createMany?: Prisma.KbsLessonCompletionCreateManyLessonInputEnvelope
  connect?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
}

export type KbsLessonCompletionUpdateManyWithoutLessonNestedInput = {
  create?: Prisma.XOR<Prisma.KbsLessonCompletionCreateWithoutLessonInput, Prisma.KbsLessonCompletionUncheckedCreateWithoutLessonInput> | Prisma.KbsLessonCompletionCreateWithoutLessonInput[] | Prisma.KbsLessonCompletionUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.KbsLessonCompletionCreateOrConnectWithoutLessonInput | Prisma.KbsLessonCompletionCreateOrConnectWithoutLessonInput[]
  upsert?: Prisma.KbsLessonCompletionUpsertWithWhereUniqueWithoutLessonInput | Prisma.KbsLessonCompletionUpsertWithWhereUniqueWithoutLessonInput[]
  createMany?: Prisma.KbsLessonCompletionCreateManyLessonInputEnvelope
  set?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  disconnect?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  delete?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  connect?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  update?: Prisma.KbsLessonCompletionUpdateWithWhereUniqueWithoutLessonInput | Prisma.KbsLessonCompletionUpdateWithWhereUniqueWithoutLessonInput[]
  updateMany?: Prisma.KbsLessonCompletionUpdateManyWithWhereWithoutLessonInput | Prisma.KbsLessonCompletionUpdateManyWithWhereWithoutLessonInput[]
  deleteMany?: Prisma.KbsLessonCompletionScalarWhereInput | Prisma.KbsLessonCompletionScalarWhereInput[]
}

export type KbsLessonCompletionUncheckedUpdateManyWithoutLessonNestedInput = {
  create?: Prisma.XOR<Prisma.KbsLessonCompletionCreateWithoutLessonInput, Prisma.KbsLessonCompletionUncheckedCreateWithoutLessonInput> | Prisma.KbsLessonCompletionCreateWithoutLessonInput[] | Prisma.KbsLessonCompletionUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.KbsLessonCompletionCreateOrConnectWithoutLessonInput | Prisma.KbsLessonCompletionCreateOrConnectWithoutLessonInput[]
  upsert?: Prisma.KbsLessonCompletionUpsertWithWhereUniqueWithoutLessonInput | Prisma.KbsLessonCompletionUpsertWithWhereUniqueWithoutLessonInput[]
  createMany?: Prisma.KbsLessonCompletionCreateManyLessonInputEnvelope
  set?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  disconnect?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  delete?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  connect?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  update?: Prisma.KbsLessonCompletionUpdateWithWhereUniqueWithoutLessonInput | Prisma.KbsLessonCompletionUpdateWithWhereUniqueWithoutLessonInput[]
  updateMany?: Prisma.KbsLessonCompletionUpdateManyWithWhereWithoutLessonInput | Prisma.KbsLessonCompletionUpdateManyWithWhereWithoutLessonInput[]
  deleteMany?: Prisma.KbsLessonCompletionScalarWhereInput | Prisma.KbsLessonCompletionScalarWhereInput[]
}

export type KbsLessonCompletionCreateNestedManyWithoutCandidateInput = {
  create?: Prisma.XOR<Prisma.KbsLessonCompletionCreateWithoutCandidateInput, Prisma.KbsLessonCompletionUncheckedCreateWithoutCandidateInput> | Prisma.KbsLessonCompletionCreateWithoutCandidateInput[] | Prisma.KbsLessonCompletionUncheckedCreateWithoutCandidateInput[]
  connectOrCreate?: Prisma.KbsLessonCompletionCreateOrConnectWithoutCandidateInput | Prisma.KbsLessonCompletionCreateOrConnectWithoutCandidateInput[]
  createMany?: Prisma.KbsLessonCompletionCreateManyCandidateInputEnvelope
  connect?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
}

export type KbsLessonCompletionUncheckedCreateNestedManyWithoutCandidateInput = {
  create?: Prisma.XOR<Prisma.KbsLessonCompletionCreateWithoutCandidateInput, Prisma.KbsLessonCompletionUncheckedCreateWithoutCandidateInput> | Prisma.KbsLessonCompletionCreateWithoutCandidateInput[] | Prisma.KbsLessonCompletionUncheckedCreateWithoutCandidateInput[]
  connectOrCreate?: Prisma.KbsLessonCompletionCreateOrConnectWithoutCandidateInput | Prisma.KbsLessonCompletionCreateOrConnectWithoutCandidateInput[]
  createMany?: Prisma.KbsLessonCompletionCreateManyCandidateInputEnvelope
  connect?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
}

export type KbsLessonCompletionUpdateManyWithoutCandidateNestedInput = {
  create?: Prisma.XOR<Prisma.KbsLessonCompletionCreateWithoutCandidateInput, Prisma.KbsLessonCompletionUncheckedCreateWithoutCandidateInput> | Prisma.KbsLessonCompletionCreateWithoutCandidateInput[] | Prisma.KbsLessonCompletionUncheckedCreateWithoutCandidateInput[]
  connectOrCreate?: Prisma.KbsLessonCompletionCreateOrConnectWithoutCandidateInput | Prisma.KbsLessonCompletionCreateOrConnectWithoutCandidateInput[]
  upsert?: Prisma.KbsLessonCompletionUpsertWithWhereUniqueWithoutCandidateInput | Prisma.KbsLessonCompletionUpsertWithWhereUniqueWithoutCandidateInput[]
  createMany?: Prisma.KbsLessonCompletionCreateManyCandidateInputEnvelope
  set?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  disconnect?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  delete?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  connect?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  update?: Prisma.KbsLessonCompletionUpdateWithWhereUniqueWithoutCandidateInput | Prisma.KbsLessonCompletionUpdateWithWhereUniqueWithoutCandidateInput[]
  updateMany?: Prisma.KbsLessonCompletionUpdateManyWithWhereWithoutCandidateInput | Prisma.KbsLessonCompletionUpdateManyWithWhereWithoutCandidateInput[]
  deleteMany?: Prisma.KbsLessonCompletionScalarWhereInput | Prisma.KbsLessonCompletionScalarWhereInput[]
}

export type KbsLessonCompletionUncheckedUpdateManyWithoutCandidateNestedInput = {
  create?: Prisma.XOR<Prisma.KbsLessonCompletionCreateWithoutCandidateInput, Prisma.KbsLessonCompletionUncheckedCreateWithoutCandidateInput> | Prisma.KbsLessonCompletionCreateWithoutCandidateInput[] | Prisma.KbsLessonCompletionUncheckedCreateWithoutCandidateInput[]
  connectOrCreate?: Prisma.KbsLessonCompletionCreateOrConnectWithoutCandidateInput | Prisma.KbsLessonCompletionCreateOrConnectWithoutCandidateInput[]
  upsert?: Prisma.KbsLessonCompletionUpsertWithWhereUniqueWithoutCandidateInput | Prisma.KbsLessonCompletionUpsertWithWhereUniqueWithoutCandidateInput[]
  createMany?: Prisma.KbsLessonCompletionCreateManyCandidateInputEnvelope
  set?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  disconnect?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  delete?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  connect?: Prisma.KbsLessonCompletionWhereUniqueInput | Prisma.KbsLessonCompletionWhereUniqueInput[]
  update?: Prisma.KbsLessonCompletionUpdateWithWhereUniqueWithoutCandidateInput | Prisma.KbsLessonCompletionUpdateWithWhereUniqueWithoutCandidateInput[]
  updateMany?: Prisma.KbsLessonCompletionUpdateManyWithWhereWithoutCandidateInput | Prisma.KbsLessonCompletionUpdateManyWithWhereWithoutCandidateInput[]
  deleteMany?: Prisma.KbsLessonCompletionScalarWhereInput | Prisma.KbsLessonCompletionScalarWhereInput[]
}

export type KbsLessonCompletionCreateWithoutLessonInput = {
  id?: string
  completedAt?: Date | string
  candidate: Prisma.KbsCandidateCreateNestedOneWithoutLessonCompletionsInput
}

export type KbsLessonCompletionUncheckedCreateWithoutLessonInput = {
  id?: string
  candidateId: string
  completedAt?: Date | string
}

export type KbsLessonCompletionCreateOrConnectWithoutLessonInput = {
  where: Prisma.KbsLessonCompletionWhereUniqueInput
  create: Prisma.XOR<Prisma.KbsLessonCompletionCreateWithoutLessonInput, Prisma.KbsLessonCompletionUncheckedCreateWithoutLessonInput>
}

export type KbsLessonCompletionCreateManyLessonInputEnvelope = {
  data: Prisma.KbsLessonCompletionCreateManyLessonInput | Prisma.KbsLessonCompletionCreateManyLessonInput[]
  skipDuplicates?: boolean
}

export type KbsLessonCompletionUpsertWithWhereUniqueWithoutLessonInput = {
  where: Prisma.KbsLessonCompletionWhereUniqueInput
  update: Prisma.XOR<Prisma.KbsLessonCompletionUpdateWithoutLessonInput, Prisma.KbsLessonCompletionUncheckedUpdateWithoutLessonInput>
  create: Prisma.XOR<Prisma.KbsLessonCompletionCreateWithoutLessonInput, Prisma.KbsLessonCompletionUncheckedCreateWithoutLessonInput>
}

export type KbsLessonCompletionUpdateWithWhereUniqueWithoutLessonInput = {
  where: Prisma.KbsLessonCompletionWhereUniqueInput
  data: Prisma.XOR<Prisma.KbsLessonCompletionUpdateWithoutLessonInput, Prisma.KbsLessonCompletionUncheckedUpdateWithoutLessonInput>
}

export type KbsLessonCompletionUpdateManyWithWhereWithoutLessonInput = {
  where: Prisma.KbsLessonCompletionScalarWhereInput
  data: Prisma.XOR<Prisma.KbsLessonCompletionUpdateManyMutationInput, Prisma.KbsLessonCompletionUncheckedUpdateManyWithoutLessonInput>
}

export type KbsLessonCompletionScalarWhereInput = {
  AND?: Prisma.KbsLessonCompletionScalarWhereInput | Prisma.KbsLessonCompletionScalarWhereInput[]
  OR?: Prisma.KbsLessonCompletionScalarWhereInput[]
  NOT?: Prisma.KbsLessonCompletionScalarWhereInput | Prisma.KbsLessonCompletionScalarWhereInput[]
  id?: Prisma.StringFilter<"KbsLessonCompletion"> | string
  candidateId?: Prisma.StringFilter<"KbsLessonCompletion"> | string
  lessonId?: Prisma.StringFilter<"KbsLessonCompletion"> | string
  completedAt?: Prisma.DateTimeFilter<"KbsLessonCompletion"> | Date | string
}

export type KbsLessonCompletionCreateWithoutCandidateInput = {
  id?: string
  completedAt?: Date | string
  lesson: Prisma.KbsLessonCreateNestedOneWithoutLessonCompletionsInput
}

export type KbsLessonCompletionUncheckedCreateWithoutCandidateInput = {
  id?: string
  lessonId: string
  completedAt?: Date | string
}

export type KbsLessonCompletionCreateOrConnectWithoutCandidateInput = {
  where: Prisma.KbsLessonCompletionWhereUniqueInput
  create: Prisma.XOR<Prisma.KbsLessonCompletionCreateWithoutCandidateInput, Prisma.KbsLessonCompletionUncheckedCreateWithoutCandidateInput>
}

export type KbsLessonCompletionCreateManyCandidateInputEnvelope = {
  data: Prisma.KbsLessonCompletionCreateManyCandidateInput | Prisma.KbsLessonCompletionCreateManyCandidateInput[]
  skipDuplicates?: boolean
}

export type KbsLessonCompletionUpsertWithWhereUniqueWithoutCandidateInput = {
  where: Prisma.KbsLessonCompletionWhereUniqueInput
  update: Prisma.XOR<Prisma.KbsLessonCompletionUpdateWithoutCandidateInput, Prisma.KbsLessonCompletionUncheckedUpdateWithoutCandidateInput>
  create: Prisma.XOR<Prisma.KbsLessonCompletionCreateWithoutCandidateInput, Prisma.KbsLessonCompletionUncheckedCreateWithoutCandidateInput>
}

export type KbsLessonCompletionUpdateWithWhereUniqueWithoutCandidateInput = {
  where: Prisma.KbsLessonCompletionWhereUniqueInput
  data: Prisma.XOR<Prisma.KbsLessonCompletionUpdateWithoutCandidateInput, Prisma.KbsLessonCompletionUncheckedUpdateWithoutCandidateInput>
}

export type KbsLessonCompletionUpdateManyWithWhereWithoutCandidateInput = {
  where: Prisma.KbsLessonCompletionScalarWhereInput
  data: Prisma.XOR<Prisma.KbsLessonCompletionUpdateManyMutationInput, Prisma.KbsLessonCompletionUncheckedUpdateManyWithoutCandidateInput>
}

export type KbsLessonCompletionCreateManyLessonInput = {
  id?: string
  candidateId: string
  completedAt?: Date | string
}

export type KbsLessonCompletionUpdateWithoutLessonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  candidate?: Prisma.KbsCandidateUpdateOneRequiredWithoutLessonCompletionsNestedInput
}

export type KbsLessonCompletionUncheckedUpdateWithoutLessonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  candidateId?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsLessonCompletionUncheckedUpdateManyWithoutLessonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  candidateId?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsLessonCompletionCreateManyCandidateInput = {
  id?: string
  lessonId: string
  completedAt?: Date | string
}

export type KbsLessonCompletionUpdateWithoutCandidateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lesson?: Prisma.KbsLessonUpdateOneRequiredWithoutLessonCompletionsNestedInput
}

export type KbsLessonCompletionUncheckedUpdateWithoutCandidateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsLessonCompletionUncheckedUpdateManyWithoutCandidateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type KbsLessonCompletionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  candidateId?: boolean
  lessonId?: boolean
  completedAt?: boolean
  candidate?: boolean | Prisma.KbsCandidateDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.KbsLessonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kbsLessonCompletion"]>

export type KbsLessonCompletionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  candidateId?: boolean
  lessonId?: boolean
  completedAt?: boolean
  candidate?: boolean | Prisma.KbsCandidateDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.KbsLessonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kbsLessonCompletion"]>

export type KbsLessonCompletionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  candidateId?: boolean
  lessonId?: boolean
  completedAt?: boolean
  candidate?: boolean | Prisma.KbsCandidateDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.KbsLessonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kbsLessonCompletion"]>

export type KbsLessonCompletionSelectScalar = {
  id?: boolean
  candidateId?: boolean
  lessonId?: boolean
  completedAt?: boolean
}

export type KbsLessonCompletionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "candidateId" | "lessonId" | "completedAt", ExtArgs["result"]["kbsLessonCompletion"]>
export type KbsLessonCompletionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  candidate?: boolean | Prisma.KbsCandidateDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.KbsLessonDefaultArgs<ExtArgs>
}
export type KbsLessonCompletionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  candidate?: boolean | Prisma.KbsCandidateDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.KbsLessonDefaultArgs<ExtArgs>
}
export type KbsLessonCompletionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  candidate?: boolean | Prisma.KbsCandidateDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.KbsLessonDefaultArgs<ExtArgs>
}

export type $KbsLessonCompletionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KbsLessonCompletion"
  objects: {
    candidate: Prisma.$KbsCandidatePayload<ExtArgs>
    lesson: Prisma.$KbsLessonPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    candidateId: string
    lessonId: string
    completedAt: Date
  }, ExtArgs["result"]["kbsLessonCompletion"]>
  composites: {}
}

export type KbsLessonCompletionGetPayload<S extends boolean | null | undefined | KbsLessonCompletionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KbsLessonCompletionPayload, S>

export type KbsLessonCompletionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KbsLessonCompletionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KbsLessonCompletionCountAggregateInputType | true
  }

export interface KbsLessonCompletionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KbsLessonCompletion'], meta: { name: 'KbsLessonCompletion' } }
  /**
   * Find zero or one KbsLessonCompletion that matches the filter.
   * @param {KbsLessonCompletionFindUniqueArgs} args - Arguments to find a KbsLessonCompletion
   * @example
   * // Get one KbsLessonCompletion
   * const kbsLessonCompletion = await prisma.kbsLessonCompletion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KbsLessonCompletionFindUniqueArgs>(args: Prisma.SelectSubset<T, KbsLessonCompletionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KbsLessonCompletionClient<runtime.Types.Result.GetResult<Prisma.$KbsLessonCompletionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KbsLessonCompletion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KbsLessonCompletionFindUniqueOrThrowArgs} args - Arguments to find a KbsLessonCompletion
   * @example
   * // Get one KbsLessonCompletion
   * const kbsLessonCompletion = await prisma.kbsLessonCompletion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KbsLessonCompletionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KbsLessonCompletionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KbsLessonCompletionClient<runtime.Types.Result.GetResult<Prisma.$KbsLessonCompletionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KbsLessonCompletion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsLessonCompletionFindFirstArgs} args - Arguments to find a KbsLessonCompletion
   * @example
   * // Get one KbsLessonCompletion
   * const kbsLessonCompletion = await prisma.kbsLessonCompletion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KbsLessonCompletionFindFirstArgs>(args?: Prisma.SelectSubset<T, KbsLessonCompletionFindFirstArgs<ExtArgs>>): Prisma.Prisma__KbsLessonCompletionClient<runtime.Types.Result.GetResult<Prisma.$KbsLessonCompletionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KbsLessonCompletion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsLessonCompletionFindFirstOrThrowArgs} args - Arguments to find a KbsLessonCompletion
   * @example
   * // Get one KbsLessonCompletion
   * const kbsLessonCompletion = await prisma.kbsLessonCompletion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KbsLessonCompletionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KbsLessonCompletionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KbsLessonCompletionClient<runtime.Types.Result.GetResult<Prisma.$KbsLessonCompletionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KbsLessonCompletions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsLessonCompletionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KbsLessonCompletions
   * const kbsLessonCompletions = await prisma.kbsLessonCompletion.findMany()
   * 
   * // Get first 10 KbsLessonCompletions
   * const kbsLessonCompletions = await prisma.kbsLessonCompletion.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kbsLessonCompletionWithIdOnly = await prisma.kbsLessonCompletion.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KbsLessonCompletionFindManyArgs>(args?: Prisma.SelectSubset<T, KbsLessonCompletionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsLessonCompletionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a KbsLessonCompletion.
   * @param {KbsLessonCompletionCreateArgs} args - Arguments to create a KbsLessonCompletion.
   * @example
   * // Create one KbsLessonCompletion
   * const KbsLessonCompletion = await prisma.kbsLessonCompletion.create({
   *   data: {
   *     // ... data to create a KbsLessonCompletion
   *   }
   * })
   * 
   */
  create<T extends KbsLessonCompletionCreateArgs>(args: Prisma.SelectSubset<T, KbsLessonCompletionCreateArgs<ExtArgs>>): Prisma.Prisma__KbsLessonCompletionClient<runtime.Types.Result.GetResult<Prisma.$KbsLessonCompletionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many KbsLessonCompletions.
   * @param {KbsLessonCompletionCreateManyArgs} args - Arguments to create many KbsLessonCompletions.
   * @example
   * // Create many KbsLessonCompletions
   * const kbsLessonCompletion = await prisma.kbsLessonCompletion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KbsLessonCompletionCreateManyArgs>(args?: Prisma.SelectSubset<T, KbsLessonCompletionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many KbsLessonCompletions and returns the data saved in the database.
   * @param {KbsLessonCompletionCreateManyAndReturnArgs} args - Arguments to create many KbsLessonCompletions.
   * @example
   * // Create many KbsLessonCompletions
   * const kbsLessonCompletion = await prisma.kbsLessonCompletion.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many KbsLessonCompletions and only return the `id`
   * const kbsLessonCompletionWithIdOnly = await prisma.kbsLessonCompletion.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KbsLessonCompletionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KbsLessonCompletionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsLessonCompletionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a KbsLessonCompletion.
   * @param {KbsLessonCompletionDeleteArgs} args - Arguments to delete one KbsLessonCompletion.
   * @example
   * // Delete one KbsLessonCompletion
   * const KbsLessonCompletion = await prisma.kbsLessonCompletion.delete({
   *   where: {
   *     // ... filter to delete one KbsLessonCompletion
   *   }
   * })
   * 
   */
  delete<T extends KbsLessonCompletionDeleteArgs>(args: Prisma.SelectSubset<T, KbsLessonCompletionDeleteArgs<ExtArgs>>): Prisma.Prisma__KbsLessonCompletionClient<runtime.Types.Result.GetResult<Prisma.$KbsLessonCompletionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KbsLessonCompletion.
   * @param {KbsLessonCompletionUpdateArgs} args - Arguments to update one KbsLessonCompletion.
   * @example
   * // Update one KbsLessonCompletion
   * const kbsLessonCompletion = await prisma.kbsLessonCompletion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KbsLessonCompletionUpdateArgs>(args: Prisma.SelectSubset<T, KbsLessonCompletionUpdateArgs<ExtArgs>>): Prisma.Prisma__KbsLessonCompletionClient<runtime.Types.Result.GetResult<Prisma.$KbsLessonCompletionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KbsLessonCompletions.
   * @param {KbsLessonCompletionDeleteManyArgs} args - Arguments to filter KbsLessonCompletions to delete.
   * @example
   * // Delete a few KbsLessonCompletions
   * const { count } = await prisma.kbsLessonCompletion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KbsLessonCompletionDeleteManyArgs>(args?: Prisma.SelectSubset<T, KbsLessonCompletionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KbsLessonCompletions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsLessonCompletionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KbsLessonCompletions
   * const kbsLessonCompletion = await prisma.kbsLessonCompletion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KbsLessonCompletionUpdateManyArgs>(args: Prisma.SelectSubset<T, KbsLessonCompletionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KbsLessonCompletions and returns the data updated in the database.
   * @param {KbsLessonCompletionUpdateManyAndReturnArgs} args - Arguments to update many KbsLessonCompletions.
   * @example
   * // Update many KbsLessonCompletions
   * const kbsLessonCompletion = await prisma.kbsLessonCompletion.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more KbsLessonCompletions and only return the `id`
   * const kbsLessonCompletionWithIdOnly = await prisma.kbsLessonCompletion.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KbsLessonCompletionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KbsLessonCompletionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsLessonCompletionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one KbsLessonCompletion.
   * @param {KbsLessonCompletionUpsertArgs} args - Arguments to update or create a KbsLessonCompletion.
   * @example
   * // Update or create a KbsLessonCompletion
   * const kbsLessonCompletion = await prisma.kbsLessonCompletion.upsert({
   *   create: {
   *     // ... data to create a KbsLessonCompletion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the KbsLessonCompletion we want to update
   *   }
   * })
   */
  upsert<T extends KbsLessonCompletionUpsertArgs>(args: Prisma.SelectSubset<T, KbsLessonCompletionUpsertArgs<ExtArgs>>): Prisma.Prisma__KbsLessonCompletionClient<runtime.Types.Result.GetResult<Prisma.$KbsLessonCompletionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of KbsLessonCompletions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsLessonCompletionCountArgs} args - Arguments to filter KbsLessonCompletions to count.
   * @example
   * // Count the number of KbsLessonCompletions
   * const count = await prisma.kbsLessonCompletion.count({
   *   where: {
   *     // ... the filter for the KbsLessonCompletions we want to count
   *   }
   * })
  **/
  count<T extends KbsLessonCompletionCountArgs>(
    args?: Prisma.Subset<T, KbsLessonCompletionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KbsLessonCompletionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KbsLessonCompletion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsLessonCompletionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KbsLessonCompletionAggregateArgs>(args: Prisma.Subset<T, KbsLessonCompletionAggregateArgs>): Prisma.PrismaPromise<GetKbsLessonCompletionAggregateType<T>>

  /**
   * Group by KbsLessonCompletion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsLessonCompletionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KbsLessonCompletionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KbsLessonCompletionGroupByArgs['orderBy'] }
      : { orderBy?: KbsLessonCompletionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KbsLessonCompletionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKbsLessonCompletionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KbsLessonCompletion model
 */
readonly fields: KbsLessonCompletionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KbsLessonCompletion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KbsLessonCompletionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  candidate<T extends Prisma.KbsCandidateDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KbsCandidateDefaultArgs<ExtArgs>>): Prisma.Prisma__KbsCandidateClient<runtime.Types.Result.GetResult<Prisma.$KbsCandidatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  lesson<T extends Prisma.KbsLessonDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KbsLessonDefaultArgs<ExtArgs>>): Prisma.Prisma__KbsLessonClient<runtime.Types.Result.GetResult<Prisma.$KbsLessonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KbsLessonCompletion model
 */
export interface KbsLessonCompletionFieldRefs {
  readonly id: Prisma.FieldRef<"KbsLessonCompletion", 'String'>
  readonly candidateId: Prisma.FieldRef<"KbsLessonCompletion", 'String'>
  readonly lessonId: Prisma.FieldRef<"KbsLessonCompletion", 'String'>
  readonly completedAt: Prisma.FieldRef<"KbsLessonCompletion", 'DateTime'>
}
    

// Custom InputTypes
/**
 * KbsLessonCompletion findUnique
 */
export type KbsLessonCompletionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsLessonCompletion
   */
  select?: Prisma.KbsLessonCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsLessonCompletion
   */
  omit?: Prisma.KbsLessonCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsLessonCompletionInclude<ExtArgs> | null
  /**
   * Filter, which KbsLessonCompletion to fetch.
   */
  where: Prisma.KbsLessonCompletionWhereUniqueInput
}

/**
 * KbsLessonCompletion findUniqueOrThrow
 */
export type KbsLessonCompletionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsLessonCompletion
   */
  select?: Prisma.KbsLessonCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsLessonCompletion
   */
  omit?: Prisma.KbsLessonCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsLessonCompletionInclude<ExtArgs> | null
  /**
   * Filter, which KbsLessonCompletion to fetch.
   */
  where: Prisma.KbsLessonCompletionWhereUniqueInput
}

/**
 * KbsLessonCompletion findFirst
 */
export type KbsLessonCompletionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsLessonCompletion
   */
  select?: Prisma.KbsLessonCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsLessonCompletion
   */
  omit?: Prisma.KbsLessonCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsLessonCompletionInclude<ExtArgs> | null
  /**
   * Filter, which KbsLessonCompletion to fetch.
   */
  where?: Prisma.KbsLessonCompletionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsLessonCompletions to fetch.
   */
  orderBy?: Prisma.KbsLessonCompletionOrderByWithRelationInput | Prisma.KbsLessonCompletionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KbsLessonCompletions.
   */
  cursor?: Prisma.KbsLessonCompletionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsLessonCompletions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsLessonCompletions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KbsLessonCompletions.
   */
  distinct?: Prisma.KbsLessonCompletionScalarFieldEnum | Prisma.KbsLessonCompletionScalarFieldEnum[]
}

/**
 * KbsLessonCompletion findFirstOrThrow
 */
export type KbsLessonCompletionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsLessonCompletion
   */
  select?: Prisma.KbsLessonCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsLessonCompletion
   */
  omit?: Prisma.KbsLessonCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsLessonCompletionInclude<ExtArgs> | null
  /**
   * Filter, which KbsLessonCompletion to fetch.
   */
  where?: Prisma.KbsLessonCompletionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsLessonCompletions to fetch.
   */
  orderBy?: Prisma.KbsLessonCompletionOrderByWithRelationInput | Prisma.KbsLessonCompletionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KbsLessonCompletions.
   */
  cursor?: Prisma.KbsLessonCompletionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsLessonCompletions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsLessonCompletions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KbsLessonCompletions.
   */
  distinct?: Prisma.KbsLessonCompletionScalarFieldEnum | Prisma.KbsLessonCompletionScalarFieldEnum[]
}

/**
 * KbsLessonCompletion findMany
 */
export type KbsLessonCompletionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsLessonCompletion
   */
  select?: Prisma.KbsLessonCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsLessonCompletion
   */
  omit?: Prisma.KbsLessonCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsLessonCompletionInclude<ExtArgs> | null
  /**
   * Filter, which KbsLessonCompletions to fetch.
   */
  where?: Prisma.KbsLessonCompletionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsLessonCompletions to fetch.
   */
  orderBy?: Prisma.KbsLessonCompletionOrderByWithRelationInput | Prisma.KbsLessonCompletionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KbsLessonCompletions.
   */
  cursor?: Prisma.KbsLessonCompletionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsLessonCompletions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsLessonCompletions.
   */
  skip?: number
  distinct?: Prisma.KbsLessonCompletionScalarFieldEnum | Prisma.KbsLessonCompletionScalarFieldEnum[]
}

/**
 * KbsLessonCompletion create
 */
export type KbsLessonCompletionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsLessonCompletion
   */
  select?: Prisma.KbsLessonCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsLessonCompletion
   */
  omit?: Prisma.KbsLessonCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsLessonCompletionInclude<ExtArgs> | null
  /**
   * The data needed to create a KbsLessonCompletion.
   */
  data: Prisma.XOR<Prisma.KbsLessonCompletionCreateInput, Prisma.KbsLessonCompletionUncheckedCreateInput>
}

/**
 * KbsLessonCompletion createMany
 */
export type KbsLessonCompletionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many KbsLessonCompletions.
   */
  data: Prisma.KbsLessonCompletionCreateManyInput | Prisma.KbsLessonCompletionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KbsLessonCompletion createManyAndReturn
 */
export type KbsLessonCompletionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsLessonCompletion
   */
  select?: Prisma.KbsLessonCompletionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KbsLessonCompletion
   */
  omit?: Prisma.KbsLessonCompletionOmit<ExtArgs> | null
  /**
   * The data used to create many KbsLessonCompletions.
   */
  data: Prisma.KbsLessonCompletionCreateManyInput | Prisma.KbsLessonCompletionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsLessonCompletionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * KbsLessonCompletion update
 */
export type KbsLessonCompletionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsLessonCompletion
   */
  select?: Prisma.KbsLessonCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsLessonCompletion
   */
  omit?: Prisma.KbsLessonCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsLessonCompletionInclude<ExtArgs> | null
  /**
   * The data needed to update a KbsLessonCompletion.
   */
  data: Prisma.XOR<Prisma.KbsLessonCompletionUpdateInput, Prisma.KbsLessonCompletionUncheckedUpdateInput>
  /**
   * Choose, which KbsLessonCompletion to update.
   */
  where: Prisma.KbsLessonCompletionWhereUniqueInput
}

/**
 * KbsLessonCompletion updateMany
 */
export type KbsLessonCompletionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KbsLessonCompletions.
   */
  data: Prisma.XOR<Prisma.KbsLessonCompletionUpdateManyMutationInput, Prisma.KbsLessonCompletionUncheckedUpdateManyInput>
  /**
   * Filter which KbsLessonCompletions to update
   */
  where?: Prisma.KbsLessonCompletionWhereInput
  /**
   * Limit how many KbsLessonCompletions to update.
   */
  limit?: number
}

/**
 * KbsLessonCompletion updateManyAndReturn
 */
export type KbsLessonCompletionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsLessonCompletion
   */
  select?: Prisma.KbsLessonCompletionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KbsLessonCompletion
   */
  omit?: Prisma.KbsLessonCompletionOmit<ExtArgs> | null
  /**
   * The data used to update KbsLessonCompletions.
   */
  data: Prisma.XOR<Prisma.KbsLessonCompletionUpdateManyMutationInput, Prisma.KbsLessonCompletionUncheckedUpdateManyInput>
  /**
   * Filter which KbsLessonCompletions to update
   */
  where?: Prisma.KbsLessonCompletionWhereInput
  /**
   * Limit how many KbsLessonCompletions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsLessonCompletionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * KbsLessonCompletion upsert
 */
export type KbsLessonCompletionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsLessonCompletion
   */
  select?: Prisma.KbsLessonCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsLessonCompletion
   */
  omit?: Prisma.KbsLessonCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsLessonCompletionInclude<ExtArgs> | null
  /**
   * The filter to search for the KbsLessonCompletion to update in case it exists.
   */
  where: Prisma.KbsLessonCompletionWhereUniqueInput
  /**
   * In case the KbsLessonCompletion found by the `where` argument doesn't exist, create a new KbsLessonCompletion with this data.
   */
  create: Prisma.XOR<Prisma.KbsLessonCompletionCreateInput, Prisma.KbsLessonCompletionUncheckedCreateInput>
  /**
   * In case the KbsLessonCompletion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KbsLessonCompletionUpdateInput, Prisma.KbsLessonCompletionUncheckedUpdateInput>
}

/**
 * KbsLessonCompletion delete
 */
export type KbsLessonCompletionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsLessonCompletion
   */
  select?: Prisma.KbsLessonCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsLessonCompletion
   */
  omit?: Prisma.KbsLessonCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsLessonCompletionInclude<ExtArgs> | null
  /**
   * Filter which KbsLessonCompletion to delete.
   */
  where: Prisma.KbsLessonCompletionWhereUniqueInput
}

/**
 * KbsLessonCompletion deleteMany
 */
export type KbsLessonCompletionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KbsLessonCompletions to delete
   */
  where?: Prisma.KbsLessonCompletionWhereInput
  /**
   * Limit how many KbsLessonCompletions to delete.
   */
  limit?: number
}

/**
 * KbsLessonCompletion without action
 */
export type KbsLessonCompletionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsLessonCompletion
   */
  select?: Prisma.KbsLessonCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsLessonCompletion
   */
  omit?: Prisma.KbsLessonCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsLessonCompletionInclude<ExtArgs> | null
}
