
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `KbsQuestion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model KbsQuestion
 * 
 */
export type KbsQuestionModel = runtime.Types.Result.DefaultSelection<Prisma.$KbsQuestionPayload>

export type AggregateKbsQuestion = {
  _count: KbsQuestionCountAggregateOutputType | null
  _min: KbsQuestionMinAggregateOutputType | null
  _max: KbsQuestionMaxAggregateOutputType | null
}

export type KbsQuestionMinAggregateOutputType = {
  id: string | null
  moduleId: string | null
  text: string | null
  type: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type KbsQuestionMaxAggregateOutputType = {
  id: string | null
  moduleId: string | null
  text: string | null
  type: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type KbsQuestionCountAggregateOutputType = {
  id: number
  moduleId: number
  text: number
  type: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type KbsQuestionMinAggregateInputType = {
  id?: true
  moduleId?: true
  text?: true
  type?: true
  createdAt?: true
  updatedAt?: true
}

export type KbsQuestionMaxAggregateInputType = {
  id?: true
  moduleId?: true
  text?: true
  type?: true
  createdAt?: true
  updatedAt?: true
}

export type KbsQuestionCountAggregateInputType = {
  id?: true
  moduleId?: true
  text?: true
  type?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type KbsQuestionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KbsQuestion to aggregate.
   */
  where?: Prisma.KbsQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsQuestions to fetch.
   */
  orderBy?: Prisma.KbsQuestionOrderByWithRelationInput | Prisma.KbsQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KbsQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KbsQuestions
  **/
  _count?: true | KbsQuestionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KbsQuestionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KbsQuestionMaxAggregateInputType
}

export type GetKbsQuestionAggregateType<T extends KbsQuestionAggregateArgs> = {
      [P in keyof T & keyof AggregateKbsQuestion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKbsQuestion[P]>
    : Prisma.GetScalarType<T[P], AggregateKbsQuestion[P]>
}




export type KbsQuestionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KbsQuestionWhereInput
  orderBy?: Prisma.KbsQuestionOrderByWithAggregationInput | Prisma.KbsQuestionOrderByWithAggregationInput[]
  by: Prisma.KbsQuestionScalarFieldEnum[] | Prisma.KbsQuestionScalarFieldEnum
  having?: Prisma.KbsQuestionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KbsQuestionCountAggregateInputType | true
  _min?: KbsQuestionMinAggregateInputType
  _max?: KbsQuestionMaxAggregateInputType
}

export type KbsQuestionGroupByOutputType = {
  id: string
  moduleId: string
  text: string
  type: string
  createdAt: Date
  updatedAt: Date
  _count: KbsQuestionCountAggregateOutputType | null
  _min: KbsQuestionMinAggregateOutputType | null
  _max: KbsQuestionMaxAggregateOutputType | null
}

type GetKbsQuestionGroupByPayload<T extends KbsQuestionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KbsQuestionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KbsQuestionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KbsQuestionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KbsQuestionGroupByOutputType[P]>
      }
    >
  >



export type KbsQuestionWhereInput = {
  AND?: Prisma.KbsQuestionWhereInput | Prisma.KbsQuestionWhereInput[]
  OR?: Prisma.KbsQuestionWhereInput[]
  NOT?: Prisma.KbsQuestionWhereInput | Prisma.KbsQuestionWhereInput[]
  id?: Prisma.StringFilter<"KbsQuestion"> | string
  moduleId?: Prisma.StringFilter<"KbsQuestion"> | string
  text?: Prisma.StringFilter<"KbsQuestion"> | string
  type?: Prisma.StringFilter<"KbsQuestion"> | string
  createdAt?: Prisma.DateTimeFilter<"KbsQuestion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KbsQuestion"> | Date | string
  module?: Prisma.XOR<Prisma.KbsModuleScalarRelationFilter, Prisma.KbsModuleWhereInput>
  answers?: Prisma.KbsAnswerListRelationFilter
}

export type KbsQuestionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  module?: Prisma.KbsModuleOrderByWithRelationInput
  answers?: Prisma.KbsAnswerOrderByRelationAggregateInput
}

export type KbsQuestionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.KbsQuestionWhereInput | Prisma.KbsQuestionWhereInput[]
  OR?: Prisma.KbsQuestionWhereInput[]
  NOT?: Prisma.KbsQuestionWhereInput | Prisma.KbsQuestionWhereInput[]
  moduleId?: Prisma.StringFilter<"KbsQuestion"> | string
  text?: Prisma.StringFilter<"KbsQuestion"> | string
  type?: Prisma.StringFilter<"KbsQuestion"> | string
  createdAt?: Prisma.DateTimeFilter<"KbsQuestion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KbsQuestion"> | Date | string
  module?: Prisma.XOR<Prisma.KbsModuleScalarRelationFilter, Prisma.KbsModuleWhereInput>
  answers?: Prisma.KbsAnswerListRelationFilter
}, "id">

export type KbsQuestionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.KbsQuestionCountOrderByAggregateInput
  _max?: Prisma.KbsQuestionMaxOrderByAggregateInput
  _min?: Prisma.KbsQuestionMinOrderByAggregateInput
}

export type KbsQuestionScalarWhereWithAggregatesInput = {
  AND?: Prisma.KbsQuestionScalarWhereWithAggregatesInput | Prisma.KbsQuestionScalarWhereWithAggregatesInput[]
  OR?: Prisma.KbsQuestionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KbsQuestionScalarWhereWithAggregatesInput | Prisma.KbsQuestionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"KbsQuestion"> | string
  moduleId?: Prisma.StringWithAggregatesFilter<"KbsQuestion"> | string
  text?: Prisma.StringWithAggregatesFilter<"KbsQuestion"> | string
  type?: Prisma.StringWithAggregatesFilter<"KbsQuestion"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"KbsQuestion"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"KbsQuestion"> | Date | string
}

export type KbsQuestionCreateInput = {
  id?: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  module: Prisma.KbsModuleCreateNestedOneWithoutQuestionsInput
  answers?: Prisma.KbsAnswerCreateNestedManyWithoutQuestionInput
}

export type KbsQuestionUncheckedCreateInput = {
  id?: string
  moduleId: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  answers?: Prisma.KbsAnswerUncheckedCreateNestedManyWithoutQuestionInput
}

export type KbsQuestionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  module?: Prisma.KbsModuleUpdateOneRequiredWithoutQuestionsNestedInput
  answers?: Prisma.KbsAnswerUpdateManyWithoutQuestionNestedInput
}

export type KbsQuestionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  moduleId?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.KbsAnswerUncheckedUpdateManyWithoutQuestionNestedInput
}

export type KbsQuestionCreateManyInput = {
  id?: string
  moduleId: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KbsQuestionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsQuestionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  moduleId?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsQuestionListRelationFilter = {
  every?: Prisma.KbsQuestionWhereInput
  some?: Prisma.KbsQuestionWhereInput
  none?: Prisma.KbsQuestionWhereInput
}

export type KbsQuestionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type KbsQuestionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KbsQuestionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KbsQuestionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  text?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KbsQuestionScalarRelationFilter = {
  is?: Prisma.KbsQuestionWhereInput
  isNot?: Prisma.KbsQuestionWhereInput
}

export type KbsQuestionCreateNestedManyWithoutModuleInput = {
  create?: Prisma.XOR<Prisma.KbsQuestionCreateWithoutModuleInput, Prisma.KbsQuestionUncheckedCreateWithoutModuleInput> | Prisma.KbsQuestionCreateWithoutModuleInput[] | Prisma.KbsQuestionUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.KbsQuestionCreateOrConnectWithoutModuleInput | Prisma.KbsQuestionCreateOrConnectWithoutModuleInput[]
  createMany?: Prisma.KbsQuestionCreateManyModuleInputEnvelope
  connect?: Prisma.KbsQuestionWhereUniqueInput | Prisma.KbsQuestionWhereUniqueInput[]
}

export type KbsQuestionUncheckedCreateNestedManyWithoutModuleInput = {
  create?: Prisma.XOR<Prisma.KbsQuestionCreateWithoutModuleInput, Prisma.KbsQuestionUncheckedCreateWithoutModuleInput> | Prisma.KbsQuestionCreateWithoutModuleInput[] | Prisma.KbsQuestionUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.KbsQuestionCreateOrConnectWithoutModuleInput | Prisma.KbsQuestionCreateOrConnectWithoutModuleInput[]
  createMany?: Prisma.KbsQuestionCreateManyModuleInputEnvelope
  connect?: Prisma.KbsQuestionWhereUniqueInput | Prisma.KbsQuestionWhereUniqueInput[]
}

export type KbsQuestionUpdateManyWithoutModuleNestedInput = {
  create?: Prisma.XOR<Prisma.KbsQuestionCreateWithoutModuleInput, Prisma.KbsQuestionUncheckedCreateWithoutModuleInput> | Prisma.KbsQuestionCreateWithoutModuleInput[] | Prisma.KbsQuestionUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.KbsQuestionCreateOrConnectWithoutModuleInput | Prisma.KbsQuestionCreateOrConnectWithoutModuleInput[]
  upsert?: Prisma.KbsQuestionUpsertWithWhereUniqueWithoutModuleInput | Prisma.KbsQuestionUpsertWithWhereUniqueWithoutModuleInput[]
  createMany?: Prisma.KbsQuestionCreateManyModuleInputEnvelope
  set?: Prisma.KbsQuestionWhereUniqueInput | Prisma.KbsQuestionWhereUniqueInput[]
  disconnect?: Prisma.KbsQuestionWhereUniqueInput | Prisma.KbsQuestionWhereUniqueInput[]
  delete?: Prisma.KbsQuestionWhereUniqueInput | Prisma.KbsQuestionWhereUniqueInput[]
  connect?: Prisma.KbsQuestionWhereUniqueInput | Prisma.KbsQuestionWhereUniqueInput[]
  update?: Prisma.KbsQuestionUpdateWithWhereUniqueWithoutModuleInput | Prisma.KbsQuestionUpdateWithWhereUniqueWithoutModuleInput[]
  updateMany?: Prisma.KbsQuestionUpdateManyWithWhereWithoutModuleInput | Prisma.KbsQuestionUpdateManyWithWhereWithoutModuleInput[]
  deleteMany?: Prisma.KbsQuestionScalarWhereInput | Prisma.KbsQuestionScalarWhereInput[]
}

export type KbsQuestionUncheckedUpdateManyWithoutModuleNestedInput = {
  create?: Prisma.XOR<Prisma.KbsQuestionCreateWithoutModuleInput, Prisma.KbsQuestionUncheckedCreateWithoutModuleInput> | Prisma.KbsQuestionCreateWithoutModuleInput[] | Prisma.KbsQuestionUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.KbsQuestionCreateOrConnectWithoutModuleInput | Prisma.KbsQuestionCreateOrConnectWithoutModuleInput[]
  upsert?: Prisma.KbsQuestionUpsertWithWhereUniqueWithoutModuleInput | Prisma.KbsQuestionUpsertWithWhereUniqueWithoutModuleInput[]
  createMany?: Prisma.KbsQuestionCreateManyModuleInputEnvelope
  set?: Prisma.KbsQuestionWhereUniqueInput | Prisma.KbsQuestionWhereUniqueInput[]
  disconnect?: Prisma.KbsQuestionWhereUniqueInput | Prisma.KbsQuestionWhereUniqueInput[]
  delete?: Prisma.KbsQuestionWhereUniqueInput | Prisma.KbsQuestionWhereUniqueInput[]
  connect?: Prisma.KbsQuestionWhereUniqueInput | Prisma.KbsQuestionWhereUniqueInput[]
  update?: Prisma.KbsQuestionUpdateWithWhereUniqueWithoutModuleInput | Prisma.KbsQuestionUpdateWithWhereUniqueWithoutModuleInput[]
  updateMany?: Prisma.KbsQuestionUpdateManyWithWhereWithoutModuleInput | Prisma.KbsQuestionUpdateManyWithWhereWithoutModuleInput[]
  deleteMany?: Prisma.KbsQuestionScalarWhereInput | Prisma.KbsQuestionScalarWhereInput[]
}

export type KbsQuestionCreateNestedOneWithoutAnswersInput = {
  create?: Prisma.XOR<Prisma.KbsQuestionCreateWithoutAnswersInput, Prisma.KbsQuestionUncheckedCreateWithoutAnswersInput>
  connectOrCreate?: Prisma.KbsQuestionCreateOrConnectWithoutAnswersInput
  connect?: Prisma.KbsQuestionWhereUniqueInput
}

export type KbsQuestionUpdateOneRequiredWithoutAnswersNestedInput = {
  create?: Prisma.XOR<Prisma.KbsQuestionCreateWithoutAnswersInput, Prisma.KbsQuestionUncheckedCreateWithoutAnswersInput>
  connectOrCreate?: Prisma.KbsQuestionCreateOrConnectWithoutAnswersInput
  upsert?: Prisma.KbsQuestionUpsertWithoutAnswersInput
  connect?: Prisma.KbsQuestionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.KbsQuestionUpdateToOneWithWhereWithoutAnswersInput, Prisma.KbsQuestionUpdateWithoutAnswersInput>, Prisma.KbsQuestionUncheckedUpdateWithoutAnswersInput>
}

export type KbsQuestionCreateWithoutModuleInput = {
  id?: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  answers?: Prisma.KbsAnswerCreateNestedManyWithoutQuestionInput
}

export type KbsQuestionUncheckedCreateWithoutModuleInput = {
  id?: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  answers?: Prisma.KbsAnswerUncheckedCreateNestedManyWithoutQuestionInput
}

export type KbsQuestionCreateOrConnectWithoutModuleInput = {
  where: Prisma.KbsQuestionWhereUniqueInput
  create: Prisma.XOR<Prisma.KbsQuestionCreateWithoutModuleInput, Prisma.KbsQuestionUncheckedCreateWithoutModuleInput>
}

export type KbsQuestionCreateManyModuleInputEnvelope = {
  data: Prisma.KbsQuestionCreateManyModuleInput | Prisma.KbsQuestionCreateManyModuleInput[]
  skipDuplicates?: boolean
}

export type KbsQuestionUpsertWithWhereUniqueWithoutModuleInput = {
  where: Prisma.KbsQuestionWhereUniqueInput
  update: Prisma.XOR<Prisma.KbsQuestionUpdateWithoutModuleInput, Prisma.KbsQuestionUncheckedUpdateWithoutModuleInput>
  create: Prisma.XOR<Prisma.KbsQuestionCreateWithoutModuleInput, Prisma.KbsQuestionUncheckedCreateWithoutModuleInput>
}

export type KbsQuestionUpdateWithWhereUniqueWithoutModuleInput = {
  where: Prisma.KbsQuestionWhereUniqueInput
  data: Prisma.XOR<Prisma.KbsQuestionUpdateWithoutModuleInput, Prisma.KbsQuestionUncheckedUpdateWithoutModuleInput>
}

export type KbsQuestionUpdateManyWithWhereWithoutModuleInput = {
  where: Prisma.KbsQuestionScalarWhereInput
  data: Prisma.XOR<Prisma.KbsQuestionUpdateManyMutationInput, Prisma.KbsQuestionUncheckedUpdateManyWithoutModuleInput>
}

export type KbsQuestionScalarWhereInput = {
  AND?: Prisma.KbsQuestionScalarWhereInput | Prisma.KbsQuestionScalarWhereInput[]
  OR?: Prisma.KbsQuestionScalarWhereInput[]
  NOT?: Prisma.KbsQuestionScalarWhereInput | Prisma.KbsQuestionScalarWhereInput[]
  id?: Prisma.StringFilter<"KbsQuestion"> | string
  moduleId?: Prisma.StringFilter<"KbsQuestion"> | string
  text?: Prisma.StringFilter<"KbsQuestion"> | string
  type?: Prisma.StringFilter<"KbsQuestion"> | string
  createdAt?: Prisma.DateTimeFilter<"KbsQuestion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KbsQuestion"> | Date | string
}

export type KbsQuestionCreateWithoutAnswersInput = {
  id?: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
  module: Prisma.KbsModuleCreateNestedOneWithoutQuestionsInput
}

export type KbsQuestionUncheckedCreateWithoutAnswersInput = {
  id?: string
  moduleId: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KbsQuestionCreateOrConnectWithoutAnswersInput = {
  where: Prisma.KbsQuestionWhereUniqueInput
  create: Prisma.XOR<Prisma.KbsQuestionCreateWithoutAnswersInput, Prisma.KbsQuestionUncheckedCreateWithoutAnswersInput>
}

export type KbsQuestionUpsertWithoutAnswersInput = {
  update: Prisma.XOR<Prisma.KbsQuestionUpdateWithoutAnswersInput, Prisma.KbsQuestionUncheckedUpdateWithoutAnswersInput>
  create: Prisma.XOR<Prisma.KbsQuestionCreateWithoutAnswersInput, Prisma.KbsQuestionUncheckedCreateWithoutAnswersInput>
  where?: Prisma.KbsQuestionWhereInput
}

export type KbsQuestionUpdateToOneWithWhereWithoutAnswersInput = {
  where?: Prisma.KbsQuestionWhereInput
  data: Prisma.XOR<Prisma.KbsQuestionUpdateWithoutAnswersInput, Prisma.KbsQuestionUncheckedUpdateWithoutAnswersInput>
}

export type KbsQuestionUpdateWithoutAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  module?: Prisma.KbsModuleUpdateOneRequiredWithoutQuestionsNestedInput
}

export type KbsQuestionUncheckedUpdateWithoutAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  moduleId?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KbsQuestionCreateManyModuleInput = {
  id?: string
  text: string
  type: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KbsQuestionUpdateWithoutModuleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.KbsAnswerUpdateManyWithoutQuestionNestedInput
}

export type KbsQuestionUncheckedUpdateWithoutModuleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.KbsAnswerUncheckedUpdateManyWithoutQuestionNestedInput
}

export type KbsQuestionUncheckedUpdateManyWithoutModuleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type KbsQuestionCountOutputType
 */

export type KbsQuestionCountOutputType = {
  answers: number
}

export type KbsQuestionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  answers?: boolean | KbsQuestionCountOutputTypeCountAnswersArgs
}

/**
 * KbsQuestionCountOutputType without action
 */
export type KbsQuestionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestionCountOutputType
   */
  select?: Prisma.KbsQuestionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * KbsQuestionCountOutputType without action
 */
export type KbsQuestionCountOutputTypeCountAnswersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KbsAnswerWhereInput
}


export type KbsQuestionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  moduleId?: boolean
  text?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  module?: boolean | Prisma.KbsModuleDefaultArgs<ExtArgs>
  answers?: boolean | Prisma.KbsQuestion$answersArgs<ExtArgs>
  _count?: boolean | Prisma.KbsQuestionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kbsQuestion"]>

export type KbsQuestionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  moduleId?: boolean
  text?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  module?: boolean | Prisma.KbsModuleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kbsQuestion"]>

export type KbsQuestionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  moduleId?: boolean
  text?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  module?: boolean | Prisma.KbsModuleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kbsQuestion"]>

export type KbsQuestionSelectScalar = {
  id?: boolean
  moduleId?: boolean
  text?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type KbsQuestionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "moduleId" | "text" | "type" | "createdAt" | "updatedAt", ExtArgs["result"]["kbsQuestion"]>
export type KbsQuestionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  module?: boolean | Prisma.KbsModuleDefaultArgs<ExtArgs>
  answers?: boolean | Prisma.KbsQuestion$answersArgs<ExtArgs>
  _count?: boolean | Prisma.KbsQuestionCountOutputTypeDefaultArgs<ExtArgs>
}
export type KbsQuestionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  module?: boolean | Prisma.KbsModuleDefaultArgs<ExtArgs>
}
export type KbsQuestionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  module?: boolean | Prisma.KbsModuleDefaultArgs<ExtArgs>
}

export type $KbsQuestionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KbsQuestion"
  objects: {
    module: Prisma.$KbsModulePayload<ExtArgs>
    answers: Prisma.$KbsAnswerPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    moduleId: string
    text: string
    type: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["kbsQuestion"]>
  composites: {}
}

export type KbsQuestionGetPayload<S extends boolean | null | undefined | KbsQuestionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KbsQuestionPayload, S>

export type KbsQuestionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KbsQuestionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KbsQuestionCountAggregateInputType | true
  }

export interface KbsQuestionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KbsQuestion'], meta: { name: 'KbsQuestion' } }
  /**
   * Find zero or one KbsQuestion that matches the filter.
   * @param {KbsQuestionFindUniqueArgs} args - Arguments to find a KbsQuestion
   * @example
   * // Get one KbsQuestion
   * const kbsQuestion = await prisma.kbsQuestion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KbsQuestionFindUniqueArgs>(args: Prisma.SelectSubset<T, KbsQuestionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KbsQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsQuestionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KbsQuestion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KbsQuestionFindUniqueOrThrowArgs} args - Arguments to find a KbsQuestion
   * @example
   * // Get one KbsQuestion
   * const kbsQuestion = await prisma.kbsQuestion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KbsQuestionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KbsQuestionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KbsQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsQuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KbsQuestion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsQuestionFindFirstArgs} args - Arguments to find a KbsQuestion
   * @example
   * // Get one KbsQuestion
   * const kbsQuestion = await prisma.kbsQuestion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KbsQuestionFindFirstArgs>(args?: Prisma.SelectSubset<T, KbsQuestionFindFirstArgs<ExtArgs>>): Prisma.Prisma__KbsQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsQuestionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KbsQuestion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsQuestionFindFirstOrThrowArgs} args - Arguments to find a KbsQuestion
   * @example
   * // Get one KbsQuestion
   * const kbsQuestion = await prisma.kbsQuestion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KbsQuestionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KbsQuestionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KbsQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsQuestionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KbsQuestions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsQuestionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KbsQuestions
   * const kbsQuestions = await prisma.kbsQuestion.findMany()
   * 
   * // Get first 10 KbsQuestions
   * const kbsQuestions = await prisma.kbsQuestion.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kbsQuestionWithIdOnly = await prisma.kbsQuestion.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KbsQuestionFindManyArgs>(args?: Prisma.SelectSubset<T, KbsQuestionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsQuestionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a KbsQuestion.
   * @param {KbsQuestionCreateArgs} args - Arguments to create a KbsQuestion.
   * @example
   * // Create one KbsQuestion
   * const KbsQuestion = await prisma.kbsQuestion.create({
   *   data: {
   *     // ... data to create a KbsQuestion
   *   }
   * })
   * 
   */
  create<T extends KbsQuestionCreateArgs>(args: Prisma.SelectSubset<T, KbsQuestionCreateArgs<ExtArgs>>): Prisma.Prisma__KbsQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsQuestionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many KbsQuestions.
   * @param {KbsQuestionCreateManyArgs} args - Arguments to create many KbsQuestions.
   * @example
   * // Create many KbsQuestions
   * const kbsQuestion = await prisma.kbsQuestion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KbsQuestionCreateManyArgs>(args?: Prisma.SelectSubset<T, KbsQuestionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many KbsQuestions and returns the data saved in the database.
   * @param {KbsQuestionCreateManyAndReturnArgs} args - Arguments to create many KbsQuestions.
   * @example
   * // Create many KbsQuestions
   * const kbsQuestion = await prisma.kbsQuestion.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many KbsQuestions and only return the `id`
   * const kbsQuestionWithIdOnly = await prisma.kbsQuestion.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KbsQuestionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KbsQuestionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsQuestionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a KbsQuestion.
   * @param {KbsQuestionDeleteArgs} args - Arguments to delete one KbsQuestion.
   * @example
   * // Delete one KbsQuestion
   * const KbsQuestion = await prisma.kbsQuestion.delete({
   *   where: {
   *     // ... filter to delete one KbsQuestion
   *   }
   * })
   * 
   */
  delete<T extends KbsQuestionDeleteArgs>(args: Prisma.SelectSubset<T, KbsQuestionDeleteArgs<ExtArgs>>): Prisma.Prisma__KbsQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsQuestionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KbsQuestion.
   * @param {KbsQuestionUpdateArgs} args - Arguments to update one KbsQuestion.
   * @example
   * // Update one KbsQuestion
   * const kbsQuestion = await prisma.kbsQuestion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KbsQuestionUpdateArgs>(args: Prisma.SelectSubset<T, KbsQuestionUpdateArgs<ExtArgs>>): Prisma.Prisma__KbsQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsQuestionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KbsQuestions.
   * @param {KbsQuestionDeleteManyArgs} args - Arguments to filter KbsQuestions to delete.
   * @example
   * // Delete a few KbsQuestions
   * const { count } = await prisma.kbsQuestion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KbsQuestionDeleteManyArgs>(args?: Prisma.SelectSubset<T, KbsQuestionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KbsQuestions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsQuestionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KbsQuestions
   * const kbsQuestion = await prisma.kbsQuestion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KbsQuestionUpdateManyArgs>(args: Prisma.SelectSubset<T, KbsQuestionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KbsQuestions and returns the data updated in the database.
   * @param {KbsQuestionUpdateManyAndReturnArgs} args - Arguments to update many KbsQuestions.
   * @example
   * // Update many KbsQuestions
   * const kbsQuestion = await prisma.kbsQuestion.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more KbsQuestions and only return the `id`
   * const kbsQuestionWithIdOnly = await prisma.kbsQuestion.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KbsQuestionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KbsQuestionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsQuestionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one KbsQuestion.
   * @param {KbsQuestionUpsertArgs} args - Arguments to update or create a KbsQuestion.
   * @example
   * // Update or create a KbsQuestion
   * const kbsQuestion = await prisma.kbsQuestion.upsert({
   *   create: {
   *     // ... data to create a KbsQuestion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the KbsQuestion we want to update
   *   }
   * })
   */
  upsert<T extends KbsQuestionUpsertArgs>(args: Prisma.SelectSubset<T, KbsQuestionUpsertArgs<ExtArgs>>): Prisma.Prisma__KbsQuestionClient<runtime.Types.Result.GetResult<Prisma.$KbsQuestionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of KbsQuestions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsQuestionCountArgs} args - Arguments to filter KbsQuestions to count.
   * @example
   * // Count the number of KbsQuestions
   * const count = await prisma.kbsQuestion.count({
   *   where: {
   *     // ... the filter for the KbsQuestions we want to count
   *   }
   * })
  **/
  count<T extends KbsQuestionCountArgs>(
    args?: Prisma.Subset<T, KbsQuestionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KbsQuestionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KbsQuestion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsQuestionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KbsQuestionAggregateArgs>(args: Prisma.Subset<T, KbsQuestionAggregateArgs>): Prisma.PrismaPromise<GetKbsQuestionAggregateType<T>>

  /**
   * Group by KbsQuestion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KbsQuestionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KbsQuestionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KbsQuestionGroupByArgs['orderBy'] }
      : { orderBy?: KbsQuestionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KbsQuestionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKbsQuestionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KbsQuestion model
 */
readonly fields: KbsQuestionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KbsQuestion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KbsQuestionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  module<T extends Prisma.KbsModuleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KbsModuleDefaultArgs<ExtArgs>>): Prisma.Prisma__KbsModuleClient<runtime.Types.Result.GetResult<Prisma.$KbsModulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  answers<T extends Prisma.KbsQuestion$answersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KbsQuestion$answersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KbsAnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KbsQuestion model
 */
export interface KbsQuestionFieldRefs {
  readonly id: Prisma.FieldRef<"KbsQuestion", 'String'>
  readonly moduleId: Prisma.FieldRef<"KbsQuestion", 'String'>
  readonly text: Prisma.FieldRef<"KbsQuestion", 'String'>
  readonly type: Prisma.FieldRef<"KbsQuestion", 'String'>
  readonly createdAt: Prisma.FieldRef<"KbsQuestion", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"KbsQuestion", 'DateTime'>
}
    

// Custom InputTypes
/**
 * KbsQuestion findUnique
 */
export type KbsQuestionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestion
   */
  select?: Prisma.KbsQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsQuestion
   */
  omit?: Prisma.KbsQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsQuestionInclude<ExtArgs> | null
  /**
   * Filter, which KbsQuestion to fetch.
   */
  where: Prisma.KbsQuestionWhereUniqueInput
}

/**
 * KbsQuestion findUniqueOrThrow
 */
export type KbsQuestionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestion
   */
  select?: Prisma.KbsQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsQuestion
   */
  omit?: Prisma.KbsQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsQuestionInclude<ExtArgs> | null
  /**
   * Filter, which KbsQuestion to fetch.
   */
  where: Prisma.KbsQuestionWhereUniqueInput
}

/**
 * KbsQuestion findFirst
 */
export type KbsQuestionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestion
   */
  select?: Prisma.KbsQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsQuestion
   */
  omit?: Prisma.KbsQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsQuestionInclude<ExtArgs> | null
  /**
   * Filter, which KbsQuestion to fetch.
   */
  where?: Prisma.KbsQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsQuestions to fetch.
   */
  orderBy?: Prisma.KbsQuestionOrderByWithRelationInput | Prisma.KbsQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KbsQuestions.
   */
  cursor?: Prisma.KbsQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KbsQuestions.
   */
  distinct?: Prisma.KbsQuestionScalarFieldEnum | Prisma.KbsQuestionScalarFieldEnum[]
}

/**
 * KbsQuestion findFirstOrThrow
 */
export type KbsQuestionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestion
   */
  select?: Prisma.KbsQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsQuestion
   */
  omit?: Prisma.KbsQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsQuestionInclude<ExtArgs> | null
  /**
   * Filter, which KbsQuestion to fetch.
   */
  where?: Prisma.KbsQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsQuestions to fetch.
   */
  orderBy?: Prisma.KbsQuestionOrderByWithRelationInput | Prisma.KbsQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KbsQuestions.
   */
  cursor?: Prisma.KbsQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KbsQuestions.
   */
  distinct?: Prisma.KbsQuestionScalarFieldEnum | Prisma.KbsQuestionScalarFieldEnum[]
}

/**
 * KbsQuestion findMany
 */
export type KbsQuestionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestion
   */
  select?: Prisma.KbsQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsQuestion
   */
  omit?: Prisma.KbsQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsQuestionInclude<ExtArgs> | null
  /**
   * Filter, which KbsQuestions to fetch.
   */
  where?: Prisma.KbsQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KbsQuestions to fetch.
   */
  orderBy?: Prisma.KbsQuestionOrderByWithRelationInput | Prisma.KbsQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KbsQuestions.
   */
  cursor?: Prisma.KbsQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KbsQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KbsQuestions.
   */
  skip?: number
  distinct?: Prisma.KbsQuestionScalarFieldEnum | Prisma.KbsQuestionScalarFieldEnum[]
}

/**
 * KbsQuestion create
 */
export type KbsQuestionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestion
   */
  select?: Prisma.KbsQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsQuestion
   */
  omit?: Prisma.KbsQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsQuestionInclude<ExtArgs> | null
  /**
   * The data needed to create a KbsQuestion.
   */
  data: Prisma.XOR<Prisma.KbsQuestionCreateInput, Prisma.KbsQuestionUncheckedCreateInput>
}

/**
 * KbsQuestion createMany
 */
export type KbsQuestionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many KbsQuestions.
   */
  data: Prisma.KbsQuestionCreateManyInput | Prisma.KbsQuestionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KbsQuestion createManyAndReturn
 */
export type KbsQuestionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestion
   */
  select?: Prisma.KbsQuestionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KbsQuestion
   */
  omit?: Prisma.KbsQuestionOmit<ExtArgs> | null
  /**
   * The data used to create many KbsQuestions.
   */
  data: Prisma.KbsQuestionCreateManyInput | Prisma.KbsQuestionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsQuestionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * KbsQuestion update
 */
export type KbsQuestionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestion
   */
  select?: Prisma.KbsQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsQuestion
   */
  omit?: Prisma.KbsQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsQuestionInclude<ExtArgs> | null
  /**
   * The data needed to update a KbsQuestion.
   */
  data: Prisma.XOR<Prisma.KbsQuestionUpdateInput, Prisma.KbsQuestionUncheckedUpdateInput>
  /**
   * Choose, which KbsQuestion to update.
   */
  where: Prisma.KbsQuestionWhereUniqueInput
}

/**
 * KbsQuestion updateMany
 */
export type KbsQuestionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KbsQuestions.
   */
  data: Prisma.XOR<Prisma.KbsQuestionUpdateManyMutationInput, Prisma.KbsQuestionUncheckedUpdateManyInput>
  /**
   * Filter which KbsQuestions to update
   */
  where?: Prisma.KbsQuestionWhereInput
  /**
   * Limit how many KbsQuestions to update.
   */
  limit?: number
}

/**
 * KbsQuestion updateManyAndReturn
 */
export type KbsQuestionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestion
   */
  select?: Prisma.KbsQuestionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KbsQuestion
   */
  omit?: Prisma.KbsQuestionOmit<ExtArgs> | null
  /**
   * The data used to update KbsQuestions.
   */
  data: Prisma.XOR<Prisma.KbsQuestionUpdateManyMutationInput, Prisma.KbsQuestionUncheckedUpdateManyInput>
  /**
   * Filter which KbsQuestions to update
   */
  where?: Prisma.KbsQuestionWhereInput
  /**
   * Limit how many KbsQuestions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsQuestionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * KbsQuestion upsert
 */
export type KbsQuestionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestion
   */
  select?: Prisma.KbsQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsQuestion
   */
  omit?: Prisma.KbsQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsQuestionInclude<ExtArgs> | null
  /**
   * The filter to search for the KbsQuestion to update in case it exists.
   */
  where: Prisma.KbsQuestionWhereUniqueInput
  /**
   * In case the KbsQuestion found by the `where` argument doesn't exist, create a new KbsQuestion with this data.
   */
  create: Prisma.XOR<Prisma.KbsQuestionCreateInput, Prisma.KbsQuestionUncheckedCreateInput>
  /**
   * In case the KbsQuestion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KbsQuestionUpdateInput, Prisma.KbsQuestionUncheckedUpdateInput>
}

/**
 * KbsQuestion delete
 */
export type KbsQuestionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestion
   */
  select?: Prisma.KbsQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsQuestion
   */
  omit?: Prisma.KbsQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsQuestionInclude<ExtArgs> | null
  /**
   * Filter which KbsQuestion to delete.
   */
  where: Prisma.KbsQuestionWhereUniqueInput
}

/**
 * KbsQuestion deleteMany
 */
export type KbsQuestionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KbsQuestions to delete
   */
  where?: Prisma.KbsQuestionWhereInput
  /**
   * Limit how many KbsQuestions to delete.
   */
  limit?: number
}

/**
 * KbsQuestion.answers
 */
export type KbsQuestion$answersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsAnswer
   */
  select?: Prisma.KbsAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsAnswer
   */
  omit?: Prisma.KbsAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsAnswerInclude<ExtArgs> | null
  where?: Prisma.KbsAnswerWhereInput
  orderBy?: Prisma.KbsAnswerOrderByWithRelationInput | Prisma.KbsAnswerOrderByWithRelationInput[]
  cursor?: Prisma.KbsAnswerWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.KbsAnswerScalarFieldEnum | Prisma.KbsAnswerScalarFieldEnum[]
}

/**
 * KbsQuestion without action
 */
export type KbsQuestionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KbsQuestion
   */
  select?: Prisma.KbsQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KbsQuestion
   */
  omit?: Prisma.KbsQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KbsQuestionInclude<ExtArgs> | null
}
