import type { AdminLand, AdminReservation, LandLabel } from './types';

export const MOCK_LABELS: LandLabel[] = [
  { id: 'lbl-1', code: 'TFL', name: 'Titre Foncier Loti' },
  { id: 'lbl-2', code: 'VEFL', name: 'Vente en État Futur de Lotissement' },
  { id: 'lbl-3', code: 'VEFIL', name: "Vente en État Futur d'Immatriculation et de Lotissement" },
];

export const MOCK_ADMIN_LANDS: AdminLand[] = [
  {
    id: 'land-1',
    title: 'Terrain Dibamba',
    slug: 'terrain-dibamba',
    region: 'Littoral',
    city: 'Douala',
    neighborhood: 'Dibamba',
    latitude: 4.0511,
    longitude: 9.7679,
    sizeM2: 500,
    price: 7_500_000,
    label: MOCK_LABELS[0],
    pv: 1.0,
    ownerType: 'KAMBRIQ',
    titleNumber: 'TF/MFOUNDI/2024/0421',
    surfaceTitle: 500,
    isPublished: true,
    isVerified: true,
    status: 'AVAILABLE',
    media: [
      {
        id: 'm1',
        url: 'https://images.unsplash.com/photo-1764719396639-66ea940bb757?q=80&w=400',
        type: 'IMAGE',
      },
    ],
    createdAt: '2024-11-01T08:00:00Z',
    updatedAt: '2024-11-15T10:30:00Z',
  },
  {
    id: 'land-2',
    title: 'Terrain Yaoundé Bastos',
    slug: 'terrain-yaounde-bastos',
    region: 'Centre',
    city: 'Yaoundé',
    neighborhood: 'Bastos',
    latitude: 3.8834,
    longitude: 11.5086,
    sizeM2: 800,
    price: 18_000_000,
    label: MOCK_LABELS[1],
    pv: 1.5,
    ownerType: 'PARTNER',
    titleNumber: 'TF/CENTRE/2025/0089',
    isPublished: true,
    isVerified: true,
    status: 'RESERVED',
    media: [
      {
        id: 'm2',
        url: 'https://images.unsplash.com/photo-1764223531702-1614efb82e40?q=80&w=400',
        type: 'IMAGE',
      },
    ],
    createdAt: '2024-12-10T09:15:00Z',
    updatedAt: '2025-01-08T14:20:00Z',
  },
  {
    id: 'land-3',
    title: 'Terrain Bafoussam Tamdja',
    slug: 'terrain-bafoussam',
    region: 'Ouest',
    city: 'Bafoussam',
    neighborhood: 'Tamdja',
    sizeM2: 650,
    price: 5_200_000,
    label: MOCK_LABELS[0],
    pv: 0.8,
    ownerType: 'KAMBRIQ',
    isPublished: false,
    isVerified: false,
    status: 'AVAILABLE',
    media: [],
    createdAt: '2025-01-20T11:00:00Z',
    updatedAt: '2025-01-20T11:00:00Z',
  },
  {
    id: 'land-4',
    title: 'Terrain Kribi Bord de Mer',
    slug: 'terrain-kribi-bord-de-mer',
    region: 'Sud',
    city: 'Kribi',
    neighborhood: 'Bord de Mer',
    latitude: 2.9405,
    longitude: 9.907,
    sizeM2: 1_200,
    price: 32_000_000,
    label: MOCK_LABELS[1],
    pv: 2.0,
    ownerType: 'PARTNER',
    titleNumber: 'TF/SUD/2025/0034',
    surfaceTitle: 1200,
    isPublished: true,
    isVerified: true,
    status: 'SOLD',
    media: [
      {
        id: 'm4',
        url: 'https://images.unsplash.com/photo-1706333593437-90724b1d9432?q=80&w=400',
        type: 'IMAGE',
      },
    ],
    createdAt: '2025-01-05T08:30:00Z',
    updatedAt: '2025-02-20T16:45:00Z',
  },
  {
    id: 'land-5',
    title: 'Terrain Garoua Ngong',
    slug: 'terrain-garoua-ngong',
    region: 'Nord',
    city: 'Garoua',
    neighborhood: 'Ngong',
    sizeM2: 900,
    price: 4_000_000,
    label: MOCK_LABELS[2],
    pv: 0.9,
    ownerType: 'PARTNER',
    isPublished: false,
    isVerified: false,
    status: 'AVAILABLE',
    media: [],
    createdAt: '2025-02-10T10:00:00Z',
    updatedAt: '2025-02-10T10:00:00Z',
  },
];

export const MOCK_RESERVATIONS: AdminReservation[] = [
  {
    id: 'res-1',
    land: { id: 'land-2', title: 'Terrain Yaoundé Bastos', region: 'Centre', city: 'Yaoundé' },
    clientName: 'Marie Ngo',
    clientEmail: 'marie.ngo@gmail.com',
    clientPhone: '+237 677 123 456',
    agent: { id: 'agt-1', name: 'Jean Kameni' },
    depositAmount: 900_000,
    downPaymentConfirmed: false,
    status: 'PENDING',
    createdAt: '2025-01-10T14:30:00Z',
  },
  {
    id: 'res-2',
    land: { id: 'land-4', title: 'Terrain Kribi Bord de Mer', region: 'Sud', city: 'Kribi' },
    clientName: 'Paul Eteme',
    clientEmail: 'paul.eteme@yahoo.fr',
    clientPhone: '+33 6 12 34 56 78',
    agent: { id: 'agt-2', name: 'Marie Kouam' },
    depositAmount: 1_600_000,
    downPaymentConfirmed: true,
    status: 'CONFIRMED',
    createdAt: '2025-02-01T09:00:00Z',
  },
  {
    id: 'res-3',
    land: { id: 'land-4', title: 'Terrain Kribi Bord de Mer', region: 'Sud', city: 'Kribi' },
    clientName: 'Sophie Mbarga',
    clientEmail: 'sophie.m@outlook.com',
    clientPhone: '+1 514 555 7890',
    agent: { id: 'agt-2', name: 'Marie Kouam' },
    depositAmount: 1_600_000,
    downPaymentConfirmed: true,
    status: 'COMPLETED',
    createdAt: '2025-02-15T11:20:00Z',
  },
  {
    id: 'res-4',
    land: { id: 'land-1', title: 'Terrain Dibamba', region: 'Littoral', city: 'Douala' },
    clientName: 'Alain Fotso',
    clientEmail: 'a.fotso@gmail.com',
    clientPhone: '+237 699 456 789',
    agent: { id: 'agt-1', name: 'Jean Kameni' },
    depositAmount: 375_000,
    downPaymentConfirmed: false,
    status: 'CANCELLED',
    reason: 'Client a changé de projet immobilier.',
    createdAt: '2025-01-25T16:00:00Z',
  },
];
