
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `KamnetApplication` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model KamnetApplication
 * *
 * * A KCA certified user submits this to join KAMNET.
 * * Admin approves -> KAMNET record is created.
 */
export type KamnetApplicationModel = runtime.Types.Result.DefaultSelection<Prisma.$KamnetApplicationPayload>

export type AggregateKamnetApplication = {
  _count: KamnetApplicationCountAggregateOutputType | null
  _min: KamnetApplicationMinAggregateOutputType | null
  _max: KamnetApplicationMaxAggregateOutputType | null
}

export type KamnetApplicationMinAggregateOutputType = {
  id: string | null
  userId: string | null
  kcaNumber: string | null
  sponsorCode: string | null
  motivation: string | null
  status: $Enums.KamnetApplicationStatus | null
  reviewedBy: string | null
  reviewNote: string | null
  reviewedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type KamnetApplicationMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  kcaNumber: string | null
  sponsorCode: string | null
  motivation: string | null
  status: $Enums.KamnetApplicationStatus | null
  reviewedBy: string | null
  reviewNote: string | null
  reviewedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type KamnetApplicationCountAggregateOutputType = {
  id: number
  userId: number
  kcaNumber: number
  sponsorCode: number
  motivation: number
  status: number
  reviewedBy: number
  reviewNote: number
  reviewedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type KamnetApplicationMinAggregateInputType = {
  id?: true
  userId?: true
  kcaNumber?: true
  sponsorCode?: true
  motivation?: true
  status?: true
  reviewedBy?: true
  reviewNote?: true
  reviewedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type KamnetApplicationMaxAggregateInputType = {
  id?: true
  userId?: true
  kcaNumber?: true
  sponsorCode?: true
  motivation?: true
  status?: true
  reviewedBy?: true
  reviewNote?: true
  reviewedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type KamnetApplicationCountAggregateInputType = {
  id?: true
  userId?: true
  kcaNumber?: true
  sponsorCode?: true
  motivation?: true
  status?: true
  reviewedBy?: true
  reviewNote?: true
  reviewedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type KamnetApplicationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KamnetApplication to aggregate.
   */
  where?: Prisma.KamnetApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KamnetApplications to fetch.
   */
  orderBy?: Prisma.KamnetApplicationOrderByWithRelationInput | Prisma.KamnetApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KamnetApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KamnetApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KamnetApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KamnetApplications
  **/
  _count?: true | KamnetApplicationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KamnetApplicationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KamnetApplicationMaxAggregateInputType
}

export type GetKamnetApplicationAggregateType<T extends KamnetApplicationAggregateArgs> = {
      [P in keyof T & keyof AggregateKamnetApplication]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKamnetApplication[P]>
    : Prisma.GetScalarType<T[P], AggregateKamnetApplication[P]>
}




export type KamnetApplicationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KamnetApplicationWhereInput
  orderBy?: Prisma.KamnetApplicationOrderByWithAggregationInput | Prisma.KamnetApplicationOrderByWithAggregationInput[]
  by: Prisma.KamnetApplicationScalarFieldEnum[] | Prisma.KamnetApplicationScalarFieldEnum
  having?: Prisma.KamnetApplicationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KamnetApplicationCountAggregateInputType | true
  _min?: KamnetApplicationMinAggregateInputType
  _max?: KamnetApplicationMaxAggregateInputType
}

export type KamnetApplicationGroupByOutputType = {
  id: string
  userId: string
  kcaNumber: string
  sponsorCode: string | null
  motivation: string | null
  status: $Enums.KamnetApplicationStatus
  reviewedBy: string | null
  reviewNote: string | null
  reviewedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: KamnetApplicationCountAggregateOutputType | null
  _min: KamnetApplicationMinAggregateOutputType | null
  _max: KamnetApplicationMaxAggregateOutputType | null
}

type GetKamnetApplicationGroupByPayload<T extends KamnetApplicationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KamnetApplicationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KamnetApplicationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KamnetApplicationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KamnetApplicationGroupByOutputType[P]>
      }
    >
  >



export type KamnetApplicationWhereInput = {
  AND?: Prisma.KamnetApplicationWhereInput | Prisma.KamnetApplicationWhereInput[]
  OR?: Prisma.KamnetApplicationWhereInput[]
  NOT?: Prisma.KamnetApplicationWhereInput | Prisma.KamnetApplicationWhereInput[]
  id?: Prisma.StringFilter<"KamnetApplication"> | string
  userId?: Prisma.StringFilter<"KamnetApplication"> | string
  kcaNumber?: Prisma.StringFilter<"KamnetApplication"> | string
  sponsorCode?: Prisma.StringNullableFilter<"KamnetApplication"> | string | null
  motivation?: Prisma.StringNullableFilter<"KamnetApplication"> | string | null
  status?: Prisma.EnumKamnetApplicationStatusFilter<"KamnetApplication"> | $Enums.KamnetApplicationStatus
  reviewedBy?: Prisma.StringNullableFilter<"KamnetApplication"> | string | null
  reviewNote?: Prisma.StringNullableFilter<"KamnetApplication"> | string | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"KamnetApplication"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"KamnetApplication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KamnetApplication"> | Date | string
}

export type KamnetApplicationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kcaNumber?: Prisma.SortOrder
  sponsorCode?: Prisma.SortOrderInput | Prisma.SortOrder
  motivation?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  reviewedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewNote?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KamnetApplicationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.KamnetApplicationWhereInput | Prisma.KamnetApplicationWhereInput[]
  OR?: Prisma.KamnetApplicationWhereInput[]
  NOT?: Prisma.KamnetApplicationWhereInput | Prisma.KamnetApplicationWhereInput[]
  kcaNumber?: Prisma.StringFilter<"KamnetApplication"> | string
  sponsorCode?: Prisma.StringNullableFilter<"KamnetApplication"> | string | null
  motivation?: Prisma.StringNullableFilter<"KamnetApplication"> | string | null
  status?: Prisma.EnumKamnetApplicationStatusFilter<"KamnetApplication"> | $Enums.KamnetApplicationStatus
  reviewedBy?: Prisma.StringNullableFilter<"KamnetApplication"> | string | null
  reviewNote?: Prisma.StringNullableFilter<"KamnetApplication"> | string | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"KamnetApplication"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"KamnetApplication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KamnetApplication"> | Date | string
}, "id" | "userId">

export type KamnetApplicationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kcaNumber?: Prisma.SortOrder
  sponsorCode?: Prisma.SortOrderInput | Prisma.SortOrder
  motivation?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  reviewedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewNote?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.KamnetApplicationCountOrderByAggregateInput
  _max?: Prisma.KamnetApplicationMaxOrderByAggregateInput
  _min?: Prisma.KamnetApplicationMinOrderByAggregateInput
}

export type KamnetApplicationScalarWhereWithAggregatesInput = {
  AND?: Prisma.KamnetApplicationScalarWhereWithAggregatesInput | Prisma.KamnetApplicationScalarWhereWithAggregatesInput[]
  OR?: Prisma.KamnetApplicationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KamnetApplicationScalarWhereWithAggregatesInput | Prisma.KamnetApplicationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"KamnetApplication"> | string
  userId?: Prisma.StringWithAggregatesFilter<"KamnetApplication"> | string
  kcaNumber?: Prisma.StringWithAggregatesFilter<"KamnetApplication"> | string
  sponsorCode?: Prisma.StringNullableWithAggregatesFilter<"KamnetApplication"> | string | null
  motivation?: Prisma.StringNullableWithAggregatesFilter<"KamnetApplication"> | string | null
  status?: Prisma.EnumKamnetApplicationStatusWithAggregatesFilter<"KamnetApplication"> | $Enums.KamnetApplicationStatus
  reviewedBy?: Prisma.StringNullableWithAggregatesFilter<"KamnetApplication"> | string | null
  reviewNote?: Prisma.StringNullableWithAggregatesFilter<"KamnetApplication"> | string | null
  reviewedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"KamnetApplication"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"KamnetApplication"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"KamnetApplication"> | Date | string
}

export type KamnetApplicationCreateInput = {
  id?: string
  userId: string
  kcaNumber: string
  sponsorCode?: string | null
  motivation?: string | null
  status?: $Enums.KamnetApplicationStatus
  reviewedBy?: string | null
  reviewNote?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KamnetApplicationUncheckedCreateInput = {
  id?: string
  userId: string
  kcaNumber: string
  sponsorCode?: string | null
  motivation?: string | null
  status?: $Enums.KamnetApplicationStatus
  reviewedBy?: string | null
  reviewNote?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KamnetApplicationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  kcaNumber?: Prisma.StringFieldUpdateOperationsInput | string
  sponsorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  motivation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumKamnetApplicationStatusFieldUpdateOperationsInput | $Enums.KamnetApplicationStatus
  reviewedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewNote?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KamnetApplicationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  kcaNumber?: Prisma.StringFieldUpdateOperationsInput | string
  sponsorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  motivation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumKamnetApplicationStatusFieldUpdateOperationsInput | $Enums.KamnetApplicationStatus
  reviewedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewNote?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KamnetApplicationCreateManyInput = {
  id?: string
  userId: string
  kcaNumber: string
  sponsorCode?: string | null
  motivation?: string | null
  status?: $Enums.KamnetApplicationStatus
  reviewedBy?: string | null
  reviewNote?: string | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KamnetApplicationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  kcaNumber?: Prisma.StringFieldUpdateOperationsInput | string
  sponsorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  motivation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumKamnetApplicationStatusFieldUpdateOperationsInput | $Enums.KamnetApplicationStatus
  reviewedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewNote?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KamnetApplicationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  kcaNumber?: Prisma.StringFieldUpdateOperationsInput | string
  sponsorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  motivation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumKamnetApplicationStatusFieldUpdateOperationsInput | $Enums.KamnetApplicationStatus
  reviewedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewNote?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KamnetApplicationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kcaNumber?: Prisma.SortOrder
  sponsorCode?: Prisma.SortOrder
  motivation?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reviewedBy?: Prisma.SortOrder
  reviewNote?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KamnetApplicationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kcaNumber?: Prisma.SortOrder
  sponsorCode?: Prisma.SortOrder
  motivation?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reviewedBy?: Prisma.SortOrder
  reviewNote?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KamnetApplicationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kcaNumber?: Prisma.SortOrder
  sponsorCode?: Prisma.SortOrder
  motivation?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reviewedBy?: Prisma.SortOrder
  reviewNote?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EnumKamnetApplicationStatusFieldUpdateOperationsInput = {
  set?: $Enums.KamnetApplicationStatus
}



export type KamnetApplicationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  kcaNumber?: boolean
  sponsorCode?: boolean
  motivation?: boolean
  status?: boolean
  reviewedBy?: boolean
  reviewNote?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["kamnetApplication"]>

export type KamnetApplicationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  kcaNumber?: boolean
  sponsorCode?: boolean
  motivation?: boolean
  status?: boolean
  reviewedBy?: boolean
  reviewNote?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["kamnetApplication"]>

export type KamnetApplicationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  kcaNumber?: boolean
  sponsorCode?: boolean
  motivation?: boolean
  status?: boolean
  reviewedBy?: boolean
  reviewNote?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["kamnetApplication"]>

export type KamnetApplicationSelectScalar = {
  id?: boolean
  userId?: boolean
  kcaNumber?: boolean
  sponsorCode?: boolean
  motivation?: boolean
  status?: boolean
  reviewedBy?: boolean
  reviewNote?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type KamnetApplicationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "kcaNumber" | "sponsorCode" | "motivation" | "status" | "reviewedBy" | "reviewNote" | "reviewedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["kamnetApplication"]>

export type $KamnetApplicationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KamnetApplication"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    kcaNumber: string
    sponsorCode: string | null
    motivation: string | null
    status: $Enums.KamnetApplicationStatus
    reviewedBy: string | null
    reviewNote: string | null
    reviewedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["kamnetApplication"]>
  composites: {}
}

export type KamnetApplicationGetPayload<S extends boolean | null | undefined | KamnetApplicationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KamnetApplicationPayload, S>

export type KamnetApplicationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KamnetApplicationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KamnetApplicationCountAggregateInputType | true
  }

export interface KamnetApplicationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KamnetApplication'], meta: { name: 'KamnetApplication' } }
  /**
   * Find zero or one KamnetApplication that matches the filter.
   * @param {KamnetApplicationFindUniqueArgs} args - Arguments to find a KamnetApplication
   * @example
   * // Get one KamnetApplication
   * const kamnetApplication = await prisma.kamnetApplication.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KamnetApplicationFindUniqueArgs>(args: Prisma.SelectSubset<T, KamnetApplicationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KamnetApplicationClient<runtime.Types.Result.GetResult<Prisma.$KamnetApplicationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KamnetApplication that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KamnetApplicationFindUniqueOrThrowArgs} args - Arguments to find a KamnetApplication
   * @example
   * // Get one KamnetApplication
   * const kamnetApplication = await prisma.kamnetApplication.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KamnetApplicationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KamnetApplicationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KamnetApplicationClient<runtime.Types.Result.GetResult<Prisma.$KamnetApplicationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KamnetApplication that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KamnetApplicationFindFirstArgs} args - Arguments to find a KamnetApplication
   * @example
   * // Get one KamnetApplication
   * const kamnetApplication = await prisma.kamnetApplication.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KamnetApplicationFindFirstArgs>(args?: Prisma.SelectSubset<T, KamnetApplicationFindFirstArgs<ExtArgs>>): Prisma.Prisma__KamnetApplicationClient<runtime.Types.Result.GetResult<Prisma.$KamnetApplicationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KamnetApplication that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KamnetApplicationFindFirstOrThrowArgs} args - Arguments to find a KamnetApplication
   * @example
   * // Get one KamnetApplication
   * const kamnetApplication = await prisma.kamnetApplication.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KamnetApplicationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KamnetApplicationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KamnetApplicationClient<runtime.Types.Result.GetResult<Prisma.$KamnetApplicationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KamnetApplications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KamnetApplicationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KamnetApplications
   * const kamnetApplications = await prisma.kamnetApplication.findMany()
   * 
   * // Get first 10 KamnetApplications
   * const kamnetApplications = await prisma.kamnetApplication.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kamnetApplicationWithIdOnly = await prisma.kamnetApplication.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KamnetApplicationFindManyArgs>(args?: Prisma.SelectSubset<T, KamnetApplicationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KamnetApplicationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a KamnetApplication.
   * @param {KamnetApplicationCreateArgs} args - Arguments to create a KamnetApplication.
   * @example
   * // Create one KamnetApplication
   * const KamnetApplication = await prisma.kamnetApplication.create({
   *   data: {
   *     // ... data to create a KamnetApplication
   *   }
   * })
   * 
   */
  create<T extends KamnetApplicationCreateArgs>(args: Prisma.SelectSubset<T, KamnetApplicationCreateArgs<ExtArgs>>): Prisma.Prisma__KamnetApplicationClient<runtime.Types.Result.GetResult<Prisma.$KamnetApplicationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many KamnetApplications.
   * @param {KamnetApplicationCreateManyArgs} args - Arguments to create many KamnetApplications.
   * @example
   * // Create many KamnetApplications
   * const kamnetApplication = await prisma.kamnetApplication.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KamnetApplicationCreateManyArgs>(args?: Prisma.SelectSubset<T, KamnetApplicationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many KamnetApplications and returns the data saved in the database.
   * @param {KamnetApplicationCreateManyAndReturnArgs} args - Arguments to create many KamnetApplications.
   * @example
   * // Create many KamnetApplications
   * const kamnetApplication = await prisma.kamnetApplication.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many KamnetApplications and only return the `id`
   * const kamnetApplicationWithIdOnly = await prisma.kamnetApplication.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KamnetApplicationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KamnetApplicationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KamnetApplicationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a KamnetApplication.
   * @param {KamnetApplicationDeleteArgs} args - Arguments to delete one KamnetApplication.
   * @example
   * // Delete one KamnetApplication
   * const KamnetApplication = await prisma.kamnetApplication.delete({
   *   where: {
   *     // ... filter to delete one KamnetApplication
   *   }
   * })
   * 
   */
  delete<T extends KamnetApplicationDeleteArgs>(args: Prisma.SelectSubset<T, KamnetApplicationDeleteArgs<ExtArgs>>): Prisma.Prisma__KamnetApplicationClient<runtime.Types.Result.GetResult<Prisma.$KamnetApplicationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KamnetApplication.
   * @param {KamnetApplicationUpdateArgs} args - Arguments to update one KamnetApplication.
   * @example
   * // Update one KamnetApplication
   * const kamnetApplication = await prisma.kamnetApplication.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KamnetApplicationUpdateArgs>(args: Prisma.SelectSubset<T, KamnetApplicationUpdateArgs<ExtArgs>>): Prisma.Prisma__KamnetApplicationClient<runtime.Types.Result.GetResult<Prisma.$KamnetApplicationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KamnetApplications.
   * @param {KamnetApplicationDeleteManyArgs} args - Arguments to filter KamnetApplications to delete.
   * @example
   * // Delete a few KamnetApplications
   * const { count } = await prisma.kamnetApplication.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KamnetApplicationDeleteManyArgs>(args?: Prisma.SelectSubset<T, KamnetApplicationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KamnetApplications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KamnetApplicationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KamnetApplications
   * const kamnetApplication = await prisma.kamnetApplication.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KamnetApplicationUpdateManyArgs>(args: Prisma.SelectSubset<T, KamnetApplicationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KamnetApplications and returns the data updated in the database.
   * @param {KamnetApplicationUpdateManyAndReturnArgs} args - Arguments to update many KamnetApplications.
   * @example
   * // Update many KamnetApplications
   * const kamnetApplication = await prisma.kamnetApplication.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more KamnetApplications and only return the `id`
   * const kamnetApplicationWithIdOnly = await prisma.kamnetApplication.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KamnetApplicationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KamnetApplicationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KamnetApplicationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one KamnetApplication.
   * @param {KamnetApplicationUpsertArgs} args - Arguments to update or create a KamnetApplication.
   * @example
   * // Update or create a KamnetApplication
   * const kamnetApplication = await prisma.kamnetApplication.upsert({
   *   create: {
   *     // ... data to create a KamnetApplication
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the KamnetApplication we want to update
   *   }
   * })
   */
  upsert<T extends KamnetApplicationUpsertArgs>(args: Prisma.SelectSubset<T, KamnetApplicationUpsertArgs<ExtArgs>>): Prisma.Prisma__KamnetApplicationClient<runtime.Types.Result.GetResult<Prisma.$KamnetApplicationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of KamnetApplications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KamnetApplicationCountArgs} args - Arguments to filter KamnetApplications to count.
   * @example
   * // Count the number of KamnetApplications
   * const count = await prisma.kamnetApplication.count({
   *   where: {
   *     // ... the filter for the KamnetApplications we want to count
   *   }
   * })
  **/
  count<T extends KamnetApplicationCountArgs>(
    args?: Prisma.Subset<T, KamnetApplicationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KamnetApplicationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KamnetApplication.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KamnetApplicationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KamnetApplicationAggregateArgs>(args: Prisma.Subset<T, KamnetApplicationAggregateArgs>): Prisma.PrismaPromise<GetKamnetApplicationAggregateType<T>>

  /**
   * Group by KamnetApplication.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KamnetApplicationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KamnetApplicationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KamnetApplicationGroupByArgs['orderBy'] }
      : { orderBy?: KamnetApplicationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KamnetApplicationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKamnetApplicationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KamnetApplication model
 */
readonly fields: KamnetApplicationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KamnetApplication.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KamnetApplicationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KamnetApplication model
 */
export interface KamnetApplicationFieldRefs {
  readonly id: Prisma.FieldRef<"KamnetApplication", 'String'>
  readonly userId: Prisma.FieldRef<"KamnetApplication", 'String'>
  readonly kcaNumber: Prisma.FieldRef<"KamnetApplication", 'String'>
  readonly sponsorCode: Prisma.FieldRef<"KamnetApplication", 'String'>
  readonly motivation: Prisma.FieldRef<"KamnetApplication", 'String'>
  readonly status: Prisma.FieldRef<"KamnetApplication", 'KamnetApplicationStatus'>
  readonly reviewedBy: Prisma.FieldRef<"KamnetApplication", 'String'>
  readonly reviewNote: Prisma.FieldRef<"KamnetApplication", 'String'>
  readonly reviewedAt: Prisma.FieldRef<"KamnetApplication", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"KamnetApplication", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"KamnetApplication", 'DateTime'>
}
    

// Custom InputTypes
/**
 * KamnetApplication findUnique
 */
export type KamnetApplicationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KamnetApplication
   */
  select?: Prisma.KamnetApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KamnetApplication
   */
  omit?: Prisma.KamnetApplicationOmit<ExtArgs> | null
  /**
   * Filter, which KamnetApplication to fetch.
   */
  where: Prisma.KamnetApplicationWhereUniqueInput
}

/**
 * KamnetApplication findUniqueOrThrow
 */
export type KamnetApplicationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KamnetApplication
   */
  select?: Prisma.KamnetApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KamnetApplication
   */
  omit?: Prisma.KamnetApplicationOmit<ExtArgs> | null
  /**
   * Filter, which KamnetApplication to fetch.
   */
  where: Prisma.KamnetApplicationWhereUniqueInput
}

/**
 * KamnetApplication findFirst
 */
export type KamnetApplicationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KamnetApplication
   */
  select?: Prisma.KamnetApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KamnetApplication
   */
  omit?: Prisma.KamnetApplicationOmit<ExtArgs> | null
  /**
   * Filter, which KamnetApplication to fetch.
   */
  where?: Prisma.KamnetApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KamnetApplications to fetch.
   */
  orderBy?: Prisma.KamnetApplicationOrderByWithRelationInput | Prisma.KamnetApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KamnetApplications.
   */
  cursor?: Prisma.KamnetApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KamnetApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KamnetApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KamnetApplications.
   */
  distinct?: Prisma.KamnetApplicationScalarFieldEnum | Prisma.KamnetApplicationScalarFieldEnum[]
}

/**
 * KamnetApplication findFirstOrThrow
 */
export type KamnetApplicationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KamnetApplication
   */
  select?: Prisma.KamnetApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KamnetApplication
   */
  omit?: Prisma.KamnetApplicationOmit<ExtArgs> | null
  /**
   * Filter, which KamnetApplication to fetch.
   */
  where?: Prisma.KamnetApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KamnetApplications to fetch.
   */
  orderBy?: Prisma.KamnetApplicationOrderByWithRelationInput | Prisma.KamnetApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KamnetApplications.
   */
  cursor?: Prisma.KamnetApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KamnetApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KamnetApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KamnetApplications.
   */
  distinct?: Prisma.KamnetApplicationScalarFieldEnum | Prisma.KamnetApplicationScalarFieldEnum[]
}

/**
 * KamnetApplication findMany
 */
export type KamnetApplicationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KamnetApplication
   */
  select?: Prisma.KamnetApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KamnetApplication
   */
  omit?: Prisma.KamnetApplicationOmit<ExtArgs> | null
  /**
   * Filter, which KamnetApplications to fetch.
   */
  where?: Prisma.KamnetApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KamnetApplications to fetch.
   */
  orderBy?: Prisma.KamnetApplicationOrderByWithRelationInput | Prisma.KamnetApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KamnetApplications.
   */
  cursor?: Prisma.KamnetApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KamnetApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KamnetApplications.
   */
  skip?: number
  distinct?: Prisma.KamnetApplicationScalarFieldEnum | Prisma.KamnetApplicationScalarFieldEnum[]
}

/**
 * KamnetApplication create
 */
export type KamnetApplicationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KamnetApplication
   */
  select?: Prisma.KamnetApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KamnetApplication
   */
  omit?: Prisma.KamnetApplicationOmit<ExtArgs> | null
  /**
   * The data needed to create a KamnetApplication.
   */
  data: Prisma.XOR<Prisma.KamnetApplicationCreateInput, Prisma.KamnetApplicationUncheckedCreateInput>
}

/**
 * KamnetApplication createMany
 */
export type KamnetApplicationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many KamnetApplications.
   */
  data: Prisma.KamnetApplicationCreateManyInput | Prisma.KamnetApplicationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KamnetApplication createManyAndReturn
 */
export type KamnetApplicationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KamnetApplication
   */
  select?: Prisma.KamnetApplicationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KamnetApplication
   */
  omit?: Prisma.KamnetApplicationOmit<ExtArgs> | null
  /**
   * The data used to create many KamnetApplications.
   */
  data: Prisma.KamnetApplicationCreateManyInput | Prisma.KamnetApplicationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KamnetApplication update
 */
export type KamnetApplicationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KamnetApplication
   */
  select?: Prisma.KamnetApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KamnetApplication
   */
  omit?: Prisma.KamnetApplicationOmit<ExtArgs> | null
  /**
   * The data needed to update a KamnetApplication.
   */
  data: Prisma.XOR<Prisma.KamnetApplicationUpdateInput, Prisma.KamnetApplicationUncheckedUpdateInput>
  /**
   * Choose, which KamnetApplication to update.
   */
  where: Prisma.KamnetApplicationWhereUniqueInput
}

/**
 * KamnetApplication updateMany
 */
export type KamnetApplicationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KamnetApplications.
   */
  data: Prisma.XOR<Prisma.KamnetApplicationUpdateManyMutationInput, Prisma.KamnetApplicationUncheckedUpdateManyInput>
  /**
   * Filter which KamnetApplications to update
   */
  where?: Prisma.KamnetApplicationWhereInput
  /**
   * Limit how many KamnetApplications to update.
   */
  limit?: number
}

/**
 * KamnetApplication updateManyAndReturn
 */
export type KamnetApplicationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KamnetApplication
   */
  select?: Prisma.KamnetApplicationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KamnetApplication
   */
  omit?: Prisma.KamnetApplicationOmit<ExtArgs> | null
  /**
   * The data used to update KamnetApplications.
   */
  data: Prisma.XOR<Prisma.KamnetApplicationUpdateManyMutationInput, Prisma.KamnetApplicationUncheckedUpdateManyInput>
  /**
   * Filter which KamnetApplications to update
   */
  where?: Prisma.KamnetApplicationWhereInput
  /**
   * Limit how many KamnetApplications to update.
   */
  limit?: number
}

/**
 * KamnetApplication upsert
 */
export type KamnetApplicationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KamnetApplication
   */
  select?: Prisma.KamnetApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KamnetApplication
   */
  omit?: Prisma.KamnetApplicationOmit<ExtArgs> | null
  /**
   * The filter to search for the KamnetApplication to update in case it exists.
   */
  where: Prisma.KamnetApplicationWhereUniqueInput
  /**
   * In case the KamnetApplication found by the `where` argument doesn't exist, create a new KamnetApplication with this data.
   */
  create: Prisma.XOR<Prisma.KamnetApplicationCreateInput, Prisma.KamnetApplicationUncheckedCreateInput>
  /**
   * In case the KamnetApplication was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KamnetApplicationUpdateInput, Prisma.KamnetApplicationUncheckedUpdateInput>
}

/**
 * KamnetApplication delete
 */
export type KamnetApplicationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KamnetApplication
   */
  select?: Prisma.KamnetApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KamnetApplication
   */
  omit?: Prisma.KamnetApplicationOmit<ExtArgs> | null
  /**
   * Filter which KamnetApplication to delete.
   */
  where: Prisma.KamnetApplicationWhereUniqueInput
}

/**
 * KamnetApplication deleteMany
 */
export type KamnetApplicationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KamnetApplications to delete
   */
  where?: Prisma.KamnetApplicationWhereInput
  /**
   * Limit how many KamnetApplications to delete.
   */
  limit?: number
}

/**
 * KamnetApplication without action
 */
export type KamnetApplicationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KamnetApplication
   */
  select?: Prisma.KamnetApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KamnetApplication
   */
  omit?: Prisma.KamnetApplicationOmit<ExtArgs> | null
}
