module.exports = {
  displayName: 'ctest',
  preset: '../../jest.preset.js',
  testEnvironment: 'node',
  transform: {
    '^.+\\.[tj]s$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.spec.json' }],
  },
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageDirectory: '../../coverage/libs/common',
  coverageReporters: ['lcov', 'text-summary'],
  // Measure every source file, not only the ones a test happens to import.
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.spec.ts',
    '!src/**/__test__/**',
    '!src/**/*.module.ts',
    '!src/**/*.d.ts',
    // Generated Prisma clients. Gitignored (.gitignore: libs/common/src/prisma/*)
    // and regenerated by postinstall, so measuring them measures Prisma.
    '!src/prisma/**',
  ],
};
