import type { HardCodedKind } from './hard-coded-values';

/**
 * J15 - the declared debt: every value still written in place of a design token,
 * file by file, with its count and its reason.
 *
 * Measured on 2 October with the rules in `hard-coded-values.ts` (J10's method,
 * comments excluded): 1 132 colour classes outside the system in 136 files, 14
 * arbitrary spacings, 4 arbitrary type values, and the root error boundary's
 * inline styles, which are an exemption and not a debt.
 *
 * **A listed value is a debt, not an absolution.** `design-tokens-only.spec.ts`
 * holds three things: a file not listed carries none; a listed file carries
 * exactly its count, so draining one means lowering it here; and this list is
 * no longer, and its counts sum no higher, than the figures pinned in the spec.
 * The list only shrinks. Adding an entry, or raising a count or a pin, is a
 * reviewed change that says in the diff that the system lost ground.
 */
export interface DesignDebt {
  /** Relative to apps/web/src. */
  readonly file: string;
  readonly kind: HardCodedKind;
  readonly count: number;
  readonly reason: string;
}

export const DESIGN_DEBT: readonly DesignDebt[] = [
  {
    file: 'app/[locale]/(site)/(app)/account/confirm-email-change/page.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/(app)/account/page.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/(app)/admin/identities/[id]/page.tsx',
    kind: 'colour-class',
    count: 6,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/(app)/agent/profile/page.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/(app)/invite/page.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/(app)/lands/page.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/(app)/layout.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/(app)/mylands/page.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/(app)/reservations/page.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/(auth)/login/page.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/(auth)/reactivate/page.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/(auth)/verify-email/page.tsx',
    kind: 'colour-class',
    count: 5,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/about/page.tsx',
    kind: 'arbitrary-spacing',
    count: 1,
    reason: 'J15 debt: a spacing value outside the scale, from before the guard.',
  },
  {
    file: 'app/[locale]/(site)/blog/page.tsx',
    kind: 'colour-class',
    count: 7,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/blog/page.tsx',
    kind: 'arbitrary-spacing',
    count: 1,
    reason: 'J15 debt: a spacing value outside the scale, from before the guard.',
  },
  {
    file: 'app/[locale]/(site)/contact/page.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/contact/page.tsx',
    kind: 'arbitrary-spacing',
    count: 1,
    reason: 'J15 debt: a spacing value outside the scale, from before the guard.',
  },
  {
    file: 'app/[locale]/(site)/faq/page.tsx',
    kind: 'colour-class',
    count: 3,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/faq/page.tsx',
    kind: 'arbitrary-spacing',
    count: 1,
    reason: 'J15 debt: a spacing value outside the scale, from before the guard.',
  },
  {
    file: 'app/[locale]/(site)/kamnet/apply/apply-form.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/kamnet/apply/page.tsx',
    kind: 'colour-class',
    count: 8,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/legal/layout.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/legal/layout.tsx',
    kind: 'arbitrary-spacing',
    count: 1,
    reason: 'J15 debt: a spacing value outside the scale, from before the guard.',
  },
  {
    file: 'app/[locale]/(site)/methode/page.tsx',
    kind: 'colour-class',
    count: 5,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/methode/page.tsx',
    kind: 'arbitrary-spacing',
    count: 1,
    reason: 'J15 debt: a spacing value outside the scale, from before the guard.',
  },
  {
    file: 'app/[locale]/(site)/plan/page.tsx',
    kind: 'colour-class',
    count: 5,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/plan/page.tsx',
    kind: 'arbitrary-spacing',
    count: 1,
    reason: 'J15 debt: a spacing value outside the scale, from before the guard.',
  },
  {
    file: 'app/[locale]/(site)/products/kamnet/annuaire/page.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/products/kamnet/page.tsx',
    kind: 'colour-class',
    count: 1,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/products/kbs/page.tsx',
    kind: 'colour-class',
    count: 1,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/products/lands/page.tsx',
    kind: 'colour-class',
    count: 1,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/products/verify/page.tsx',
    kind: 'colour-class',
    count: 1,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/verify-certificate/[certificateNumber]/page.tsx',
    kind: 'colour-class',
    count: 13,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/(site)/verify-certificate/[certificateNumber]/page.tsx',
    kind: 'arbitrary-spacing',
    count: 1,
    reason: 'J15 debt: a spacing value outside the scale, from before the guard.',
  },
  {
    file: 'app/[locale]/not-found.tsx',
    kind: 'colour-class',
    count: 3,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'app/[locale]/not-found.tsx',
    kind: 'arbitrary-spacing',
    count: 1,
    reason: 'J15 debt: a spacing value outside the scale, from before the guard.',
  },
  {
    file: 'app/global-error.tsx',
    kind: 'inline-style',
    count: 4,
    reason:
      'Not debt: a root error boundary renders its own <html> without globals.css, so a token resolves to nothing there; its colours come from lib/brand-colors.ts (J9).',
  },
  {
    file: 'components/about/about-hero.tsx',
    kind: 'colour-class',
    count: 1,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/about/about-timeline.tsx',
    kind: 'colour-class',
    count: 6,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/about/mission-vision.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/about/offices-section.tsx',
    kind: 'colour-class',
    count: 6,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/about/team-section.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/account/account-preferences-card.tsx',
    kind: 'colour-class',
    count: 3,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/app-shell/mobile-nav.tsx',
    kind: 'colour-class',
    count: 5,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/app-shell/nav-item.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/app-shell/sidebar.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/app-shell/sidebar.tsx',
    kind: 'arbitrary-typography',
    count: 1,
    reason: 'J15 debt: a type value outside the scale, from before the guard.',
  },
  {
    file: 'components/app-shell/user-menu.tsx',
    kind: 'colour-class',
    count: 5,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/auth/auth-shell.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/cms/policy-document.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/cms/portable-text.tsx',
    kind: 'colour-class',
    count: 19,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/contact/contact-form.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/contact/contact-info.tsx',
    kind: 'colour-class',
    count: 5,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/faq/faq-content.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/floating/quick-actions.tsx',
    kind: 'arbitrary-typography',
    count: 1,
    reason: 'J15 debt: a type value outside the scale, from before the guard.',
  },
  {
    file: 'components/hero/index.tsx',
    kind: 'colour-class',
    count: 5,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/identities/identity-queue-content.tsx',
    kind: 'colour-class',
    count: 12,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/identities/identity-review-action.tsx',
    kind: 'colour-class',
    count: 11,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/identity/identity-document-upload.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/invite/invite-form.tsx',
    kind: 'colour-class',
    count: 28,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kamnet/agents-management-content.tsx',
    kind: 'colour-class',
    count: 18,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs-admin/admin-kbs-subnav.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs-admin/candidate-detail-content.tsx',
    kind: 'colour-class',
    count: 18,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs-admin/candidates-list-content.tsx',
    kind: 'colour-class',
    count: 12,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs-admin/certificates-list-content.tsx',
    kind: 'colour-class',
    count: 17,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs-admin/course-editor-content.tsx',
    kind: 'colour-class',
    count: 22,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs-admin/exams-list-content.tsx',
    kind: 'colour-class',
    count: 12,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs-admin/pending-candidates-banner.tsx',
    kind: 'colour-class',
    count: 8,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs-admin/question-banks-content.tsx',
    kind: 'colour-class',
    count: 21,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs-admin/settings-form.tsx',
    kind: 'colour-class',
    count: 1,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs/kbs-awaiting-verification.tsx',
    kind: 'colour-class',
    count: 5,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs/kbs-certificate-view.tsx',
    kind: 'colour-class',
    count: 12,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs/kbs-certificate-view.tsx',
    kind: 'arbitrary-typography',
    count: 1,
    reason: 'J15 debt: a type value outside the scale, from before the guard.',
  },
  {
    file: 'components/kbs/kbs-dashboard-content.tsx',
    kind: 'colour-class',
    count: 15,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs/kbs-enroll-form.tsx',
    kind: 'colour-class',
    count: 19,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs/kbs-exam-content.tsx',
    kind: 'colour-class',
    count: 17,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs/kbs-exam-grading.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs/kbs-exam-results.tsx',
    kind: 'colour-class',
    count: 8,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs/kbs-exam-session.tsx',
    kind: 'colour-class',
    count: 14,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs/kbs-lesson-view.tsx',
    kind: 'colour-class',
    count: 9,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs/kbs-module-detail-content.tsx',
    kind: 'colour-class',
    count: 19,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs/kbs-quiz-taker.tsx',
    kind: 'colour-class',
    count: 16,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/kbs/kbs-subnav.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/landing/hero.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/landing/partners-section.tsx',
    kind: 'colour-class',
    count: 1,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/landing/products-services.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/landing/why-kambriq.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/lands/app/land-card.tsx',
    kind: 'colour-class',
    count: 17,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/lands/app/land-detail-content.tsx',
    kind: 'colour-class',
    count: 15,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/lands/app/land-documents.tsx',
    kind: 'colour-class',
    count: 5,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/lands/app/land-gallery.tsx',
    kind: 'colour-class',
    count: 3,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/lands/app/land-info-panel.tsx',
    kind: 'colour-class',
    count: 9,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/lands/app/lands-catalog-content.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/lands/app/lands-filters.tsx',
    kind: 'colour-class',
    count: 10,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/lands/app/reserve-form.tsx',
    kind: 'colour-class',
    count: 9,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/layout/navbar.tsx',
    kind: 'colour-class',
    count: 16,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/mylands/journey-steps.tsx',
    kind: 'colour-class',
    count: 10,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/mylands/my-payment-content.tsx',
    kind: 'colour-class',
    count: 17,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/mylands/mylands-content.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/mylands/purchase-card.tsx',
    kind: 'colour-class',
    count: 12,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/mylands/purchase-detail-content.tsx',
    kind: 'colour-class',
    count: 53,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/mylands/purchase-documents.tsx',
    kind: 'colour-class',
    count: 9,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/mylands/request-payment-card.tsx',
    kind: 'colour-class',
    count: 15,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/payments-admin/advance-payment-action.tsx',
    kind: 'colour-class',
    count: 7,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/payments-admin/channel-label.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/payments-admin/payment-detail-content.tsx',
    kind: 'colour-class',
    count: 23,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/payments-admin/payment-purpose-label.tsx',
    kind: 'colour-class',
    count: 6,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/payments-admin/payment-state-badge.tsx',
    kind: 'colour-class',
    count: 18,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/payments-admin/payments-list-content.tsx',
    kind: 'colour-class',
    count: 7,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/payments-admin/proof-link.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/payments-admin/receipt-picker.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/payments-admin/record-receipt-form.tsx',
    kind: 'colour-class',
    count: 15,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/payments-admin/request-queue-content.tsx',
    kind: 'colour-class',
    count: 16,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/payments-admin/send-instructions-action.tsx',
    kind: 'colour-class',
    count: 20,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/payments-admin/validate-payment-action.tsx',
    kind: 'colour-class',
    count: 9,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/placeholder-page.tsx',
    kind: 'colour-class',
    count: 6,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/kamnet/why-kabriq-agent.tsx',
    kind: 'colour-class',
    count: 6,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/kamnet/why-kamnet-agent.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/kbs/about.tsx',
    kind: 'colour-class',
    count: 1,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/kbs/admission.tsx',
    kind: 'colour-class',
    count: 8,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/kbs/advantages-kca.tsx',
    kind: 'colour-class',
    count: 3,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/kbs/modules.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/kbs/what-you-will-learn.tsx',
    kind: 'colour-class',
    count: 5,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/kbs/who-can register.tsx',
    kind: 'colour-class',
    count: 5,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/lands/admin/constants.ts',
    kind: 'colour-class',
    count: 18,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/lands/admin/lands-admin-content.tsx',
    kind: 'colour-class',
    count: 12,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/lands/admin/lands-table.tsx',
    kind: 'colour-class',
    count: 6,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/lands/admin/reservation-detail-dialog.tsx',
    kind: 'colour-class',
    count: 25,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/lands/admin/reservations-table.tsx',
    kind: 'colour-class',
    count: 3,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/lands/land-types.tsx',
    kind: 'colour-class',
    count: 3,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/lands/why-buy-at-kambriq.tsx',
    kind: 'colour-class',
    count: 3,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/verify/hero.tsx',
    kind: 'colour-class',
    count: 17,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/products/verify/ready-to-verify.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/reservations/reservation-card.tsx',
    kind: 'colour-class',
    count: 17,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/reservations/reservation-client-documents-panel.tsx',
    kind: 'colour-class',
    count: 8,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/reservations/reservation-client-info-card.tsx',
    kind: 'colour-class',
    count: 9,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/reservations/reservation-detail-content.tsx',
    kind: 'colour-class',
    count: 8,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/reservations/reservation-land-summary-card.tsx',
    kind: 'colour-class',
    count: 10,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/reservations/reservation-timeline.tsx',
    kind: 'colour-class',
    count: 17,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/reservations/reservations-content.tsx',
    kind: 'colour-class',
    count: 8,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/section/header/index.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/steps/step/index.tsx',
    kind: 'colour-class',
    count: 1,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/ui/alert.tsx',
    kind: 'colour-class',
    count: 1,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/ui/button.tsx',
    kind: 'arbitrary-typography',
    count: 1,
    reason: 'J15 debt: a type value outside the scale, from before the guard.',
  },
  {
    file: 'components/ui/card.tsx',
    kind: 'colour-class',
    count: 2,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/ui/dialog.tsx',
    kind: 'colour-class',
    count: 1,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/ui/dropdown-menu.tsx',
    kind: 'colour-class',
    count: 4,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/ui/input-group.tsx',
    kind: 'arbitrary-spacing',
    count: 4,
    reason: 'J15 debt: a spacing value outside the scale, from before the guard.',
  },
  {
    file: 'components/ui/sheet.tsx',
    kind: 'colour-class',
    count: 9,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'components/ui/tabs.tsx',
    kind: 'arbitrary-spacing',
    count: 1,
    reason: 'J15 debt: a spacing value outside the scale, from before the guard.',
  },
  {
    file: 'constants/land.ts',
    kind: 'colour-class',
    count: 26,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
  {
    file: 'lib/kbs.ts',
    kind: 'colour-class',
    count: 28,
    reason: 'J10 debt: colour classes from before the design system, measured 2 October.',
  },
];
