import { randomUUID } from 'node:crypto';
import { attempt, openTestDatabase, SQLSTATE, type TestDatabase } from './lands-test-db';

/**
 * G19 - one column carried two units. The API and the seed read `Land.price`
 * as the parcel's total, the web as a price per m2, and on a 480 m2 parcel the
 * web showed a balance of 1 631 830 000 beside a deposit of 170 000.
 *
 * Visquis decided both figures are kept, each in its own column. The total is
 * the source of truth; the price per m2 is GENERATED by the database, so the
 * two cannot drift: nobody can write the second, and it follows the first.
 */
describe('G19 - the total and the price per m2 cannot disagree', () => {
  let db: TestDatabase;

  beforeAll(() => {
    db = openTestDatabase();
  });

  afterAll(async () => {
    await db.close();
  });

  const createLand = async (totalPrice: number, sizeM2: number) => {
    const tag = randomUUID();
    const label = await db.prisma.landLabel.upsert({
      where: { code: 'TFL' },
      create: { code: 'TFL', name: 'Titre foncier' },
      update: {},
    });
    return db.prisma.land.create({
      data: {
        title: `G19 ${tag}`,
        slug: `g19-${tag}`,
        description: 'G19 fixture.',
        region: 'Est',
        sizeM2,
        totalPrice,
        labelId: label.id,
      },
    });
  };

  it('the parcel from the diagnosis: 3 400 000 over 480 m2 is 7 083 per m2', async () => {
    const land = await createLand(3_400_000, 480);
    expect(land.totalPrice).toBe(3_400_000);
    expect(land.pricePerM2).toBe(7083);
  });

  it('follows the total when the total changes', async () => {
    const land = await createLand(3_400_000, 480);
    const updated = await db.prisma.land.update({
      where: { id: land.id },
      data: { totalPrice: 4_800_000 },
    });
    expect(updated.pricePerM2).toBe(10_000);
  });

  it('follows the surface when the surface changes', async () => {
    const land = await createLand(3_400_000, 480);
    const updated = await db.prisma.land.update({ where: { id: land.id }, data: { sizeM2: 500 } });
    expect(updated.pricePerM2).toBe(6800);
  });

  it('refuses a direct write to the price per m2', async () => {
    const land = await createLand(3_400_000, 480);
    expect(
      await attempt(db.pool, 'UPDATE "Land" SET "pricePerM2" = 1 WHERE id = $1', [land.id]),
    ).toMatchObject({ code: SQLSTATE.GENERATED_ALWAYS });
  });
});
