
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more KbsCourses
 * const kbsCourses = await prisma.kbsCourse.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model KbsCourse
 * 
 */
export type KbsCourse = Prisma.KbsCourseModel
/**
 * Model KbsModule
 * 
 */
export type KbsModule = Prisma.KbsModuleModel
/**
 * Model KbsLesson
 * 
 */
export type KbsLesson = Prisma.KbsLessonModel
/**
 * Model KbsQuestion
 * 
 */
export type KbsQuestion = Prisma.KbsQuestionModel
/**
 * Model KbsAnswer
 * 
 */
export type KbsAnswer = Prisma.KbsAnswerModel
/**
 * Model KbsExamQuestion
 * 
 */
export type KbsExamQuestion = Prisma.KbsExamQuestionModel
/**
 * Model KbsExamQuestionAnswer
 * 
 */
export type KbsExamQuestionAnswer = Prisma.KbsExamQuestionAnswerModel
/**
 * Model KbsCandidate
 * 
 */
export type KbsCandidate = Prisma.KbsCandidateModel
/**
 * Model KbsCandidateProgress
 * 
 */
export type KbsCandidateProgress = Prisma.KbsCandidateProgressModel
/**
 * Model KbsExam
 * 
 */
export type KbsExam = Prisma.KbsExamModel
/**
 * Model KbsExamAnswer
 * 
 */
export type KbsExamAnswer = Prisma.KbsExamAnswerModel
/**
 * Model KbsExamAnswerSelection
 * 
 */
export type KbsExamAnswerSelection = Prisma.KbsExamAnswerSelectionModel
/**
 * Model KbsSettings
 * 
 */
export type KbsSettings = Prisma.KbsSettingsModel
/**
 * Model KbsCertificate
 * 
 */
export type KbsCertificate = Prisma.KbsCertificateModel
