
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  LandLabel: 'LandLabel',
  Land: 'Land',
  LandMedia: 'LandMedia',
  LandDocument: 'LandDocument',
  LandReservation: 'LandReservation',
  LandPriceHistory: 'LandPriceHistory'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const LandLabelScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LandLabelScalarFieldEnum = (typeof LandLabelScalarFieldEnum)[keyof typeof LandLabelScalarFieldEnum]


export const LandScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  description: 'description',
  region: 'region',
  city: 'city',
  neighborhood: 'neighborhood',
  latitude: 'latitude',
  longitude: 'longitude',
  sizeM2: 'sizeM2',
  price: 'price',
  labelId: 'labelId',
  status: 'status',
  isPublished: 'isPublished',
  pv: 'pv',
  ownerType: 'ownerType',
  partnerId: 'partnerId',
  isVerified: 'isVerified',
  verifiedAt: 'verifiedAt',
  verificationRef: 'verificationRef',
  titleNumber: 'titleNumber',
  surfaceTitle: 'surfaceTitle',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LandScalarFieldEnum = (typeof LandScalarFieldEnum)[keyof typeof LandScalarFieldEnum]


export const LandMediaScalarFieldEnum = {
  id: 'id',
  landId: 'landId',
  type: 'type',
  url: 'url',
  caption: 'caption',
  order: 'order',
  createdAt: 'createdAt'
} as const

export type LandMediaScalarFieldEnum = (typeof LandMediaScalarFieldEnum)[keyof typeof LandMediaScalarFieldEnum]


export const LandDocumentScalarFieldEnum = {
  id: 'id',
  landId: 'landId',
  type: 'type',
  name: 'name',
  url: 'url',
  uploadedBy: 'uploadedBy',
  isPrivate: 'isPrivate',
  createdAt: 'createdAt'
} as const

export type LandDocumentScalarFieldEnum = (typeof LandDocumentScalarFieldEnum)[keyof typeof LandDocumentScalarFieldEnum]


export const LandReservationScalarFieldEnum = {
  id: 'id',
  landId: 'landId',
  agentUserId: 'agentUserId',
  clientUserId: 'clientUserId',
  clientName: 'clientName',
  clientEmail: 'clientEmail',
  clientPhone: 'clientPhone',
  status: 'status',
  downPaymentAmount: 'downPaymentAmount',
  downPaymentConfirmed: 'downPaymentConfirmed',
  confirmedBy: 'confirmedBy',
  confirmedAt: 'confirmedAt',
  completedAt: 'completedAt',
  cancelReason: 'cancelReason',
  cancelledAt: 'cancelledAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LandReservationScalarFieldEnum = (typeof LandReservationScalarFieldEnum)[keyof typeof LandReservationScalarFieldEnum]


export const LandPriceHistoryScalarFieldEnum = {
  id: 'id',
  landId: 'landId',
  previousPrice: 'previousPrice',
  newPrice: 'newPrice',
  changedBy: 'changedBy',
  reason: 'reason',
  changedAt: 'changedAt'
} as const

export type LandPriceHistoryScalarFieldEnum = (typeof LandPriceHistoryScalarFieldEnum)[keyof typeof LandPriceHistoryScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

